### ISSUE TITLE
EnderIO: Inventory Panel Issue with Storage Drawers

### ISSUE THREAD

**Issue by ozhound** [whatthedrunk/allthemods#10]
Inventory panel doesn't recognize items if they are > one stack when connected via enderio item conduit to the drawer controller

I tried reducing an items quantity from 98 to 64 and it showed up in the list of items in the inventory panel.

Tested on an iron chest with 244 Stone and it worked fine.

**Comment by Carrots4U** [comment]
This is a known and a "feature". It cannot be resolved because of how Storage Drawers holds it's items. It's the same as it was with AE2 in 1.7.10.
