### ISSUE TITLE
[1.10.2 v1.9] WAILA showing Enrichment Chamber for multiple Mekanism machines

### ISSUE THREAD

**Issue by claywar** [whatthedrunk/allthemods#100]
::Precondition
1.  Metallurgic Infuser, Crusher, Enrichment Chamber, and Energized Smelter are placed in world.

::Procedure
1.  Observe WAILA tooltip for each machine.  In this case, machines are placed side by side powered by the same line of power, and Metallurgic Infuser was the first to be placed in this line.

Note: No other placement has been tested

::Observation
-- Expected Result
Tooltip should change based on the machine observed
-- Observed Result
Tooltip for all of these items show Enrichment Chamber

**Comment by DnTheMn** [comment]
if you havent done so already can u post this on the mekanism git hub the page can be found here https://github.com/aidancbrady/Mekanism/issues

**Comment by FiveEYZ** [comment]
https://github.com/aidancbrady/Mekanism/issues/3598

aidancbrady says he is confident its on WAILAs end.

**Comment by Carrots4U** [comment]
For reference, https://bitbucket.org/ProfMobius/waila/issues/273/194-showing-incorrect-block-type-mekanism

**Comment by whatthedrunk** [comment]
Bug has been reported to the mod author so I will close this here as we just have to wait for an update. Thanks!
