### ISSUE TITLE
Blood Magic - in-game docu through Guide-API

### ISSUE THREAD

**Issue by neomelonas** [whatthedrunk/allthemods#102]
Per [their Curse page](https://minecraft.curseforge.com/projects/blood-magic), Blood Magic is now routing their in-game documentation through [Guide-API](https://minecraft.curseforge.com/projects/guide-api).

>The in-game documentation is being worked on! If you want to use it in its current form, download Guide-API from here and craft the "Sanugine Scientiem." It will give you information on how to begin your adventures with the mod!

**Comment by Carrots4U** [comment]
Last time we added Guide API, it crashed on launch, and it hasn't received another update since, so when that gets fixed it will be added :)

**Comment by neomelonas** [comment]
Really? What version was the crash on launch from? [Guide-API-1.9.4-2.0.0-40](https://minecraft.curseforge.com/projects/guide-api/files/2317032) is a semi-recent alpha build, but seems to be running OK for me right now.

**Comment by whatthedrunk** [comment]
It has to do with this. https://github.com/TeamAmeriFrance/Guide-API/issues/38

As soon as Charset and Abyssalcraft update we will be able to update forge and add it.
