### ISSUE TITLE
All the mods 1.9 FPS problem

### ISSUE THREAD

**Issue by SirJu83** [whatthedrunk/allthemods#103]
Issue Description:

I updated my world from 1.8 hotfix to 1.9 and began to have weird and constant fps drops.
What happens:

 In 1.8hotfix, I had an average 50 fps (60 in the wild, around 40 fps in my base, mid game so not a lot of stuff). I tried to get some clues on what happens, and I noticed the ticks part in the debug screen start to increase as soon as I start the game, and is around 70% constantly after that. Changing location doesn't help, I hardly get 15 fps wherever I go with very bad lag spikes and freeze, be it my base, the wild, the end, nether or rftools dimension. I also tried creating a brand new world, and got the same problem.

I got some profiler report (A /sampler export, and a /debug profile over 1 minute), but I don't know enough java nor minecraft modding to read them, but if that can helps, I can send them to you.

After some trials, I noticed that downgrading forge to 2018 (the version of 1.8) from 2028 (the new one in 1.9) solved the issue for me. Tried also to upgrade forge to the lastest version (2044 some days ago and 2046 today) but it crashed at start (was predictable since not all mods from the pack are up to date with forge it seems)

What you expected to happen:

A performance level somewhat similar to the previous version. It goes from confortable in 1.8 to unplayable in 1.9

Steps to reproduce:

1.
2.
3.
...

Version of All the Mods: 1.9

Added mods (Optifine, Fastcraft, etc.):

None. I use the default modpack.

Misc:

If that matters, I play on my laptop over "in home streaming" from steam. I've never had any problems on modded minecraft with that, but I don't know. 

My computer specs : 
Host (Desktop) I5-3570k, 8g, ATI 7950

Client (laptop) I7-2670QM, 4g, GT540M

Just a word for you too, thanks a lot for the pack, It's incredibly stable for an experimental one, and quite well designed, keep up the good work. =)

**Comment by ZiggyAdventures** [comment]
Try Terrain Animation to Off, seems to provide a FPS boost and Ram smoothing.

**Comment by SirJu83** [comment]
Seems to have solved my issue. I updated to 1.10 with forge 2026, installed optifine (never used it before), and so far fps are normal. Thanks man. =)

**Comment by jmcaffee** [comment]
I've updated from 1.6-Hotfix to 1.11 and now get lag spikes once I've been playing for 30 mins ~ 1 hr.

Exiting the world and reentering does not stop the spikes, Exiting the game entirely and restarting it does fix the spikes for another 30~60 minutes. My memory settings are at 512 and 4096 MB but I've noticed Java is using almost 7 GB at restart. 

I believe something's leaking memory.

**Comment by Carrots4U** [comment]
@jmcaffee please see if you still experience a memory leak in the current update, I believe it might have been fixed.

**Comment by jmcaffee** [comment]
I haven't experienced the issue since I updated to 1.12 this morning.

**Comment by Carrots4U** [comment]
Just as I thought :) If it comes back reopen this otherwise I'm closing it
