### ISSUE TITLE
Mekanism Crafting Formula

### ISSUE THREAD

**Issue by ADAMHG** [whatthedrunk/allthemods#104]
Issue Description:
Unable to craft Crafting Formula for mekanism

What happens: try to make dosnt do anything.

What you expected to happen: craft a crafting formula

Steps to reproduce:

1.Collect items to make
2.Place in crafting table
3.No output
...

Version of All the Mods:  v1.9
![2016-08-07_19 31 12](https://cloud.githubusercontent.com/assets/20885372/17461610/e4e7aabe-5cd5-11e6-8d15-3e6853a437ec.png)
![2016-08-07_19 31 15](https://cloud.githubusercontent.com/assets/20885372/17461609/e4e6fcae-5cd5-11e6-9db4-f569485eaef9.png)

**Comment by DnTheMn** [comment]
if you dont mind could you plase make an issue on the actual mekanism github it can be found here https://github.com/aidancbrady/Mekanism/issues

**Comment by Carrots4U** [comment]
I will work on a fix, will report back if it works.

**Comment by DnTheMn** [comment]
fixed with next version of mekanism
