### ISSUE TITLE
Mod Suggestion: Flood Lights

### ISSUE THREAD

**Issue by Lintesrion** [whatthedrunk/allthemods#106]
Hello there!
First: loving the pack and thanks for all your work!
There's a huge lack of good, large ground- covering light sources and spamming torches or lamps isn't a very convenient way to do so. That's why I wanted to suggest a small and simple mod:
https://mods.curse.com/mc-mods/minecraft/224728-floodlights

Thanks in advance!
Greetings, 
Linte

**Comment by whatthedrunk** [comment]
Post #108 will now be for all future requests. We had the floodlights in our 1.9 pack so maybe I can add it.
