### ISSUE TITLE
Mod Suggestion: Craftable Elytra

### ISSUE THREAD

**Issue by Chaogomu** [whatthedrunk/allthemods#107]
Most servers that run this pack have an issue. While the Elytra is world gen and thus theoretically infinite, however most servers have world border enabled.

With a world border of 2000 blocks you will have an average of 4 available Elytra. (and dragon heads)

The problem comes in when more than 4 people play on a server. The Elytra, while fun on it's own, is also used in a few crafting recipes. Also if one is lost to durability or such, it cannot be replaced.

This mod adds a crafting recipe https://mods.curse.com/mc-mods/minecraft/243146-craftable-elytra

Recipes can also be added through Mine Tweaker, but that's more effort.

When Armor Plus is re-added this will be an even larger issue. We will also then need a way to get more dragon heads. Mine Tweaker will be the only option at that point.

**Comment by sokratis12GR** [comment]
> `When Armor Plus is re-added this will be an even larger issue`

No, very soon ArmorPlus will integrate a recipe for the elytra (of course with config) and no recipe will require Dragon Head

**Comment by Gaelan** [comment]
Elytra can't be lost to durability. They break like TCon tools.

**Comment by Carrots4U** [comment]
We don't plan on adding craftable elytras sorry. Ruins the point of exploration in the end if you can just craft everything directly.
