### ISSUE TITLE
[Official] Mod Suggestion Post

### ISSUE THREAD

**Issue by SpiCraftsman** [whatthedrunk/allthemods#108]
Hello can  you add  ic2 , Veinminer , ftb lib and ftb utilities 
Thanks for your time Spi.

**Comment by DnTheMn** [comment]
ic2 will be back once its updated to a point where its not game breaking 
vainminer "probably" wont be added.
ftb lib and ftb utils "might" be added back once it is updated to a point where it also wont corrupt worlds and stuff

**Comment by SpiCraftsman** [comment]
Thank for yous answer

**Comment by SpiCraftsman** [comment]
Everyone can suggest mods in this suggestion

**Comment by Chaogomu** [comment]
https://mods.curse.com/mc-mods/minecraft/248424-daedalus-labyrinth

The pack lacks some exploration, this one might help.

**Comment by Hardeh** [comment]
https://minecraft.curseforge.com/projects/chicken-chunks
It's time to have proper chunk loaders ;)

**Comment by Eladkay** [comment]
https://minecraft.curseforge.com/projects/silimatics
I'm kind of biased but I really think it's a cool mod. It adds Oculation and lens welding.

**Comment by nan0bug00** [comment]
Remove WTF Ores, it sucks.

**Comment by DnTheMn** [comment]
@nan0bug00 if you dont like the mod thats fine but its not likely it will be removed if your on a singleplayer you can remove it

**Comment by nan0bug00** [comment]
If I wanted to run this single player I wouldn't be asking.

**Comment by DnTheMn** [comment]
@nan0bug00 i wasnt aware you were on a server

**Comment by nan0bug00** [comment]
What about WTF Expedition is so important to All The Mods?  Is it the breaking blocks three times before they actually disappear?  When I think of great mods, one that basically turns block lag into a feature is right up there with one that corrupts worlds and replaces all the sounds with ghast noises.

**Comment by DnTheMn** [comment]
i havent noticed any block lag could it be the server your on is lagging or you ping is high?
this pack is intensive.

**Comment by nan0bug00** [comment]
It's not block lag.  It's making ores that need to be broken in 3 stages before they disappear.  Which is very much like block lag in practice, you know, since you have to break something and then it comes back unbroken and you have to break it again until the server catches up.

I'm just curious about what it is in the mod that appeals to you, since so far the only thing I've experienced from the mod is that it makes mining annoying and difficult.  The pack is already difficult enough with the Infernal Mobs, why make mining more annoying?  For what purpose?

**Comment by whatthedrunk** [comment]
the ores have been disabled in the last 2 versions of the pack, that's what the big red warning sign is all about.

**Comment by nan0bug00** [comment]
Well that's the worst part of it, so thank you.  Though I'd encourage you to just remove the whole thing.  It adds little of value, it's poorly optimized, poorly documented, it makes more difficult mobs in a pack that's already got infernal mobs which is difficult enough to deal with.  It just seems like the kind of mod better suited as an add on than something that should be a default.  But its your pack.

**Comment by nan0bug00** [comment]
Any chance of getting Chicken Chunks back until FTB Utilities remembers how to chunkload when people are offline?

**Comment by Omega696** [comment]
Remove IC2, redundant mod that lags servers.

**Comment by koalalord9999** [comment]
I would like quantum flux added to the pack :d on server, and would rather not have to tell everyone to download it hehe

**Comment by eriico39hi** [comment]
I would like to recommend adding cyberware to the pack. I also second quantum flux.

**Comment by Carrots4U** [comment]
@eriico39hi we had cyberware in the pack but sadly it caused extreme lag so it had to be removed.

**Comment by CvoidWyvern** [comment]
Any chance we could get Login Shield or something similar?  I for one don't enjoy getting killed before I completely connect to a server.

**Comment by whatthedrunk** [comment]
Cleaned this up and moved it to https://github.com/whatthedrunk/allthemods/issues/173
