### ISSUE TITLE
[1.10.2 v1.11 - Server] Disabled jars

### ISSUE THREAD

**Issue by jmcaffee** [whatthedrunk/allthemods#109]
After upgrading from `1.10.2 v1.6-Hotfix` to `1.20.2 v1.11` using the `Server Files` archive (with MultiMC), there are some issues.

- JEI: Just Enough Resources stops the load with errors because it cannot find JEI.
- JourneyMap missing after successful load

I did not see anything in the change logs about removing these mods and after enabling them and running the pack I've noticed no issues.

Suggested fix:

- Rename `minecraft/mods/jei_1.10.2-3.8.0.241.jar.disabled` to `minecraft/mods/jei_1.10.2-3.8.0.241.jar`
- Rename `minecraft/mods/journeymap-1.10.2-5.2.4-unlimited.jar.disabled` to `minecraft/mods/journeymap-1.10.2-5.2.4-unlimited.jar`

**Comment by Hirsu** [comment]
I've noticed the same thing. A few mods were .disabled by default in the server files. These include:
- custommainmenu
- just enough forestry bees
- jei
- journeymap
- more overlays
- resourceloader (dependency for custommainmenu)
- waila and waila harvestability
- wawla

I had some issues with getting the server to fire up, so I re-enabled these mods.
It doesn't seem to cause any issues and I can play just fine now, but maybe there is a reason these mods were disabled.

If so, please inform us so we don't do more harm than good ;)

**Comment by sokratis12GR** [comment]
These mods were disabled, because all of these are Client-Side mods

**Comment by jmcaffee** [comment]
Thanks.
