### ISSUE TITLE
Tinkers Construct: Alum Brass doesnt work

### ISSUE THREAD

**Issue by ozhound** [whatthedrunk/allthemods#11]
Cannot create a cast using molten alum brass. Gold and Clay do work.

**Comment by Janitor53** [comment]
You can use "brass" instead of "aluminium brass".

**Comment by ozhound** [comment]
Thanks, still a legitimate bug though.

**Comment by whatthedrunk** [comment]
From what I can tell it seems to be a Mod change or they have not added it yet.
