### ISSUE TITLE
Unable to extract power from ender io capacitor

### ISSUE THREAD

**Issue by 9arriflex9** [whatthedrunk/allthemods#111]
Issue Description:

Hello,

I'm unable to export power from Ender IO Capacitor to Mekanism Universal Cable.

[ScreenShot](http://imgur.com/a/NemH3)

What happens:
No power output

What you expected to happen:
RF or J ouputing to the cable

Steps to reproduce:

1.Fill a Ender IO capacitor
2.Configure one ouput on the capacitor
3.Plug mekanism cable to it
...

I tired without using the Mekanism configurator.
And has showed in the screenshot i tried using the configuration push/pull fonction

Version of All the Mods:
latest

Added mods (Optifine, Fastcraft, etc.):

None

**Comment by DietmarKrause** [comment]
it seemed to be an issue with mekanism and reported there in the github: https://github.com/aidancbrady/Mekanism/issues/3660
