### ISSUE TITLE
fatally missing blocks and items (dark utils)

### ISSUE THREAD

**Issue by DnTheMn** [whatthedrunk/allthemods#112]
just reported the fatally missing blocks and items, to dark utils as removing the mod will allow players to connect just a heads up ill keep you guys updated on what they say this is more for a record

**Comment by autumnfire** [comment]
There's a mismatch between the server configs and the client configs. The client has the correct config file that should be copied to the server. Specifically, the "Mysterious Potion" should be disabled as it has been on all previous releases.

**Comment by DnTheMn** [comment]
its not my server but this isnt a real issue more so i can let drunk know and keep a record

**Comment by K1ltu** [comment]
i have located the exact issue Dark utilities is looking for darkutils.cfg and the file in the ServerFiles package it is DarkUtils.cfg on a windows system capitalization doesnt matter however on linux it does so Dark Utilities looks for darkutils.cfg and cant find it so it creates it ignoring DarkUtils.cfg

**Comment by Carrots4U** [comment]
Fixed in the next update, reopen if it comes back.
