### ISSUE TITLE
Disconnect Twice When Joining a Server After Client Start

### ISSUE THREAD

**Issue by Hazmatik** [whatthedrunk/allthemods#114]
Issue Description: When I start up the client, first time I try to join a server I get an error "A Fatal Error has occurred, this connection is terminated", then when I try to join again I get just an error "Disconnected", then the third time it finally connects. After that everytime I go to join it connects fine until I restart the client again then it goes through the same thing. The second disconnect could be on the server side as it has always happened but the "Fatal Error" didn't happen until after the server updated to version 1.11

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: Have to click to join server 3 times to actually connect.

What you expected to happen: Connect on the first try.

Steps to reproduce:

1. Start client
2. Try to join server.
3. Try to join again.
...

Version of All the Mods: 1.11

Added mods (Optifine, Fastcraft, etc.):

1. Optifine
2.
3.
...

**Comment by Carrots4U** [comment]
Same as https://github.com/whatthedrunk/allthemods/issues/115

**Comment by radiocrack** [comment]
This used to happen to me all the time.   Since 13b this no longer happens.  

I thought it was only me because I run a server and client at the same time on the same computer.
