### ISSUE TITLE
Cooking For Blockheads & Harvestcraft break Mekanism Progression

### ISSUE THREAD

**Issue by Hazmatik** [whatthedrunk/allthemods#119]
With the Cooking For Blockheads multi-block kitchen and a Pam's Harvestcraft pot you can basically get unlimited amounts of Pam's Harvestcraft salt for free (can sit there and spam shift + click on the recipe in the cooking table). The salt can then be used to make Brine from Mekanism, which means you can achieve 4x ore processing without having to build the thermal evaporation towers as the intended progression through Mekanism. A simple solution would be to disable Pam's Harvestcraft salt from being used to create brine and only allow the Mekanism salt (which has to be mined in word) to be used to create the brine or the towers.

**Comment by DnTheMn** [comment]
im not sure where to report this to i would be tempted to post on both the mekanism and cooking for blockheads git hubs for you if you dont mind

**Comment by DnTheMn** [comment]
"Not a big enough issue." RIP, thats what the Mekanism dev had to say

**Comment by Doomgull** [comment]
This has been around since at least 1.6.x
