### ISSUE TITLE
Refined Storage Crafting Grid client crash

### ISSUE THREAD

**Issue by dhawk312** [whatthedrunk/allthemods#120]
Issue Description:
Random crashes when attempting to use the Refined Storage Crafting Grid. Opening the RS Crafting Gird crashes client. Happens every 20-60 minutes. Sometimes immediately upon entering the server, other times after an hour but usually around the 20-30 min mark.

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:
MC crashes at times when using Refined Storage's Crafting Grid. Crash logs are provided. 

What you expected to happen:
No crash?

Steps to reproduce:

1. Open RS Crafting Grid. Behavior is erratic but seems to be happening more frequently on versions 1.13. Happen very infrequently prior to 1.13 but then about hourly on 1.13 for each player on the server.
2.
3.
...

Version of All the Mods:
1.12 and 1.13. 
[crash-2016-08-16_20.02.58-client.txt](https://github.com/whatthedrunk/allthemods/files/423587/crash-2016-08-16_20.02.58-client.txt)
[crash-2016-08-16_21.26.42-client.txt](https://github.com/whatthedrunk/allthemods/files/423588/crash-2016-08-16_21.26.42-client.txt)

Added mods (Optifine, Fastcraft, etc.):

1.
2.
3.
...

**Comment by Hazmatik** [comment]
I recieve this crash as well, also happened to me today using the wireless grid. It's fixed in the most recent version of Refined Storage.
raoulvdberge/refinedstorage#266

**Comment by Carrots4U** [comment]
Thanks for the report, when the mod is updated the pack will also.

**Comment by whatthedrunk** [comment]
This seems to be fixed now. Reopen if not.
