### ISSUE TITLE
Soul shards dupe

### ISSUE THREAD

**Issue by Beefjerkyy** [whatthedrunk/allthemods#121]
Issue Description: when crafting blank soul shards the diamond is not consumed. Also placing a shard into a spawner does not remove it from inventory so you can place a shard then remove it to make a copy.

Community sponge based server
Version of All the Mods:1.11

Added mods (Optifine, Fastcraft, etc.):

1.optifine
2.better fps
3.
...

**Comment by DnTheMn** [comment]
i have passed this onto the soul shard guys (https://github.com/SgtPunishment/Soul-Shards-The-Old-Ways/issues/52)

**Comment by DnTheMn** [comment]
"1. Wrong repository." (this was my bad Dan~)
"2. Attempt reproduction without Sponge. I do nothing weird." (you could try this)
