### ISSUE TITLE
Ender IO exp use

### ISSUE THREAD

**Issue by Beefjerkyy** [whatthedrunk/allthemods#122]
Issue Description: Tooltips and descriptions show the wrong amount of levels needed for anything in Ender IO. Darksteel armor, powered spawners, soul binders. This is particularly difficult for soul binders because even if you have the correct amount the machine will only take what it displays

Example soul vial to change broken spawner type says you need 6 levels and will only take 6 levels. It needs 10 or 15 levels before the process starts. You have to dump exp into a tank and pump it into the soul binder to get around this. Anvils are less troublesome at this time(darksteel armor upgrades etc)

Community sponge based server
Version of All the Mods:1.11

betterfps, optifine installed.

**Comment by DnTheMn** [comment]
if you could get me the version of forge your using i think it should be 2065 im just confirming?

**Comment by DnTheMn** [comment]
i think that spong is messing with your modded server I havn't seen any other issues about this. I know it works on most servers not saying 100% that sponge is the cause but 99% probably
