### ISSUE TITLE
Broken spawners not dropping

### ISSUE THREAD

**Issue by Beefjerkyy** [whatthedrunk/allthemods#123]
Issue Description: When breaking a spawner as a player it only drops the broken spawner shards and not the broken spawner from EnderIO. If you use a block breaker from random things it will drop both items

Community sponge based server
Version of All the Mods:1.11

betterfps, optifine installed.

**Comment by Carrots4U** [comment]
Mind telling me what mod the broken spawner shards are from as I can't check at the moment? :)

**Comment by radiocrack** [comment]
Actually its actually additions has spawner shards

I just tried this with 13C and it dropped both.

Did it fix itself or config change?

**Comment by DnTheMn** [comment]
its fixed then? great!

**Comment by acidjazz** [comment]
on v37 I actually got just the shards, even trying this w/ silk touch, no possible way I was able to get a broken spawner
