### ISSUE TITLE
Skeletal horse spawn rates

### ISSUE THREAD

**Issue by Beefjerkyy** [whatthedrunk/allthemods#124]
Issue Description:There are an excessive amount of skeletal horses that spawn. Every horse spawns as skeletal and the majority are the trap ones. Also it seems since the update that the horses will also shoot arrows out of their bodies at the player when they are not the trap horses.

Community sponge based server
Version of All the Mods:1.11

betterfps, optifine installed.

**Comment by whatthedrunk** [comment]
Are you using the configs that come with the pack? Might also want to update because I remember this being an issue a month or so ago but not anymore. Thanks!
