### ISSUE TITLE
abyssalcraft dims crash server on startup

### ISSUE THREAD

**Issue by Beefjerkyy** [whatthedrunk/allthemods#125]
Issue Description: I don't have the exact details but it seems abyssalcraft dims crash the server on startup. If the dims are first deleted the server will start.

Community sponge based server
Version of All the Mods:1.11

betterfps, optifine installed.

**Comment by Carrots4U** [comment]
We need a crashlog in order to help fix the problem :smile:

**Comment by Beefjerkyy** [comment]
Ill see what I can do as I have zero access to the server myself and just playtest.

**Comment by whatthedrunk** [comment]
Reopen if you get a crash log or something for us to look at. Thanks!
