### ISSUE TITLE
1.11 crash when breaking Botania Endoflame

### ISSUE THREAD

**Issue by Hazmatik** [whatthedrunk/allthemods#127]
Issue Description: Broke Endoflame and client crashed

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: When an Endoflame is broke in world the client crashes.

What you expected to happen: Endoflame breaks and drops as normal

Steps to reproduce:

1. Place Endoflame
2. Break Endoflame
3. 
...

Version of All the Mods: 1.11

Added mods (Optifine, Fastcraft, etc.):

1. Optifine
2.
3.
...

A copy of the crash report can be seen here: http://pastebin.com/aBy8BUdQ

**Comment by whatthedrunk** [comment]
Can you try updating your java and giving me a new crash report? Version 8_25 causes many issues with people. I will try looking at mine later but 13b has a new version of botania and new version of Forge already.

**Comment by Hazmatik** [comment]
Ah, yeah i will try updating my Java version. I am waiting to update pack versions until the server I play on updates so hopefully this won't be an issue after that.

**Comment by Hazmatik** [comment]
Tried to update Java and it wouldn't let me got a message about unable to validate the security integrity. The strange thing is when I check which version I have in the Java control panel it says I have 1.8.0_102-b14 yet the MC crash reports say I'm using 1.8.0_25. The server I play on just updated to version 13b of ATM so I'll see if I still get the crash now after updating.

**Comment by Hazmatik** [comment]
Yeah the crash doesn't happen on version 13b so closing issue.
