### ISSUE TITLE
Where can I see a changelog for the last few versions?

### ISSUE THREAD

**Issue by pmlaterza** [whatthedrunk/allthemods#129]
The title says it all...

**Comment by Hazmatik** [comment]
in the curse launcher you can click on the pack itself not the "play" button and then at the top there is a "versions" button it will open up a window with a drop down menu to select versions when you select the version it will show you the changelog for that version

**Comment by jmcaffee** [comment]
If you go to [curseforge](https://minecraft.curseforge.com/projects/all-the-mods/files) and follow the individual version links, you will see a changelog.

**Comment by pmlaterza** [comment]
Thanks @Hazmatik and @jmcaffee
