### ISSUE TITLE
Quark Realistic terrain doesn't work

### ISSUE THREAD

**Issue by Fortanono** [whatthedrunk/allthemods#13]
Feel like this may be a compatibility issue with BoP, but not sure. All I know is that it freezes and eventually crashes when I select the Realistic terrain from Quark.

**Comment by whatthedrunk** [comment]
Do you have a crash report I can look at?

**Comment by Fortanono** [comment]
Not right now, can get it but am currently testing it without BoP to see if it's an issue with that. Afterwards, or if it still doesn't work, I will get the info for you.

**Comment by Fortanono** [comment]
Worked without BoP, so that says something. Now testing my old world with and then I'll get you the report.

**Comment by Fortanono** [comment]
Well, it seems to work now. Odd.
