### ISSUE TITLE
[Request] Infernal Mobs config changes

### ISSUE THREAD

**Issue by Chaogomu** [whatthedrunk/allthemods#130]
Please disable the Ninja ability.

All it does is teleport mobs into the wall or floor, and when paired with regen it lets them take damage every second for hours.

Also I'd request the blacklisting Dragons and Withers, They do not need to be infernal, Regen on either makes them functionally immortal.

**Comment by DnTheMn** [comment]
withers and dragons should are already blacklisted so to speak and i just had a look that config may have been changes in an update there was an option to make bosses not infernal which appears to have gone poof

**Comment by whatthedrunk** [comment]
I generated new configs and disabled Ninja because of a few complaints.
