### ISSUE TITLE
mekanism and actuallyadditions interaction crash

### ISSUE THREAD

**Issue by dodgythoughts** [whatthedrunk/allthemods#131]
Issue Description: using universal cable, connecting to Laser Relay, causes server to crash, any time this chunk loads the server crashes.

What happens: Ticking block entity

What you expected to happen: provide power.

Steps to reproduce:

1.connect universal power cable to laser relay.

Version of All the Mods:13c

Added mods (Optifine, Fastcraft, etc.): none

crash report.
http://pastebin.com/m2tH74iU

**Comment by DnTheMn** [comment]
i will forward this to the mekanism git hub for you if you have not done so ill let you know the results if you would like?

**Comment by dodgythoughts** [comment]
That would be great thanks :)

**Comment by DnTheMn** [comment]
i have now liked it to both the mekanism and actually additions githubs the links are here for you as well as me 
(https://github.com/Ellpeck/ActuallyAdditions/issues/217)(https://github.com/aidancbrady/Mekanism/issues/3683)

**Comment by DnTheMn** [comment]
this issue is fixed we just need an update to the pack it incoming
