### ISSUE TITLE
No tombstone after death.

### ISSUE THREAD

**Issue by zyxep** [whatthedrunk/allthemods#133]
Hi,

I am curious about the tombstone.
I found a pirate ship somewhere on my server and i was fighting 2 skeletons (pirates).
One with sword and one with bow.

I got killed a split second after i killed the skeleton with the sword, a death mark was made in journeyMap but i couldn't find any body.

I looked around, from top to bottom, I thought it could have been because i maybe died on a slab or something but nope it was a full block.

Any idea what this could be?

**Comment by DnTheMn** [comment]
as far as i know the graves find a spot where they can spawn they wont overwrite blocks so look around

**Comment by whatthedrunk** [comment]
if for some reason you cant find the grave anywhere use the command to get your grave back.

/tmg_restore [player] <timestamp>
