### ISSUE TITLE
[1.10 v.13] Crash to desktop while filling drawer controller with chest using enderio conduits

### ISSUE THREAD

**Issue by DietmarKrause** [whatthedrunk/allthemods#134]
Issue Description: build up a storage drawer with 4 Chests (32 stacks) and a controller. A chest  and item conduits from enderio. I think it was a birch chest (not a normal chest). Crash to desktop after filling stones inside the chest. World corrupt after that. Hat to restore a backup. SP survival. http://pastebin.com/eJy9iqpS

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:
crash to desktop
What you expected to happen:
filling the stones inside the drawer
Steps to reproduce:

1.build up 4 drawers 32 stack each (storage drawers mod) and a controller
2.but birch chest beneath it and connect with item conuits from enderio
3. configure item conduits 
4. fill stones into the chest
5. crash to desktop with corrupt world after that...

Version of All the Mods:
1.13c

Added mods (Optifine, Fastcraft, etc.):
nothing
1.
2.
3.
...

**Comment by DietmarKrause** [comment]
issue also reorted to the mod builder: https://github.com/jaquadro/StorageDrawers/issues/332

**Comment by DietmarKrause** [comment]
is a known bug as i see now.  fixed in the version 3.2.6 https://minecraft.curseforge.com/projects/storage-drawers/files/2325151 .  (in the pack is the version 3.2.5). would you please update the pack? :)

**Comment by DietmarKrause** [comment]
solved with new version 1.14 which contains storage drawers 3.2.6. /closed

**Comment by whatthedrunk** [comment]
Awesome thanks
