### ISSUE TITLE
recepie in any enderIO block make the game crash

### ISSUE THREAD

**Issue by haruza** [whatthedrunk/allthemods#136]
Issue Description:

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:

waila recepies crashes the game 

What you expected to happen:
recepi
Steps to reproduce:

1.login to the server
2. try viewing recepie in any enderIO block
3.
...

Version of All the Mods:

Newest Server files

**Comment by whatthedrunk** [comment]
Please give me a crash log and we can reopen this. I am able to see Ender IO Recipes just fine. Cope and paste it into this site, thanks! http://pastebin.com/
