### ISSUE TITLE
[1.10.2 v. 1.14] Crash when Optifine is added.

### ISSUE THREAD

**Issue by pmlaterza** [whatthedrunk/allthemods#138]
### Issue Description
When Optifine is added, the game crashes when booting up.
I am running OS X 10.11 and Java 1.8.0_102.
[Here](http://paste.ee/p/bFgWY) is my crash log.

### What happens
The game crashes. It does not make it to the title screen.

### What you expected to happen
For the game to successfully load up to the title screen. I tested with and without Aroma's Dimensional Worlds mod and the game loads successfully with it but only if optifine is not installed. Therefore the issue is isolated to Optifine.

### Steps to reproduce
1. Add Optifine
2. Add Aroma's Dimensional World mod (Although this crash still occurs without it)
3. Launch game
4. Crashes before reaching Main Menu

### Mods added
1. Optifine [version 1.10.2 HD U C2]
2. Aroma's Dimensional World mod [version 1.2.0.1]

### Version of All the Mods
1.14

**Comment by whatthedrunk** [comment]
Neither of those are supported by the pack but I would remove Optifine from the server and only load it locally. Also there is not really a need for the mining dim because RFTools Dims are in the pack. Hopefully it works out!

**Comment by pmlaterza** [comment]
Thanks for the info on the RFTools Dims, I didn't know that was a feature! As for Optifine, I am not running a server, this was all done locally.

**Comment by pmlaterza** [comment]
### Update: I solved the issue

After much trial and error, I was able to solve the issue by editing `/config/splash.properties` such that `enabled=true` is changed to `enabled=false`

In other words: [this](https://gist.githubusercontent.com/pmlaterza/8c365340089120f4bef7d6ae975ef9fc/raw/3346ad8ea80965694e6fa745fabacb8ebcdb7098/splash.properties) is what `splash.properties` should look like.
