### ISSUE TITLE
[1.10.2] Move to 1.10.2

### ISSUE THREAD

**Issue by whatthedrunk** [whatthedrunk/allthemods#14]
- [x] AbyssalCraft by Shinoow
- [x] Actually Additions by Ellpeck
- [x] Advanced Generators by bdew
- [x] AppleCore by squeek502
- [x] ArmorPlus by sokratis12GR
- [x] Aroma1997Core by Aroma1997
- [x] AromaBackup by Aroma1997
- [x] AutoPackager by smbarbour
- [x] Bagginses by lorddusk
- [x] Baubles by azanor
- [x] BdLib by bdew
- [x] BetterFps by Guichaguri
- [x] Biomes O' Plenty by Glitchfiend
- [x] Blood Magic by WayofTime
- [x] Bloodmoon by lumien231
- [x] Botania Unofficial by williewillus
- [x] Chameleon by jaquadro
- [x] Chisel by tterrag1098
- [x] Chisels & Bits by AlgorithmX2
- [x] Cooking for Blockheads by Blay09
- [x] Correlated Potentialistics by Aesen
- [x] Custom Main Menu by lumien231
- [x] Dark Utilities by darkh4x
- [x] Deep Resonance by McJty
- [x] ElecCore | Rendering Library by Elec332
- [x] Ender IO by CrazyPants_MC
- [x] EnderBags by Gigabit1011
- [x] EnderCore by tterrag1098
- [x] EnderTanks by ShetiPhian
- [x] Enderthing by gigaherz
- [x] Environmental Tech by ValkyrieofNight
- [x] Experience Rings by MrComputerGhost
- [x] Extra Utilities by RWTema
- [x] Fast Leaf Decay by lumien231
- [x] Flat Colored Blocks by AlgorithmX2
- [x] Forestry by SirSengir
- [x] Grappling Hook Mod by Yyon
- [x] Industrial Craft by sfPlayer
- [x] Iron Chests by progwml6
- [x] Item Scroller by masa_
- [x] Just Enough Items JEI by mezz
- [x] Just Enough Resources JER by Way2muchnoise
- [x] Mantle by mDiyo
- [x] McJtyLib by McJty
- [x] More Overlays by feldim2425
- [x] Morph-o-Tool by Vazkii
- [x] Morpheus by quetzi
- [x] Nether Metals by koxhack
- [x] NetherPortalFix by Blay09
- [x] No Mob Spawning on Trees by oldjunyi
- [x] Not Enough Wands by romelo333
- [x] OpenComputers by Kethtar
- [x] Packing Tape by gigaherz
- [x] Pam's HarvestCraft by MatrexsVigil
- [x] Platforms by ShetiPhian
- [x] Progressive Automation by VanhalMinecraft
- [x] Psi by Vazkii
- [x] Quark by Vazkii
- [x] Random Things by lumien231
- [x] Resource Loader by lumien231
- [x] RFTools by McJty
- [x] RFTools Dimensions by McJty
- [x] Roguelike Dungeons by Greymerk
- [x] Roots by elucent
- [x] ShadowMC by shadowfactsmc
- [x] ShetiPhianCore by ShetiPhian
- [x] Simpleretrogen by cpw11
- [x] Solar Village by darkh4x
- [x] Soul Shards: The Old Ways by SgtPunishment
- [x] Storage Drawers by jaquadro
- [x] Substratum by EXTER7
- [x] TESLA by darkh4x
- [x] The One Probe by McJty
- [x] Tinkers Construct by mDiyo
- [x] Tomb Many Graves by M4thG33k
- [x] ValkyrieLib by ValkyrieofNight
- [x] WeaponsPlus by sokratis12GR

**Not Important for Update**
WAILA
Easy Breeding
Block Drops
Infernal Mobs
BaublesHud 
Ender Zoo
Screenshot Uploader
ShieldHider
The Spice of Life
Sleeping Bag
SimpleHarvest 
BetterBedrockGen 
OreDictionaryConverter 
Inventory Tweaks
JourneyMap 
MmmMmmMmmMmm 

**Removing**
Baubles Stuff: Very OP & unbalanced
Ender Crop: Useless with Enderlily from Extra Utilities 2
Food Expansion: Gets around Spice of Life and almost useless with Pam's Harvestcraft
Hammerz: Useless with Tinkers' Construct Hammers
QuantumFlux: Drunk was misinformed when he added this mod & it was much more OP than we were lead to believe
Fluxed Redstone:
RebornCore: 
TechReborn: Too many conflicts with ic2 making it unplayable with both installed at the moment. Development of the I thought was halted due to comments on Reddit but now am told is just going slow.

**Comment by Harith163** [comment]
woah..... why are baubles stuff, quantumflux and hammerz being removed?

**Comment by Carrots4U** [comment]
Bauble Stuff: Very OP & unbalanced
Quantumflux: Drunk was misinformed when he added this mod & it was much more OP than we were lead to believe
Hammerz: Useless w/ Tinkers' Construct

**Comment by Harith163** [comment]
Baubles stuff: Op but can be balanced with minetweaker or what not.
Quantumflux: It is only OP if you seriously know what you are doing and it
is not exactly cheap.
Hammerz: Maybe useless, but gives much earlier game option to do the same!

**Comment by Harith163** [comment]
Also, if correlated potential istics doesn't update, atleast now consider refined storage. The crash with JEI on servers has been fixed I do believe

**Comment by whatthedrunk** [comment]
It's already been added to the Beta pack for a few days now. We will most likely have both in the pack if  it doesn't cause any issues when I start working on server files.

**Comment by whatthedrunk** [comment]
Alright we have everything migrated as of 1.10.2 v0.2 Now its just waiting on a few bugs but world migrating should be possible soon.

**Comment by TheReidMan1** [comment]
I know Fluxed Redstone is listed as being removed because it depends on RebornCore but the Solar Village solar panel only seems to work with the Fluxed Redstone wires so you will also have to remove Solar Village (Ender IO conduits do not connect to the solar panels).

**Comment by whatthedrunk** [comment]
Good to know, thanks. I will take a look at it and if I can't get anything else to work I can add it back.

**Comment by Harith163** [comment]
I believe that was because forge updated it's capability handlers or
something along those lines mid way in for 1.9.4 development. That could be
why those cables don't work.

**Comment by Janitor53** [comment]
> Ender Crop: Useless with Enderlily from Extra Utilities 2
But there is no ender lily in current version of EU2.

**Comment by Carrots4U** [comment]
Not sure what you mean Janitor53, there is an Ender Lily in the current version. Just look it up in JEI.
