### ISSUE TITLE
(v1.15) crash when you want to search for "cry" when i'm in tinkers smeltery

### ISSUE THREAD

**Issue by zyxep** [whatthedrunk/allthemods#140]
Hey guys,

When I was in my smeltery and i wanted to see if there was cryothium (or how it's spelled) that i could use as fuel it crashed when i typed "y" in "cry". 

Crash log:
http://pastebin.com/F1LBZtBN

**Comment by whatthedrunk** [comment]
Natural Pledge needs to be updated. If you are not using the mod at the moment feel free to disable it for now.

**Comment by zyxep** [comment]
On both ends?

**Comment by whatthedrunk** [comment]
Yeah remove it from both for now. I will keep this open until I have a fix out.

**Comment by zyxep** [comment]
awesome, thx.
