### ISSUE TITLE
Crash to Desktop while reading "Engineer's Manual"

### ISSUE THREAD

**Issue by KingOscar** [whatthedrunk/allthemods#141]
Issue Description: I was reading the "engineer's manual" form ImmersiveEngineering mod and my game crashed to desktop.

http://pastebin.com/AZKqe7KQ

https://paste.ee/p/2Gd2g

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: Crash to desktop

What you expected to happen: Nothing

Steps to reproduce:

1. I couldnt reproduce it

Version of All the Mods: 1.15

Added mods (Optifine, Fastcraft, etc.):

1. Optifine
2. Veinminer

**Comment by DnTheMn** [comment]
it could be an issue with optfine rendering funny ill keep a look out for it

**Comment by DietmarKrause** [comment]
Notice: I can read it without crash and dont have Optifine. Try dactivating optifine, perhaps it works

**Comment by DnTheMn** [comment]
i can also read it fine without optfine. so it looks like that is most likely the cause

**Comment by KingOscar** [comment]
I can read it fine now, it was a one time thing. Not sure what triggered it.

**Comment by whatthedrunk** [comment]
Thank's for letting us know its fine now!
