### ISSUE TITLE
FTB Utilities - "My Server Config" button drops connection with "A fatal error has occured, this connection is terminated"

### ISSUE THREAD

**Issue by nan0bug00** [whatthedrunk/allthemods#142]
Issue Description:  Clicking on "My Server Config" button drops the connection with "A fatal error has occured, this connection is terminated"

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:  

Clicking "My Server Config" button drops connection with "A fatal error has occurred, this connection is terminated" (see hastebin at bottom)

What you expected to happen:  
1. Expected "My Server Settings" button to open some kind of configuration menu instead of throwing a critical exception

Steps to reproduce:   
1.  Create an All The Mods 1.15 server. Go into the server console and op yourself. 
2.  Join server with ATM 1.15 client.  Click on the "My Server Config" button in the FTB Utilities menu and get disconnected from the server with a fatal error.

Version of All the Mods: 1.15

Added mods (Optifine, Fastcraft, etc.):  Optifine, but I tested it without optifine and the error persists.

Error Log:  http://www.hastebin.com/jicogonaxa.avrasm

**Comment by DietmarKrause** [comment]
happens to me too in Single player. Should not crash though. I expected to select some chunks to keep them chunkloaded but this cannot be done.  Seems to be a problem of config

**Comment by nan0bug00** [comment]
Just a heads up to anyone who sees this, until this bug is fixed, you can adjust server settings with 

/ftb edit_config

type that in and then use tab autocompletion to see and adjust the options.

**Comment by Carrots4U** [comment]
Thank you for the report, we'll look into it!

**Comment by DnTheMn** [comment]
fixed in 1.42
