### ISSUE TITLE
immersive engineering Floodlight server crash

### ISSUE THREAD

**Issue by dodgythoughts** [whatthedrunk/allthemods#143]
Issue Description: Server crashes when immersive engineering Floodlight is placed.
restarting server, and logging backin causes crash again. had to use nbtexplorer to remove it.

http://pastebin.com/8K1nQTNE

What happens: server crashes

What you expected to happen: light up area.

Steps to reproduce:

1.place flood light on ground.
2.
3.
...

Version of All the Mods: 1.14

Added mods (Optifine, Fastcraft, etc.):

1.TickProfiler{1.10.2.jenkins.2} [TickProfiler] (TickProfiler-1.10.2.jenkins.2.jar) 
2.
3.
...

**Comment by DnTheMn** [comment]
blu is working on it i would suggest avoiding it as the code isnt complete at this time

**Comment by DnTheMn** [comment]
this issue has been resolved
