### ISSUE TITLE
Spawner NOT harvestable!

### ISSUE THREAD

**Issue by papa3boyz** [whatthedrunk/allthemods#144]
Issue Description:

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: All spawner now cannot be break using Enderio dark pickaxe.

What you expected to happen:

Steps to reproduce:

1.
2.
3.
...

Version of All the Mods: V1.16

Added mods (Optifine, Fastcraft, etc.):
1. Optifine
   2.
   3.
   ...

**Comment by Caleb-Ardern** [comment]
I take it that the steps to reproduce are as follows
1. get ender io dark pick 
2. attempt to break spawner

**Comment by papa3boyz** [comment]
TQ for the replied, as above mention
**What happens:** ### All spawner now cannot be break using Enderio dark pickaxe.

My EnderIO Dark Pickage top notch upgrade...

https://s16.postimg.org/blqu85c9x/2016_08_29_22_26_46.png
https://s22.postimg.org/8jg5or335/2016_08_29_22_27_04.png


...same as v1.17.

**Comment by DnTheMn** [comment]
i believe this is a sponge issus
