### ISSUE TITLE
Advanced generator Gas Intake Valve not present

### ISSUE THREAD

**Issue by 9arriflex9** [whatthedrunk/allthemods#145]
Issue Description:

Advanced generator Gas Intake Valve (Requires Mekanism 8.x) block is not available.

What happens:

I built a Advanced Generator but there is no way for me to connect Mekanism to it

What you expected to happen:

Being able to build the Gas Intake Valve (Requires Mekanism 8.x) from advanced generator

Steps to reproduce:

1. Check NEI

Version of All the Mods:

1.10.2 v1.116

Added mods (Optifine, Fastcraft, etc.):

None

**Comment by DnTheMn** [comment]
https://www.reddit.com/r/allthemods/comments/4ynwnh/mekanism_gas_outputs_not_working/

**Comment by 9arriflex9** [comment]
Hello,

I tried that already the mekanism Pressurized Tube won't even connect to the fluid intake.

[ScreenShot](http://i.imgur.com/t5k7Hbn.jpg)

**Comment by DnTheMn** [comment]
you need to use the configurator

**Comment by 9arriflex9** [comment]
it's not po ssible to use the configurator when the tube won't connect.

[Here is a Video of it](https://vid.me/Y2PN)

**Comment by 9arriflex9** [comment]
bdew (creator of advanced generator) said this 

Will be (re-)added in next update. For now you can use fuels from mekanism by converting them to liquids, either using the machine in mekanism (sorry, i don't remember what's it called) or by using Pressure Pipes.

[here](https://minecraft.curseforge.com/projects/advanced-generators?comment=87)
