### ISSUE TITLE
[1.10.2 v1.15] Crash to Desktop from Charset redstone cable

### ISSUE THREAD

**Issue by jmcaffee** [whatthedrunk/allthemods#146]
Issue Description:
Received NPE: Ticking block entity error

```
java.lang.NullPointerException: Ticking block entity
	at pl.asie.charset.wires.logic.PartWireSignalBase.logicUpdate(PartWireSignalBase.java:75)
	at pl.asie.charset.lib.wires.PartWire.func_73660_a(PartWire.java:441)

```

There's an existing ticket on the [charset repo (#11)](https://github.com/Vazkii/Charset/issues/11) related to this. I've linked a pastebin of my crash report to that ticket.

To fix the error and successfully reload the world, I used mcedit to delete the Tile Entity at the location specified in the crash report. Tile Entity was a piece of Redstone Cable.

**Comment by Carrots4U** [comment]
It is fixed in the latest version already, thank you for reporting it however!
