### ISSUE TITLE
[1.10 v. 1.16b] Crash to Dektop after loading world right after update

### ISSUE THREAD

**Issue by DietmarKrause** [whatthedrunk/allthemods#147]
Issue Description:
Crash to Dektop while loading world right after Update: http://pastebin.com/pH5acb4h

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:
Crash to Dektop
What you expected to happen:

Steps to reproduce:

1.Update to 1.1.6b 
2.Load former good World (in Alpha from same day everything was fine)
3.Crash to Dektop
...

Version of All the Mods:

Added mods (Optifine, Fastcraft, etc.):
1. nothing added
   2.
   3.
   ...

**Comment by DietmarKrause** [comment]
could not reproduce with second try but got CDT after returning from Nether http://pastebin.com/7mtDQt2u BOP...

**Comment by autumnfire** [comment]
I get this same crash if I'm able to connect to my server successfully on the first try (normally I just get disconnected and have to reconnect). Right before this happens, all I can see is the void although my coordinates never change. Only mod I've added is Optifine. http://pastebin.com/G8BeSjzv
