### ISSUE TITLE
v. 1.17 Crash on forge loading screen

### ISSUE THREAD

**Issue by KingOscar** [whatthedrunk/allthemods#149]
Issue Description: It crashed around model loading screen of forge.

https://paste.ee/p/om5Gy

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: Crash

What you expected to happen:

Steps to reproduce:

1. Launch v.1.17 with optifine C3 installed (8/25/2016). 4G of ram allocated.

Version of All the Mods: 1.17

Added mods (Optifine, Fastcraft, etc.):

1. Optifine

**Comment by axisonegaming** [comment]
I've had no issue getting it running with Optifine C2, maybe try downgrading to that version.

**Comment by autumnfire** [comment]
You're out of memory. Change your Minecraft settings in Curse to give it 5G of RAM.

**Comment by KingOscar** [comment]
It did work with 4.5 gb and optifine c2 but game itself was unplayable. Memory was getting up to 85% and resetting back to 65% really fast, every time it hit 85 i was getting a major lag spike.

**Comment by Carrots4U** [comment]
Make sure you are adjusting your memory using the curse launcher if you are using it through that. Also try anything on here https://docs.google.com/document/d/1cQeLi9x3vN5VKDkAvM3PimoAHipAWGObv4S71m9s5pc/edit
Especially the updated java part, as I see you are still using v25

**Comment by kaimokene** [comment]
I have the exact same problem.

**Comment by KingOscar** [comment]
I managed to get it run with 4gb but it took 6 mins overall and looked like it was stuck at 39/58 but it launched after 4 mins(in that 39/58 step). Those extra arguments in the google doc lagged my game removing them and doing all the other steps fixed it. Still, you need 5gb or more to run it smoothly, with 4gb i get occasional stutters.
