### ISSUE TITLE
[1.10] Reliquary Config Proposal

### ISSUE THREAD

**Issue by ZiggyAdventures** [whatthedrunk/allthemods#15]
I'll let you decide the mob drop issue.

1st Config - Hard mode recipes, Alkestry Tome disabled and no longer in JEI, Mob drops ON.
http://pastebin.com/jZvZWeBe
Mob drops would allow new players to easier craft the early items, while needing specific mob farms for end game items. However, would increase the large amount of mob drops we have already.

2nd Config - Hard mode recipes, Alkestry Tome disabled and no longer in JEI, Mob drops OFF, Crafting of drops ON.
http://pastebin.com/Qkn7wMDs
Crafting drops would gate away beginning items due to heavy iron and/or gold requirements, but make it easier to craft end game items with just throwing iron and/or gold at it.

**Comment by whatthedrunk** [comment]
Option 1 it is. I added the configs to the update but I don't have to mod in until we fix the crash with JEI recipes.

**Comment by Carrots4U** [comment]
Mod added & configs changed in the update.
