### ISSUE TITLE
Graphics freeze but game keeps going

### ISSUE THREAD

**Issue by krasnyineko** [whatthedrunk/allthemods#150]
Issue Description:
At times(seems to be randomly) the game screen freezes but I am still able to hear my self moving, and the things around me. Other players report they can see me moving in the game. It is just my client screen that does not update. I have found no way to get the screen to unfreeze other than restarting the game. This has happened since 1.16b, and still happening on 1.17. 

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

Steps to reproduce:
Seems to happen on a whim. Have not noticed any pattern

Version of All the Mods:
Latest 1.17 all the mods no extras

Added mods (Optifine, Fastcraft, etc.):
I did try adding optifine to see if that helped. It only made the intermittent freezing worse from what I saw and still experienced the screen freezing. I have since removed it. 

![2016-08-27_04 31 48](https://cloud.githubusercontent.com/assets/10760764/18026524/4640a07a-6c0f-11e6-9956-225ffdb09b35.png)

If this seems to be unrelated to the pack I am sorry. Have not had the issue on other mod packs.

**Comment by Carrots4U** [comment]
Hmmm very odd. Next time it happens try pressing F3 + R to see if it unfreezes you.

**Comment by krasnyineko** [comment]
Unable to fix it really on my laptop, but it works fine on my desktop. Closing due to lack of information in the cause of the issue.
