### ISSUE TITLE
Crash just while idling, maybe tinkers at fault

### ISSUE THREAD

**Issue by Ricket** [whatthedrunk/allthemods#151]
Was just idling on our island (tinker smeltery and stations, some chests, a few mekanism machines, a mango tree). Froze and crashed.

All the Mods 1.17

Added only Optifine.

http://pastebin.com/yjCbFkJS

**Comment by Carrots4U** [comment]
I can't seem to reproduce this. Might have just been a onetime thing. If it happens again please reopen this otherwise I can't do much :/
