### ISSUE TITLE
IC2 causes server crash java.lang.NullPointerException: Exception in server tick loop

### ISSUE THREAD

**Issue by dodgythoughts** [whatthedrunk/allthemods#152]
Issue Description:since updating to v1.17 we have had random crashes of the server. all with the same error.

crash log
http://pastebin.com/xR3AQ46Q

found this, seems its been an issue for a while
http://bt.industrial-craft.net/view.php?id=1969
https://gist.github.com/anonymous/680ecb301e66be6b0f9d5f283a38eb7c

What happens: tps on server suddenly drops, then the server crashes.

What you expected to happen: it not to crash.

Steps to reproduce:

1.leave server running. 
2.
3.
...

Version of All the Mods: All.

Added mods (Optifine, Fastcraft, etc.):

1.tickprofiler.
2.
3.
...

**Comment by axisonegaming** [comment]
I believe I'm having the same issue: http://pastebin.com/c6xFNHd4

**Comment by axisonegaming** [comment]
Not sure if this helps, but this thread references the issue and says updating to the latest versions of IC2 and Mekanism fix it: http://bt.industrial-craft.net/view.php?id=1943

**Comment by dodgythoughts** [comment]
Just updated to v18b and the issue is still present.
[crash-2016-08-31_14.25.43-server.txt](https://github.com/whatthedrunk/allthemods/files/446293/crash-2016-08-31_14.25.43-server.txt)

**Comment by Carrots4U** [comment]
Can you try in v1.9 and see if it is still broken? Thanks!

**Comment by nan0bug00** [comment]
I tried it in v1.19, still broken.  Removing it (and Compact Solars) from the pack solves everything.

**Comment by dodgythoughts** [comment]
I can confirm it does the same for me in v1.19

the issue happens, when you leave certain areas, and the chunk unloads.
nobody has ever used IC2 on the server.
I've tried chunk loading (with different types of chunk loaders) but it makes no difference.

i can reliably crash the server every time by flying through past one of our more heavy users base. he uses alot of mekanism machines etc.

if needed, i can give you a copy of the world, but its around 2gb.

**Comment by ProsperCraft** [comment]
http://pastebin.com/kJxpAxW4

This is still an issue on .27  Please remove it from the pack it causes client crashes as well.

The server has crashed 5 times in the last two days from this issue.

**Comment by dodgythoughts** [comment]
For me its a specific area in the world.(someone's base) and its when you
leave that area that it crashes. Chunk loading the area does not fix it.

If I was to delete that chunk it would fix it I believe, it seems to be a
legacy issue from an earlier version of the pack.

**Comment by ProsperCraft** [comment]
Server crashed 24 times this morning due to this bug!!

It happens whenever a player logs in instantly...there is no time to do anything when he logs in, he doesn't even get in to the game before it crashes.

**Comment by ProsperCraft** [comment]
https://gyazo.com/d41361d8592acbcbf0cd46c578d8f250

When disabling IC2, compact solars, and the coremod we get this when trying to log in.

**Comment by ProsperCraft** [comment]
ok, now I am at a loss, when re-enabling the mods and restoring the world from pre-disabled state we still get this error.

**Comment by skipgamer** [comment]
Is crashing on first tick (I'm pretty sure someones been using IC2 near spawn) with Sponge for me. Fine on Forge. only been running since 1.25 re: legacy issue.
http://pastebin.com/rqRVqT2V

**Comment by ProsperCraft** [comment]
This happens with just forge as well, we were getting it before adding sponge.

http://bt.industrial-craft.net/view.php?id=1969

**Comment by skipgamer** [comment]
yep, happening without sponge too (it must have just been preloading) player getting CTD when he tries to log in, I TP'd to his last location and server crashed throwing the same ic2.core.energy.leg.EnergyNetLocalLeg.emitEnergyFrom(EnergyNetLocalLeg.java:341)

**Comment by ProsperCraft** [comment]
This is absolutely the highest priority item because it's having a huge impact on playability of the pack.

**Comment by Tander** [comment]
Same issue in my pack ( https://minecraft.curseforge.com/projects/elittle-net-extended ), with only one of my player. When he removed all things that he craft from the world - no more crashes! And he use nothing from ic2, so maybe it's cross-mod issue?

**Comment by nightred** [comment]
Happened on pack version 1.29

**Comment by skipgamer** [comment]
Thank you @nightred !!! I was literally about to move my server back to a 1.7 pack after quite literally tearing down machine after machine in MCEdit with no joy.

**Comment by ProsperCraft** [comment]
+1 vote to make that the default config option @whatthedrunk

**Comment by whatthedrunk** [comment]
I have no problems changing this in 1.31 as most people who use Mekanism probably won't care. I can maybe push an update in a few hours.

**Comment by axisonegaming** [comment]
@whatthedrunk Note that this didn't fix the crashes for us. We set that to true to try and crashes continued to happen.

**Comment by Chocohead** [comment]
Try using http://jenkins.ic2.player.to/job/IC2_110/82, it will now log the broken tile and it's position rather than crash. Depending on if it's constantly being given power it might cause the logs to become quite big over time, so use with caution.

**Comment by ProsperCraft** [comment]
@whatthedrunk An IC2 dev is asking we use a new version that now should have a fix for the crashes.

http://bt.industrial-craft.net/view.php?id=1969

**Comment by whatthedrunk** [comment]
Did you guys remove permission to use Jenkins builds in packs? I tried using one the other day and it got rejected. I've been trying to use them until the bug gets fixed. 

> "The following mods are not on the Third Party List or are a file that the author has chosen not to upload to CurseForge, if the author provides permissions to redistribute them for modpacks please follow the instructions at https://goo.gl/x0Im2l to have them added: 
> [mods] industrialcraft-2-2.6.71-ex110.jar"

@ZeldoKavira never got back to me.

**Comment by Chocohead** [comment]
It should still be allowed, and we are on the 3rd party list purely to allow Jenkins builds that aren't on Curse to be used.

**Comment by whatthedrunk** [comment]
I can't test it myself because I don't have the crash but I will push an update in a couple hours so hopefully others can verify that its working. Thanks.

**Comment by dodgythoughts** [comment]
I can confirm after update my crashing is resolved.

All this time I've been blaming ic2 and mek but the error in console is this

[21:46:10] [Server thread/INFO] [IC2.EnergyNet]: No tile found for sonar.calculator.mod.common.tileentity.generators.TileEntityConductorMast@3c750e9a at dim 0: -312/63/-298.

**Comment by rupnerd** [comment]
i upgraded our server to 1.32 and it does not crash at startup anymore. 
it just constantly spams 
[IC2.EnergyNet]: No tile found for sonar.calculator.mod.common.tileentity.generators.TileEntityConductorMast@1c1f2490 at dim 0: -491/81/592
with an equal entry for every Conductor mast there is, just the coords are different and the hex code. I tried to remove the masts, but that increased the frequency of the messages... if the area with the masts is chunkloaded no message is displayed, if it's not loaded its spaming the messages every 30 sec until the server freezes after 4h. if you are in the vicinity your client also crashes with this error report http://pastebin.com/jZAz8HP0 what i also noticed the few moments i can stay on that chests and the masts render half transparent

**Comment by ProsperCraft** [comment]
This can be closed as the server is no longer crashing after the updates.

**Comment by whatthedrunk** [comment]
Thank's for letting me know, glad its working out finally.
