### ISSUE TITLE
Unknown travelling crash 

### ISSUE THREAD

**Issue by Caleb-Ardern** [whatthedrunk/allthemods#154]
Issue Description:
crash report 

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: 
1. server crashes 
2. client bugs out 
3. got caught in a portal and sufficoted to death

What you expected to happen:
To be able to play without crashing
Steps to reproduce:(similar)

1.  Travel through portal at pepper-jacks, Dan's and Bookrages's place
(this probably has something to do with chunk loading, teams and FTB utility's)

Version of All the Mods:
v1.17
Added mods (Optifine, Fastcraft, etc.):
N/A

Game output
http://pastebin.com/MhETFzug

**Comment by DietmarKrause** [comment]
The crash happens while going through the portal to the nether? Or coming back? The crash seems to happen with some"Fluid container" What could that be? A container in the inventory of the player going through the portal? Something in the World?

**Comment by DnTheMn** [comment]
i believe it has been resolved if not please reopen this issue
