### ISSUE TITLE
Issue with Optifine on 1.17 and IC2 being included

### ISSUE THREAD

**Issue by Omega696** [whatthedrunk/allthemods#155]
Issue Description:
Optifine was working fine in version 1.13 of the pack, we updated to 1.17 and it continually crashes the pack before it can get to the main screen. Causing an Open GL error. Given the resource intensive nature of running the pack any boost is needed especially 1.17 which eats memory.
Also why was IC2 added to the Pack, the pack already has issues with terrain generation and lag from resource allocation. IC2 does nothing to the game but weight it down with redundant and outdated methods that the majority of people have discarded from the packs. I know no one that uses it willingly.

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: On loading 1.17 with optifine C1, 2, or C3 it crashes with an openGL error while trying to load the models.

What you expected to happen: It to run

Steps to reproduce:

1. Install Curse, load all the mods, and then add Optifine to the mods folder
2. run the pack
3. expect crash.
...

Version of All the Mods: 1.17

Added mods (Optifine, Fastcraft, etc.):

1. Optifine
2.
3.
...

**Comment by DnTheMn** [comment]
i have been able to use optfine c1 with the pack how much rams do you have?

**Comment by Omega696** [comment]
Yes, after some tinkering with settings I maxed out the memory to 6 gig (which it eat instantly) and its running with optifine. The memory usage is a real issue for layers on our server with older or lower power machines, where 4 gig on 1.7.10 packs worked fine, here that amount struggles to give any real fps an no texture packs or optifine.
