### ISSUE TITLE
Crossroads gears missing recipe

### ISSUE THREAD

**Issue by bejarrodar** [whatthedrunk/allthemods#157]
When I went to start playing with Crossroads I realized that the recipe for the gears is missing I believe the reason for this is your use of Substratum to consolidate items. The Crossroad gears are placed in world unlike the Substratum ones.

**Comment by Carrots4U** [comment]
I  will take a look, thanks for the report.

**Comment by Carrots4U** [comment]
Fixed in the next update, thanks for the report!
