### ISSUE TITLE
Nether and Endmetals spawn in Overworld

### ISSUE THREAD

**Issue by Yucca86** [whatthedrunk/allthemods#158]
After updating to version 1.18 of the pack, Nether and Endmetals spawn in Overworld. Even existing chunks have them retrogenned in.

**Comment by nan0bug00** [comment]
Same problem here.

[Pics](http://imgur.com/a/QVSg7)

**Comment by Yucca86** [comment]
Tried removing orespawn configs and copying the json -files to the new orespawn folder in the root of the pack, but still the ores spawn in Overworld. Tried exploring new chunks after the config altering.

**Comment by Yucca86** [comment]
Seems to be that Orespawn mod changed configs or something. I placed the 1.17 versions json -files to the new orespawn folder that generates in the root folder of the modpack. That did not work, but seems like the jsons formatted to the new style.
I then added the dimension 1 and -1 accordingly to the nether- and endmetals-bmore.json files and tested in a clean creative BOP -world and no nether or end metals.

**Comment by whatthedrunk** [comment]
I did the change and posted a new beta if anyone else can check to verify its been fixed fully.

**Comment by Yucca86** [comment]
That fixed the Overworld for me, but did not test the End or Nether though. So cannot say anything about the generation on those dimensions.

**Comment by DnTheMn** [comment]
nether metals are supposed to be in the nether and end

**Comment by Yucca86** [comment]
Yeah. But I meant like there could be Overworld or End ores in Nether for example.

**Comment by StevenB83** [comment]
This still happens on a clean 1.18b server. finding both end and nether ores in the overworld. I checked the configs and they seem fine to me (1 or -1 respectively for the end and nether ores).

**Comment by whatthedrunk** [comment]
Let me know if this is still happening with 1.18c. That ore spawn mod is being such a pain and I reverted it to an older version.

**Comment by Carrots4U** [comment]
Is this still occuring in v1.19? If not I'd like to close the issue thanks!

**Comment by Yucca86** [comment]
Just tested with a fresh world in 1.19. Cheated in a builder and quarried 3x3 chunks, No nether or end ores in sight.

**Comment by Carrots4U** [comment]
Resolved, the latest update: closing

**Comment by StevenB83** [comment]
My apologies, have been very busy with work and rl stuff.
I cannot replicate it with 1.19 :)
