### ISSUE TITLE
Stuck in bed again

### ISSUE THREAD

**Issue by Caleb-Ardern** [whatthedrunk/allthemods#159]
Issue Description:
getting stuck in bed bug is back

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: cant wake up 

What you expected to happen: to wake up and it to be day

Steps to reproduce:

1.make bed 
2.hop in bed
3.repeat 2...

Version of All the Mods: v1.18

Added mods (Optifine, Fastcraft, etc.):
N/A

probably not repeatable and rare

**Comment by Caleb-Ardern** [comment]
easy way to kick yourself /ftb my_settings
this will kick you from the server and is a known bug on the ftb utility's page

**Comment by Hazmatik** [comment]
if you are on a server the easiest way i've found to kick self from server is disconnect from wifi/network, it's a lot faster than restarting the client but yeah this bug from what i've looked into it is a vanilla bug it's happened to me on every version of ATM. Happens to me less often using the sleeping bag but still occasionally happens with it.

**Comment by DnTheMn** [comment]
this has been around for a long time its a pain were waiting on a fix
