### ISSUE TITLE
Immersive Engineering Arc Recycling Crash (Server)

### ISSUE THREAD

**Issue by axisonegaming** [whatthedrunk/allthemods#160]
**Issue Description:** Server crashes on startup after a tick takes too long during startup. Crash Report: http://pastebin.com/yRW0acn9

**What happens:** Server crashes.

**What you expected to happen:** Server does not crash.

**Steps to reproduce:**

1. Start server.
2. Crash
3. Sigh

**Version of All the Mods:** 1.17

**Added mods (Optifine, Fastcraft, etc.):**

1. No added server mods, but removed IC2 and Compact Solars

**Comment by dodgythoughts** [comment]
In server config change max tick time to -1

**Comment by axisonegaming** [comment]
This did seem to fix the issue.
