### ISSUE TITLE
No iron ore generated

### ISSUE THREAD

**Issue by Benjamin-Berry** [whatthedrunk/allthemods#162]
Issue Description:

There's no iron ore in the world.

What happens:
only gold ore mined

What you expected to happen:
Iron and gold ore mined

Steps to reproduce:

Make new standard world
Place down digital miner
set radius to 32
configure for item stack iron ore
configure for item stack gold ore
start

Version of All the Mods:
allthemods 1.10.2 v1.18b

Added mods (Optifine, Fastcraft, etc.):

1.
2.
3.
...

**Comment by TributeR** [comment]
Is this not possibly a digital miner issue? I had my digital miner disappear from the world. Try running a RFTools quarry in creative mode.

**Comment by Benjamin-Berry** [comment]
Thats just confirmation of something i noticed manually. Placing an iron ore and restarting the miner gets the placed ore.

**Comment by krasnyineko** [comment]
The same thing is happening to me. I thought it had to do with WTF-E but after updating and removing it I still cannot find and Iron Lapis, or any vanilla ores really.

**Comment by zininzinin** [comment]
Yep, same here. There are no vanilla ores. I also tried removing WTF-Expedition and the same issue persists.

**Comment by krasnyineko** [comment]
For now I have a mining dimension created for our users in case anyone wants a work around and doesn't want to regen their world.

**Comment by whatthedrunk** [comment]
If you generated the world with WTFE and them removed it then you need to go to new chucks to find vanilla ores. In the newer version of the pack the configs were changed so it would not use WTFE oregen so this won't happen to new players who want to remove it. If you don't want to reset there are many ways to get the vanilla ores such as the void miner, botania, new chunks, mining dimension & nether ores.

**Comment by Benjamin-Berry** [comment]
No were is my issue did I state anything about adding or removing mods. I also  specifically stated that it was a newly created world.

**Comment by krasnyineko** [comment]
My world and installations were also fresh on both single player/server installations.

**Comment by Benjamin-Berry** [comment]
What's the best way to get a issue reopened as a non contributer?

On Sep 1, 2016, at 11:28 AM, krasnyineko <notifications@github.com<mailto:notifications@github.com>> wrote:


My world and installations were also fresh on both single player/server installations.

-

**Comment by whatthedrunk** [comment]
Doing some more tests now, if I find the problem expect an update within the hour.

**Comment by zininzinin** [comment]
Yeah, a new world with or without WTF-E seems to have no vanilla ore generation.

**Comment by whatthedrunk** [comment]
There is a new update that should be approved any second. If someone can check out a new world(overworld, nether & end) and verify I would appreciate it.

**Comment by whatthedrunk** [comment]
Update is approved. Waiting on feedback before I close again.

**Comment by krasnyineko** [comment]
I would like to say with my minimal testing using the digital miner on a fresh install/world I was a able to find all vanilla ores. What was the problem anyway?

**Comment by whatthedrunk** [comment]
Sometimes when you update mods on curse it adds other mods and they update. There was a mod called MMD OreSpawn that I seemed to update and it changed to move the configs into a new location. In 18 I edited them to display the correct dim ID's but that seemed to not fix the problem. So I reverted to an older version of the mod and it seemed to fix it. Thank's for letting me know!

**Comment by zininzinin** [comment]
Looks like it fixed the issue, but I'm trying to retrogen as I played for quite a while with no vanilla ores. Any thoughts on this? I'll try to track it down a report my findings.
