### ISSUE TITLE
[1.10.2] Testserver No lapis generated

### ISSUE THREAD

**Issue by DietmarKrause** [whatthedrunk/allthemods#163]
Issue Description:
i havent found any Lapis in 2 mines 4 hours manually  mining on the right level. Spawning problem of Lapis? Iron ore is found. 
Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:
didnt find any lapis
What you expected to happen:
lapis in level 16 (so shoukd it be according to JEI)
Steps to reproduce:

1.
2.
3.
...

Version of All the Mods:

Added mods (Optifine, Fastcraft, etc.):

1. Nothing
2.
3.
...

**Comment by whatthedrunk** [comment]
If you are seeing Iron ore then lapis is generating fine, my guess is someone may have placed a digital miner down to collect them all. Go a few hundred blocks away and place a digital miner down and see if it sees any, if not feel free to reopen this issue and explain what version you are on and what you updated from.

**Comment by DietmarKrause** [comment]
It is not possible to build anything included digital miner, if you cannot see, that the region you are building your home base or the region you just want to mine is already looted by a digital miner. At first you have to build that thing to see, that everthing is looted already. I personally think digital miniers should be made impossible on servers, or alt least, the player using it should claim the chunks and therby telling everybody that this region is looted by him, so others are dont waistung time. It is not an issue but a question of game balance. What do you think?

**Comment by DnTheMn** [comment]
its a problem yes you just have to go far enough away

**Comment by DietmarKrause** [comment]
How can you tell this region isnt looted already ? You cannot see this. You mine and dont find anything and after hours you see: someone used a digital miner and therefor you cannot find anything. Far enough away isnt a solution. soemone was there befor you and used a digital miner...it should be blacklisted, i think (or mark the chunks with ftb as an altenative)
