### ISSUE TITLE
Cooking For Blockheads version 1.10.2-4.2.14 not working as intended. 

### ISSUE THREAD

**Issue by krasnyineko** [whatthedrunk/allthemods#164]
Issue Description:
A decent amount of recipes do not work using 1.10.2-4.2.14 of cooking for blockheads. I downgraded the mod to 1.10.2-4.2.12 from 1.17 of the mod pack and that resolved the issues.

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:
Trying to make taffy. peppermint, and others as well results in no recipe being shown on the left side and nothing being made when clicked again. 
What you expected to happen:

Steps to reproduce:

1. Get the needed tools/ingredients to make taffy, or pepper mint.
2. Attempt to see the recipe in the cooking table (nothings shows)
3. Attempt to get the treat by clicking again (nothing is made)

As stated above, it seems its the new version causing problems. Downgrading fixes the problem. This happens to a lot of recipes, I just used taffy/peppermint as they were the ones I noticed it on and are really easy to make.

**Comment by DnTheMn** [comment]
can you craft them without cooking for blockheads in a regular grid for example or is no recipe being shown at all?

**Comment by krasnyineko** [comment]
I can confirm you can craft them outside of cooking for blockheads and a recipe is shown in jei and as stated before is craft-able manually. In the cooking table when clicking on a food, it does not show how to make it in the left pane which normally shows you what you need to make it.

**Comment by DnTheMn** [comment]
can you pass it on to cooking for blockheads

**Comment by krasnyineko** [comment]
I added onto an already existing issue thread. You think there would be a patch for this or wait until there is an update for cooking for blockheads.

**Comment by DnTheMn** [comment]
ok ill keep any eye on it

**Comment by Carrots4U** [comment]
Fixed in the next version, thanks for the report!
