### ISSUE TITLE
Server update to v1.19 causes client crashes upon world load.

### ISSUE THREAD

**Issue by eriico39hi** [whatthedrunk/allthemods#165]
Issue Description:

What happens:

Friends server was updated to v1.19. (from 1.18c) When either me or him attempt to load in we get a client crash with the message java.util.ConcurrentModificationException.

Also, the brief glimpse that I got upon world load showed that some blocks were replaced.

What you expected to happen:

I expected to successfully load into the world.

Steps to reproduce:
1. Update a server and client to v1.19
2. Attempt to connect

Version of All the Mods: v1.19

Crash report: http://pastebin.com/NFiAxgAJ

**Comment by OfficialStamper** [comment]
The ConcurrentModificationException also happens on my server.  Restarting the client and retying is normally successful.  I can supply crash logs if required.   Please request if  I can be of further help.

**Comment by Carrots4U** [comment]
Yes we've had this bug for a while but it only seems to happen to certain people. Any help would be greatly appreciated.

**Comment by OfficialStamper** [comment]
OK, this may sound crazy but.......

If I click [Refresh] in the multiplayer/server list before connecting the problem doesn't happen.

However, if I leave the game/server and drop back to the multiplayer/server list screen, and then reconnect, without hitting [refresh] first, I get the crash to desktop.

latest crash report: http://pastebin.com/LcYiwBAg

**Comment by eriico39hi** [comment]
We recently solved ours by first loading the world files on a different computer with the new version. Then moving the world files back to the main server computer.

Very strange issue indeed.

**Comment by Ryuhouji** [comment]
This is still an issue in 1.30, and it still happens a lot. Still testing the theory that refreshing server list prevents it.
