### ISSUE TITLE
AbyssalCraft Biomes Disabled in Config.......Why???

### ISSUE THREAD

**Issue by OfficialStamper** [whatthedrunk/allthemods#166]
Issue Description:

Is there a reason why some of the AbyssalCraft biomes are set NOT to generate?  Without these biomes, the  Mod cannot be completed.   If these biomes are not to exist you may as well remove the mod from the pack!

The following excerpt is from the AbyssalCraft config:

    # Set true for the Darklands Highland biome to generate.
    B:"Darklands Highland"=false

    # Set true for the Darklands Mountain biome to generate.
    B:"Darklands Mountain"=false

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:

Darklands Highland, Darklands Mountain biomes do not  generate in the world.

What you expected to happen:

AbyssalCraft mod to be  configured so that it can be played to completeion.

Steps to reproduce:

1.  Examine file 'abyssalcraft.cfg'
2.
3.
...

Version of All the Mods:

1.10.2_v1.19

Added mods (Optifine, Fastcraft, etc.):

1.  (no additions)
2.
3.
...

**Comment by Carrots4U** [comment]
Thank you for reporting this, I swear we have changed this back multiple times but it likes to revert back to normal. Fixed in the next version!

**Comment by OfficialStamper** [comment]
Thanks for the quick reply, will hold off my Abyssal exploration till then. Or....... can I manually turn on the Biomes in the config now?  I'm assuming there is no issue?

Thanks, and keep up the good work, really enjoying it. :)))
