### ISSUE TITLE
Pressure Pipes mod missing from 1.19

### ISSUE THREAD

**Issue by dhawk312** [whatthedrunk/allthemods#167]
Issue Description:
Changelog states Pressure Pipes was added to v1.19. However, pressure pipes is not in the curse modpack or the server mod folder. 

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:
No pressure pipes.

What you expected to happen:
Pressure pipes to be in the modpack.

Steps to reproduce:

1. Download curse modpack or server files from the project website
2. Check the 'mods' folder for pressure pipes
3.
...

Version of All the Mods: 1.19

Added mods (Optifine, Fastcraft, etc.):

1. Optifine
2.
3.
...

**Comment by Carrots4U** [comment]
Thanks for the report, it seems to be have been missed when updating. It will be added next update!
