### ISSUE TITLE
Memory Leak in 1.19

### ISSUE THREAD

**Issue by SpectacularNumbers** [whatthedrunk/allthemods#168]
Issue Description:
There is a memory leak due to one of the mods in the pack.
Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:
Memory usage climbs extremely fast then drops back down. (starts @ 70% used, goes up to 90% fast then drops back down to 70%)
Steps to reproduce:
1. Launch the game and hit F3
   2.
   3.
   ...

Version of All the Mods:
1.19
Added mods (Optifine, Fastcraft, etc.):

1.none
2.
3.
...

**Comment by DnTheMn** [comment]
unfortunatly we know about this and it is a big problem if you have more ram you can slow it down or you could potentially change to the lite version of the pack all the configs are the same so you can carry over any mods you really want

**Comment by Carrots4U** [comment]
No dan keep this open, it's important we document any bugs so can keep in them mind when we can fix them.

**Comment by capSAR273** [comment]
I was able to fix this by removing all the Java arguments that are recommended by the Google Doc guide. Now Java will garbage collect when it needs to and not at 100% like it was for me before. I now have no problems with stuttering, the game would freeze up for a few seconds while Java collected.

**Comment by KingOscar** [comment]
This happens in the lite version aswell but since it requires less ram to run it is not as much of a problem.
