### ISSUE TITLE
Mob spawning in the nether

### ISSUE THREAD

**Issue by zyxep** [whatthedrunk/allthemods#169]
Hi,

This is just a question that annoys me a little.
Have you set ghast spawning to be really low?
I have been walking around in the nether without a single ghast to spawn.

I want to capture it to make that god damn angel wing :)

**Comment by whatthedrunk** [comment]
You are probably just having bad luck. If I was to change anything it would be making mobs spawn more not less.

**Comment by zyxep** [comment]
Thanks for the info.
