### ISSUE TITLE
v1.20b - Draconic Evolution -1.10.2-2.0.0.89 Energy Storage Cores Broken

### ISSUE THREAD

**Issue by OfficialStamper** [whatthedrunk/allthemods#170]
Issue Description:

Since update to v1.20b; DE (Draconic Evolution) storage cores lose components and stop working.

This has been reported on brandon3055/Draconic-Evolution gitHub.  

https://github.com/brandon3055/Draconic-Evolution/issues/372

Have had to restore world from backup and roll back to v1.19

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:

Update to v1.20b breaks DE Storage Cores

What you expected to happen:

Steps to reproduce:

1. Build a DE Storage Core
2. Update to v1.20b
3.
...

Version of All the Mods:  v1.20b

Added mods (Optifine, Fastcraft, etc.):

1. Optifine
2.
3.
...

**Comment by ilordnightmarei** [comment]
wrong version this one fixes it
Draconic-Evolution-1.10.2-2.0.0.89-universal.jar

**Comment by DnTheMn** [comment]
as far as i know that version is bugged and needs more work it will be updated when ready

**Comment by OfficialStamper** [comment]
Latest version of  DE fixes this.  Closed.
