### ISSUE TITLE
Extra utils 2 angel ring doesn't work

### ISSUE THREAD

**Issue by zyxep** [whatthedrunk/allthemods#171]
Hi,

I just got an angel ring but it doesn't work, i can't put it in a bauble either.
i don't any errors in the console, and allow-flight is set to true in my server.properties.

Any idea what it could be?

**Comment by whatthedrunk** [comment]
You need grid power for it to work, try watching some youtube videos on how the mod works now. It's also no longer a bauble.

**Comment by jmcaffee** [comment]
Check out Kryllyk's youtube video on the water mill which is used to generate GP for powering Extra Utils stuff (like the Angel Ring): [FTB Unstable 1.10 - Ep. 4 - Extra Utilities 2 Water Mill](https://www.youtube.com/watch?v=mZOKR3FEmeE&index=4&list=PLcrFan80a3K-4jJ6cTXry3XEiSR9Nk9q8)

**Comment by jmcaffee** [comment]
You'll also want to look into the Extra Utils chunk loader which uses GP as well.
