### ISSUE TITLE
v1.20b Crash on startup

### ISSUE THREAD

**Issue by milkman1017** [whatthedrunk/allthemods#172]
Issue Description: Launcher gets to "Model Loader: Baking" stage of startup then crashes after finishing

What happens: Launcher crashes

What you expected to happen: not to crash

Steps to reproduce:

1. Open up launcher
2. Press Play
3. Wait for it to load most of the way and then crash
...

Version of All the Mods: 1.10.2  v1.20b

Added mods (Optifine, Fastcraft, etc.):

1. none

**Comment by Carrots4U** [comment]
We need a crash report to even begin helping, post one onto pastebin and link it here :)

**Comment by milkman1017** [comment]
http://pastebin.com/x9vwitnj

Here ya go :)

**Comment by whatthedrunk** [comment]
You need to increase the amount of Ram you are using. 
[Performance Help](https://docs.google.com/document/d/1cQeLi9x3vN5VKDkAvM3PimoAHipAWGObv4S71m9s5pc)
[All the Mods Lite](https://minecraft.curseforge.com/projects/all-the-mods-lite)

**Comment by DnTheMn** [comment]
you beat me to it damn you drunk

**Comment by milkman1017** [comment]
Thank you :)
