### ISSUE TITLE
Ghasts hard to find

### ISSUE THREAD

**Issue by Hirsu** [whatthedrunk/allthemods#174]
Issue Description:

The ghast spawn rate in the nether seems to be really low. Several other users have reported the same issue, with some people spending hours to find a single ghast. Usually you get blasted with ghast fireballs and now they seem to play hide and seek.

This issue has been posted before but was closed at the time (it was credited to user bad luck). 
But with several people reporting the same issue [on reddit](https://www.reddit.com/r/allthemods/comments/519b43/ghast_spawning_issue_for_anyone/) there may be more to this.

Version of All the Mods: 1.21

Removed Mods: Infernal Mobs

Added Mods (client side only): Dynamic Surroundings Unofficial (cosmetic mod)

**Comment by nightred** [comment]
We have halved the butterfly spawn cap on our server, the town is surrounded by them.
We also have changed the blaze spawn chance from 20 to 5 to see if that helps.
Will take a few days to get real results.

**Comment by DnTheMn** [comment]
i have seen a few issues pop up in relation to ghasts spawning but drunk hasn't changed the spawn rate ill keep this open because its been reported before so i think its becoming a bigger pack wide problem

**Comment by KingOscar** [comment]
It is fine in the lite version

**Comment by TributeR** [comment]
I must agree, I had the same difficulty finding them. Throughout 1.18 and upwards.

**Comment by nightred** [comment]
This might be due to the view distance of the client in SP and on servers the server.properies view-distance setting might be to low.
I am testing the new setting view-distance=10

**Comment by SephirothWS** [comment]
I would like to add that I too am having this very issue in 1.47 currently. took me 12 hours in one playthrough to find a ghast in the nether, and I'm sitting on 3 hours searching on a smp playthrough atm and no luck thus far. Why do ghasts have to be this frustratingly rare?

**Comment by Arcanatias** [comment]
use the soul bead from quark in the nether, it increases the spawn rates of all the nether mobs.

**Comment by jezzen** [comment]
Kind of giving this a revival, but I think a large part of this may be that ghasts are forcibly despawned quickly for some reason.

Lately for my angel rings, I have been using an enclosed box with cursed earth to get them to spawn. But, as I'm trying to damage and capture it from outside the box, they suddenly disappear on me despite being only a few blocks away and only being around for a minute or so.

It has also happened to the rare naturally spawned ones as well, as they often despawn as I try hunting them down.

**Comment by BuggaNoia** [comment]
@jezzen: All mobs spawned by cursed earth despawn quickly right after they leave the cursed earth, regardless if a player is nearby. Observed this in my overworld mob farm (ATM:E 1.19)

**Comment by jezzen** [comment]
@BuggaNoia Yeah, didn't notice that little effect until a bit later. Having them escape from under my nose made me think of a few times that ghasts despawned while I was hunting them (though not as extreme, since if I could get that close it would quickly be put in a lasso) and ended up connecting the two cases.

Still pretty annoying how because they fly, they aren't safe from despawning even in the minimum 4 height enclosure. I wonder if using pistons to force them to collide with the cursed earth would negate it...
