### ISSUE TITLE
All the Mods Lite (CTD)

### ISSUE THREAD

**Issue by KingOscar** [whatthedrunk/allthemods#175]
Issue Description: All of a sudden 4 items with no texture(purple square) appeared in my inventory while i was in the nether. I crashed to desktop when i tried to put the items in my hand.

Crash Report: http://paste.ubuntu.com/23156726/

What happens: Crash to desktop

What you expected to happen: Figure out what the item with the missing texture is...

Steps to reproduce:
1. Put the item with the purple texture in your hotbar

Version of All the Mods: Lite v0.5

Added mods (Optifine, Fastcraft, etc.):
1. Optifine
2. And couple of other mods

EDIT: I got the backup save and i still had the item in my inventory. Checked the ntbexplorer and it said it was a substratum ore dust. I was getting it from vein mining netherack with an auto smelt pickaxe. Only putting it in my hand would cause me to CTD, voiding it works fine.

**Comment by DnTheMn** [comment]
is this still an issue?
