### ISSUE TITLE
Modpack totaly incomplete on curse

### ISSUE THREAD

**Issue by chaos234** [whatthedrunk/allthemods#177]
Hey,

I downloaded your mod but all what was in there, from the mod list, are Mekanism and ArchitectureCraft.
I dunno why but I can't play this MP without all the other mods.

Please provide at every time a full MP Download so that I can use it and setup a server, thanks.

**Comment by DnTheMn** [comment]
what version of the pack normal or lite also what version are you using? (ie 1.22)

**Comment by chaos234** [comment]
I used the following link: https://minecraft.curseforge.com/projects/all-the-mods/files/2329234 and then downloaded the file which is shown there (not the server files zip because normaly all mods on the client are equal with the ones on the server).

Also I noticed that there is nu linux support which i need becaus MC Server on windows is like burning hundreds of euros/dollors or what ever else down.

I think that you can look like the ftb team have solved this with his 1.7.10 infinity evolved pack ;).

**Comment by DnTheMn** [comment]
as far as im aware when you run the start.bat it downloads all the mods

**Comment by chaos234** [comment]
I can't run a .bat file on linux and normaly a MP has to be deployed with all his content which includes mods, scripts, ressourcpackages and so far.

The best way is to import it on any kind of luncher or with a nice instruction to install it on MultiMC but actually I can't get it running without a compleate zip file :(

**Comment by DnTheMn** [comment]
did you get both .zip files?
https://minecraft.curseforge.com/projects/all-the-mods/files/2329234
https://minecraft.curseforge.com/projects/all-the-mods/files

**Comment by chaos234** [comment]
Again, I can't do anything with a .bat file becaue I am using linux!

And again if you deploy a modpack it has to contain a full version of the MP so files which are only arround 20 MB doesn't meet the conditions to be an MP.

So you have to zip a client instance which contains at last all the configs and all the mods in your MP. You can also deliver a ressource package if you have one.

Then you must look if the server files differ from the client ones and if so, you must also deliver a full pack of it for the server including files to ran the server on linux and ond windows (well, how runs his server on windows is quite stupied in my opinion because linux has a better performance and is free).

Fact is, if I download the arround 20 MB file I can't even play it because where is the minecraft.jar? Where is the launcher.jar? All of them are missing so I can't set it up manually.

Please provide a full package for client and for server incl. a executable linux sh file. I want to play this MP but without those things it isn't possible.

**Comment by DnTheMn** [comment]
the pack is available on curse you can get all the files you require there. the reason you need both of the zips is because one is the overrides which isnt on curse or curse cant host the mod i.e. mekanism

**Comment by chaos234** [comment]
But I only see this overwriting zip and the serverfiles and server files for me are not counting as client files. So I will have a server but I will not have a client ... how bad is this?

And yes, I make the difference between MP-Zip-Files called Client/Server/Universal which means that only an universal.zip will be land on client and server side but a server.zip will only landing on the server side so that there is actually no client side zip file.

Means I can create/build a server with a linux sh file but I am not be able to create a client ones. Sorry but tose are rules, which I follow the reduce problems between client and server.

**Comment by DnTheMn** [comment]
the pack is currently only availiable on the curse launcher which dosent work on linux so you can access the client files from the technic launcher

**Comment by chaos234** [comment]
Yes, the curse launcher should fastly rewritten compleatly in java, like all thos other launchers.

Technic launcher? This sound good. So then I can go and start to play with it, trying to get it run with the additional mods which I have posted on #173 .
