### ISSUE TITLE
Server crash on v1.22 (Linux)

### ISSUE THREAD

**Issue by zyxep** [whatthedrunk/allthemods#178]
Hi,

I just updated my server.
I started the server and ran /fml confirm when it asked to do that or /fml cancel.

But i get an instant crash.
Here is my crash report.

http://paste.ubuntu.com/23165796/
I think it's enderio that fails but not sure.

**Comment by DnTheMn** [comment]
there is an option in your fml options to remove erroring entities try enabling that the it should start up

**Comment by zyxep** [comment]
didn't help @DnTheMn 
:/ new crash report http://paste.ubuntu.com/23165923/

**Comment by DnTheMn** [comment]
there is an update out soon with updated enderio which should fix this hopefully
