### ISSUE TITLE
server loading loop

### ISSUE THREAD

**Issue by deviraux** [whatthedrunk/allthemods#179]
Issue Description:
updated from 1.21 to 1.23 on my server. stuck in loading loop no crash occurs. I deleted everything except the world file put in the new server files and hit launch which causes this error.
Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: caught in loading loop 

What you expected to happen: server to finish loading the world and become playable

Steps to reproduce:

1.update from 1.21 to 1.23
2.start the server and wait
3.
...

Version of All the Mods: 1.23

Added mods (Optifine, Fastcraft, etc.):

1.floricraft
2.agricultural expansion
3.mycommands
...

**Comment by DnTheMn** [comment]
can u edit the forge.cfg to remove erroring blocks

**Comment by deviraux** [comment]
I can see if I can do that I will post again after I test

**Comment by whatthedrunk** [comment]
I will need to see logs if you are still having a problem.
