### ISSUE TITLE
[1.9.4] Conversion to the v0.4 Hotfix

### ISSUE THREAD

**Issue by OuweMickey** [whatthedrunk/allthemods#18]
I have a lot of fence gates in my world, don't know which blocks converted to fence gates, but probably some kind of ore (only fences underground)

They are all Biomes o Plenty fence gates

**Comment by Carrots4U** [comment]
Did you make a backup? An item registry was most liked changed during the conversion

**Comment by OuweMickey** [comment]
Yes, I did. Still a good reason to start a new world.
