### ISSUE TITLE
Digital Miner disappeared after returning from Nether

### ISSUE THREAD

**Issue by TributeR** [whatthedrunk/allthemods#180]
Issue Description: I went to the Nether and came back and the Digital Miner is gone.

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: See above

What you expected to happen: -

Steps to reproduce: I didn't try reproduce it yet, but this isn't the first time it happened. I'm running the latest version of the pack and it happened it a previous version too. The area isn't chunk loaded or anything funny. The game doesn't crash at all.

1.
2.
3.
...

Version of All the Mods: Modpack v1.23 (Nothing changed)

Added mods (Optifine, Fastcraft, etc.): None

1.
2.
3.
...

**Comment by DnTheMn** [comment]
Don't worry you're not alone i thought this bug was fixed but i guess not the main problem is its so random.

**Comment by Carrots4U** [comment]
do you mind trying to chunkload the area then leaving and seeing if it still happens?
