### ISSUE TITLE
fix for netherportal enter exit crash

### ISSUE THREAD

**Issue by ilordnightmarei** [whatthedrunk/allthemods#182]
Issue Description: removing netherportal fix mod  stops  exit enter crash from happaning

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:  server dosnt crash

What you expected to happen: server dosnt crash

Steps to reproduce: remove netherportal fix mod

1. go through netherportal
2.go through netherportal  or teleport home
3.not crash profit
...

Version of All the Mods: latest version 1.23

Added mods (Optifine, Fastcraft, etc.):

1.optifine 
2.betterfps mod
3.
...

**Comment by whatthedrunk** [comment]
Do your crash reports show Java 8 version 25?

**Comment by whatthedrunk** [comment]
If you are still crashing give me a report with a version of java 8-91 or above and reopen thanks!
