### ISSUE TITLE
[1.10 1.24] Tree-Leaves drop as stix and cobble follows gravitiy

### ISSUE THREAD

**Issue by DietmarKrause** [whatthedrunk/allthemods#183]
Issue Description:
Since Update 1.24 : if i chop a tre with either a normal axe or a lumber axe from tinkers the wood drops normal and i get some seeds. but the leaves drop as stix in large amounts. 
Second: If i chop a stone in my mine it first turns into Cobble, the i have to chop it a second time so it can be collected. If i chop over my head in some mine wall it drops as if it was gravel. Only one layer though.
Sounds like some config chenges. Please revert this changes. 
Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:

What you expected to happen:

Steps to reproduce:

1.chop tree completely. See stix dropping instead of leaves
2.
3.
...

Version of All the Mods:

Added mods (Optifine, Fastcraft, etc.):

1.nothing added
2.
3.
...

**Comment by whatthedrunk** [comment]
Are you using the right configs? Did you manually update WTFE by accident?

**Comment by DietmarKrause** [comment]
solved by simply crating a new instance of the modpack with old version, then updgrading this new instance to the new version, copying save folder, Jouneymap and options to the new instance. After that the issues are gone. I had first time installed 64 Java 8.102 developement kit shortly before that, so i was not sure if that was the problem. Besides: The curse cleint has a tendency to forget the Java version and skip back to Launcher Java. 
can be closed
