### ISSUE TITLE
Crafting dupe/bug

### ISSUE THREAD

**Issue by xgamingpro70** [whatthedrunk/allthemods#184]
Issue Description:

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:
When i try to craft it crafts 1 item then i need to move the item and it resets as if i never made the item but i have the created item

What you expected to happen:
Create item and take resources 

Steps to reproduce:

1.Make a crafting table 
2. Craft A chest"Or something"
3. And try to multi click or shift click
...

Version of All the Mods:
1.24

Added mods (Optifine, Fastcraft, etc.):

1. Nothing
2.
3.
...

**Comment by whatthedrunk** [comment]
If you disable HQM does it fix your issue?

**Comment by xgamingpro70** [comment]
Yes it does i have another issue when the modpack does not respond it makes all my stuff not respond like youtube or discord

**Comment by whatthedrunk** [comment]
[Look over this sheet to help with performance issues.](https://docs.google.com/document/d/1cQeLi9x3vN5VKDkAvM3PimoAHipAWGObv4S71m9s5pc)

**Comment by xgamingpro70** [comment]
also a little question i have the shield slow how do i use it

**Comment by xgamingpro70** [comment]
slot*

**Comment by xgamingpro70** [comment]
can you tell me what mod adds the offhand capability please

**Comment by Hazmatik** [comment]
that's a vanilla feature added back in 1.9

**Comment by Carrots4U** [comment]
HQM bug, was removed recently.
