### ISSUE TITLE
Can't open Mechanical user interface after rotation with yeta wrench

### ISSUE THREAD

**Issue by TributeR** [whatthedrunk/allthemods#186]
Issue Description: You can open the GUI of the Mechanical User (Extra Utils 2) when you place it but once you rotate it with a yeta wrench (EnderIO) it wants you to do power sharing as it no longer see's the block as your item.

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: See above

What you expected to happen: To open the GUI normally and configure it

Steps to reproduce:

1. Place the Mechanical User ( Open GUI), it works
2. Rotate with Yeta Wrench
3. Can't open GUI
...

Version of All the Mods: v.124 of All the Mods ( No changes)

Added mods (Optifine, Fastcraft, etc.):

1. No added mods
2.
3.
...

**Comment by DnTheMn** [comment]
can you use the new wrench from extra utils 2 as i believe it has been resolved if not please reopen this issue
