### ISSUE TITLE
Psi Mining spell not working on blocks it should work on

### ISSUE THREAD

**Issue by Hazmatik** [whatthedrunk/allthemods#188]
Issue Description: Mining using a spell from Psi it doesn't break any of the Mekanism ores, or the Environmental Tech stone blocks. It seems to be anything that doesn't show a specified "Mining Level" in WAILA it won't break. The config for Psi says it should break Iron mining level which the Mekanism Tin, Copper, and Osmium ores are all Iron mining level yet they don't break.

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: Blocks with no "Mining Level" specified don't break when using Psi mining spell.

What you expected to happen: Blocks to be broken.

Steps to reproduce:

1. Create CAD and install a mining spell
2. Try to mine any Mekanism ore or Environmental Tech stone
3.
...

Version of All the Mods: 1.24

Added mods (Optifine, Fastcraft, etc.):

1. OptiFine_1.10.2_HD_U_C2
2. ReAuth-3.2
3.
...

EDIT: The config says it breaks blocks of Iron mining level yet it works on Immersive Engineering Lead Ore which says has a mining level of Diamond.

**Comment by Chaogomu** [comment]
A break level of diamond means that an iron pick will break it. Thus this is the correct behavior.

The incorrect behavior is that almost all mod blocks cannot be broken by the break block trick, The list of exceptions is much shorter than the ones works on.

**Comment by Hazmatik** [comment]
Interesting thing was using this 3x3 mining spell with the CAD the modded blocks like those from Environmental Tech and the Mekanism ores would not break. I put the same spell on a Psimetal Pickaxe and the ones it wouldn't break with the CAD it does break.

**Comment by DnTheMn** [comment]
i believe it has been resolved if not please reopen this issue
