### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by sonofgutpig** [whatthedrunk/allthemods#189]
[crash-2016-09-16_20.32.37-client.txt](https://github.com/whatthedrunk/allthemods/files/477591/crash-2016-09-16_20.32.37-client.txt)

Issue Description: Crash on startup

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: I download the pack through curse and when I start it up it crashes after fully loading.

What you expected to happen: load normally into title screen

Steps to reproduce:

1. start mod pack from curse
2. crash
3.
...

Version of All the Mods: see attached file

Added mods (Optifine, Fastcraft, etc.):

1. none
2.
3.
...

**Comment by whatthedrunk** [comment]
Looks like you might have a bad forge installation. open your curse folder and go to Curse\Minecraft\Install\versions and delete them. Edit the pack profile and select the newest forge in the dropdown. Currently 2088.

**Comment by sonofgutpig** [comment]
[crash-2016-09-16_21.50.35-client.txt](https://github.com/whatthedrunk/allthemods/files/477685/crash-2016-09-16_21.50.35-client.txt)

Hi, thanks for the fast response. I did what you suggested but unfortunately still get a crash on start up. See attached crash report. Many thanks.

**Comment by whatthedrunk** [comment]
I don't know if this is the same issue but can you try the following steps I found on google.

"For now, you can work around this by copying the `libraries` folder from a working installation (e.g. install Forge for the vanilla launcher, then you'll find it in `<user>/AppData/Roaming/.minecraft/libraries`) to your Curse setup (Documents/Curse/Minecraft/Install/libraries) "

**Comment by sonofgutpig** [comment]
Thank you that fixed it! you are a genius! Thanks again.

**Comment by whatthedrunk** [comment]
Glad it worked out! Enjoy.
