### ISSUE TITLE
[1.10.2] Nether metals no longer have recipes

### ISSUE THREAD

**Issue by Mechalith** [whatthedrunk/allthemods#19]
Nether copper, zinc, lead, uranium ( and I'm sure a few others) no longer have a smelting or pulverizing recipe as of the 1.10.2 update of the pack.

I haven't updated my server to v0.5, so this may be corrected in the new build, but since I didn't see an issue for it I figured I'd log one just in case. I'll be updating from v0.2 in about 9 hours, and I'll update this as appropriate once I have.

**Comment by Mechalith** [comment]
Confirmed that the nether metals still have no recipe for smelting/grinding/etc.

**Comment by Carrots4U** [comment]
The nether ores for vanilla ores work, so there is not much I can do. All I can say is, "it's a feature".

**Comment by jmcaffee** [comment]
I went with `zs` (minetweaker) scripts:

`nether_ores.zs`:

```
# Add recipes for Nether Ores
#
print("--- loading nether_ores.zs ---");

# NOTES:
# * When adding smelting recipes, EIO alloy smelter only displays 1 to 1 recipes,
#   but it outputs the same count (2) as the furnace recipe.

val oreCopper = <substratum:ore:0>;
val oreNickel = <substratum:ore:2>;
val oreZinc = <substratum:ore:3>;
val oreSilver = <substratum:ore:4>;
val oreLead = <substratum:ore:5>;
val orePlatinum = <substratum:ore:6>;

furnace.addRecipe(oreLead * 2, <nethermetals:nether_lead_ore>);

furnace.addRecipe(orePlatinum * 2, <nethermetals:nether_platinum_ore>);

furnace.addRecipe(oreZinc * 2, <nethermetals:nether_zinc_ore>);

furnace.addRecipe(oreNickel * 2, <nethermetals:nether_nickel_ore>);

furnace.addRecipe(oreSilver * 2, <nethermetals:nether_silver_ore>);

furnace.addRecipe(oreCopper * 2, <nethermetals:nether_copper_ore>);
```

**Comment by whatthedrunk** [comment]
We have this added in the latest beta, let me know if it needs anything else added. Thanks!
