### ISSUE TITLE
Optifine Tesselation Crash

### ISSUE THREAD

**Issue by GoodBob** [whatthedrunk/allthemods#191]
Issue Description:

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:  http://pastebin.com/7xnYzLAy

What you expected to happen: 

Steps to reproduce:

1. Tried upgrading a basic Mekanism tank to the next tier in a Tinker's crafting bench
2. Tested with a friend who is using an AMD card. He did not crash. Tested crashes with GTX960 and 970
3.
...

Version of All the Mods: 1.26

Added mods (Optifine, Fastcraft, etc.):

1. Optifine
2. 
3.
...

**Comment by whatthedrunk** [comment]
Optifine should only be used as a last resort. I would try another version of the mod and see if that helps. [Use this list here to find maybe a better option then Optifine. ](https://docs.google.com/document/d/1cQeLi9x3vN5VKDkAvM3PimoAHipAWGObv4S71m9s5pc/edit)
