### ISSUE TITLE
Iron Door duplication bug

### ISSUE THREAD

**Issue by Nesffer** [whatthedrunk/allthemods#192]
What happens:
iron door has bug. if you break iron door, it drops 2 iron doors.
Maybe.. All of MalisisDoors.
I can smelt iron door. and can make iron ingot.

Version of All the Mods: 1.26

**Comment by vanAndesen** [comment]
The same thing happened to me with a normal Dark Oak door.
ATM v1.25

**Comment by ProsperCraft** [comment]
This has been an issue in the past, I think you are right it is MalisisDoors

**Comment by Carrots4U** [comment]
For reference; https://github.com/Ordinastie/MalisisDoors/issues/100

**Comment by whatthedrunk** [comment]
fixed in the newest version
