### ISSUE TITLE
Mekanism fluid tanks and TC's crafting table

### ISSUE THREAD

**Issue by Atoms88** [whatthedrunk/allthemods#195]
Issue Description: Mekanism fluid tanks can not be placed on TC's crafting table, this will cause a that chunk to nolonger be loadable and crash your game within a second.

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: When placing a Fluid Tank from Mekanism on a TC's crafting table, the game immediately crashed

What you expected to happen: the tank would be visible in a much smaller form on the table

Steps to reproduce:

1. place a tinker's construct table down
2. build a mekanism fluid tank
3. place it on the tinker's construct table
...

Version of All the Mods:

Added mods (Optifine, Fastcraft, etc.):

1. Optifine
2.
3.
...

**Comment by Varil** [comment]
A bit belated, and I don't know if this crash still exists but I had a similar problem that went away after removing Optifine. I couldn't craft the advanced fluid tank, as when I placed the recipe on the crafting bench I would crash. Unfortunately I didn't do extensive testing and this was a while ago so I don't recall the details. I don't know if it was placing the basic tank that caused the problem or the advanced tank being the result.

**Comment by DnTheMn** [comment]
i believe this issue was with tinkers and optfine rendering the items in the table and i believe it has been resolved if not please reopen this issue
