### ISSUE TITLE
v1.28 Duplication bugs: Chisel

### ISSUE THREAD

**Issue by axisonegaming** [whatthedrunk/allthemods#197]
**Issue Description:** 
Two duplication bugs found. The first is when breaking Birch Doors, instead of dropping one, it drops two. The second is with Chisel, and is more serious. Any items placed in an iron chisel do not register that they've been taken out, so for example, if I chisel some Oak Wood Planks, remove them from the chisel and then open it again, the planks I put in are still there, even though I've already placed the items in my inventory. This allows you to duplicate stacks of any material that can be chiseled. 

**What happens:** Items are duplicated

**What you expected to happen:** Items should not be duplicated

**Steps to reproduce:** See above.

**Version of All the Mods:** 1.28

**Added mods (Optifine, Fastcraft, etc.):**
1. Optifine
2. BetterFPS (Client and server)
3. Sampler (Server side) 
4. Tick Profiler (Server side) 
5. Environmental Creepers (Server side)

**Comment by Carrots4U** [comment]
Hmm thanks for the report. I have reported them with the corresponding developers and we will add in the fix once it's complete =)

**Comment by ilordnightmarei** [comment]
the door thing might be malices doors

**Comment by ozhound** [comment]
No longer an issue
