### ISSUE TITLE
Unable to log in :(

### ISSUE THREAD

**Issue by Harith163** [whatthedrunk/allthemods#2]
I tried logging in today with the 0.18 version of the pack, added the latest dev version of chisel and I get a message saying fatally missing blocks.
![screen shot 2016-06-02 at 12 09 50 pm](https://cloud.githubusercontent.com/assets/18382195/15736099/08bbae62-28bb-11e6-94dd-32b1718cc25b.png)

**Comment by Carrots4U** [comment]
Are you running v0.1.8 of the pack? Did you download the build of chisel found on the subreddit, because it is not always the latest dev build we use.

**Comment by Harith163** [comment]
Yeah I am using the build in the subreddit. We should upgrade the chisel build any way, it fixes the terrible lag that we get when placing anything next to a chisel block.

**Comment by whatthedrunk** [comment]
The last version of Chisel caused the server to crash when you broke a block. I see there is another update from 9 hours ago. I will give that one a shot tonight because it seems to be fixed finally.

**Comment by whatthedrunk** [comment]
Also were you able to get in yet? Or is this still open?

**Comment by Harith163** [comment]
no :(. It could be because I have a dev version of world edit also loaded.
Let me try with that.

**Comment by whatthedrunk** [comment]
Make sure to use all the Configs provided as well. That can also cause missing blocks.

**Comment by Harith163** [comment]
bah, I have no clue what I am doing wrong. I will just wait for the 0.1.9
version and retry later. Will you add the tinker's addon's mod later?

**Comment by whatthedrunk** [comment]
I still need to look into it (leaning towards no). I just checked at there is a bug he needs to work out first with auto repair in the hotbar.
