### ISSUE TITLE
Server crash - Enderstorage

### ISSUE THREAD

**Issue by ProsperCraft** [whatthedrunk/allthemods#200]
https://github.com/Chicken-Bones/EnderStorage/issues/77

I was just waiting for this old crash to rear its ugly head again.

Next I expect to see map problems from chickenchunks.

**Comment by Carrots4U** [comment]
What were you doing when the crashed occurred? This it keep happening every time you log in? Please provide more info or use the template :)

**Comment by ProsperCraft** [comment]
That is all the information there is...it happens at random times when players open their enderchest/enderpouch.  Exactly how it happened in 1.7

**Comment by jburrows82** [comment]
OP is running Thermos for 1.7 and Sponge in 1.10, which modify vanilla behavior. Both historically known to break many of the larger packs.

**Comment by DnTheMn** [comment]
im chalking this up to sponge you know the drill please pass it on to them we have 0 crashes when players open enderpouches
