### ISSUE TITLE
Blood moon mobs overload the server.

### ISSUE THREAD

**Issue by ProsperCraft** [whatthedrunk/allthemods#201]
Has the mob amount multiplier been increased from default?

https://github.com/lumien231/Random-Things/issues/131#issuecomment-249350647

**Comment by Carrots4U** [comment]
No we don't have the the multiplier increased. In fact I don't even see a multiplier anywhere in the Random Things config. Is there anyway you can point it to me?...

**Comment by lumien231** [comment]
The mod isn't Random Things it's Bloodmoon.

**Comment by DnTheMn** [comment]
waiting on drunk to update

**Comment by DnTheMn** [comment]
fixed in 1.38
