### ISSUE TITLE
allthemods crashes on load/out of memory errror

### ISSUE THREAD

**Issue by Spookeh70** [whatthedrunk/allthemods#202]
Hello, I have latest version of MC, Curse, and allthemods (I believe).

When I load from launcher, forge starts up but it crashes before it completes due to out of memory error. I have 16gbs.

Here's the pastebin of the report: http://pastebin.com/sAr8MSmi

Thank you for your help!

**Comment by whatthedrunk** [comment]
Just because you have that much ram, does not mean Minecraft is using it. [Use this link to optimize the pack and click on the sample image in the ram section to see how to correct it.  ](http://allthepacks.com/performance.htm)
