### ISSUE TITLE
osx crash on mod insiltion phase with the curse launcher

### ISSUE THREAD

**Issue by hadfordkid** [whatthedrunk/allthemods#205]
Issue Description:osx crash on mod insiltion phase with the curse launcher v1.29

What happens:crashes halfway thrue

What you expected to happen: get to the title screen

Steps to reproduce:

1. launch on osx

Version of All the Mods: default 

Added mods (Optifine, Fastcraft, etc.):

1.n/a

**Comment by whatthedrunk** [comment]
Probably not enough ram but don't submit an issue without a crash log. Reopen once you get a pastebin.com of it and I will be glad to look.

**Comment by hadfordkid** [comment]
my bad http://pastebin.com/eURaH0WK
