### ISSUE TITLE
osx crash on mod insiltion phase with the curse launcher

### ISSUE THREAD

**Issue by hadfordkid** [whatthedrunk/allthemods#206]
Issue Description:osx crash on mod insulation phase with the curse launcher v1.29 (7 gig dedicated)
What happens:crashes halfway true
What you expected to happen: get to the title screen
Steps to reproduce:
	1.	launch on osx
Version of All the Mods: default
Added mods (Optifine, Fastcraft, etc.):
1.n/a

http://pastebin.com/eURaH0WK

**Comment by DnTheMn** [comment]
java.lang.RuntimeException: Error loading user config **please reinstall the pack if you are still having issues reopen this issue**
