### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by PacceFlowrite** [whatthedrunk/allthemods#207]
Issue Description: Game crashes on load

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: Game is crashing either at the end of the mod PreInitialization phase or at the start of the next phase, this is the crash log: http://pastebin.com/wTYdFdD4

What you expected to happen: Game to load correctly to the main menu

Steps to reproduce:

1. Start the game

Version of All the Mods: tried on 1.29 and 1.31 both with same results

Added mods (Optifine, Fastcraft, etc.):

1. Optifine
2. BetterFPS

**Comment by ZiggyAdventures** [comment]
Bad library downloads from Curse

C:\Users\*YOU*\Documents\Curse\Minecraft\Install\libraries\com needs to be deleted and will re-download on Play.
