### ISSUE TITLE
Server crash Mekanism after the 1.32 update.

### ISSUE THREAD

**Issue by ProsperCraft** [whatthedrunk/allthemods#208]
https://github.com/aidancbrady/Mekanism/issues/3853

**Comment by Exceptionfault** [comment]
Same here with 1.10.2 v1.33 when I try to load my local saved game.
http://pastebin.com/gFLkGt6E

**Comment by ProsperCraft** [comment]
https://github.com/ZeroNoRyouki/BigReactors/issues/24#issuecomment-251738183

Mod author would like an update.

@whatthedrunk

**Comment by ZeroNoRyouki** [comment]
Please update to ER 1.10.2-0.4.5.17

Thank you
Z

**Comment by DnTheMn** [comment]
updated
