### ISSUE TITLE
Client crash after updating to 1.31/1.32

### ISSUE THREAD

**Issue by punkdown** [whatthedrunk/allthemods#210]
Issue Description:
Client crashes every 10-15 minutes.

What happens:
Since updating to 1.31 and then 1.32 my client crashes walking around in my base. I can't tell from the crash report what could be causing it.

What you expected to happen:
Not to crash?

Steps to reproduce:

1. Not sure... it happens just walking around.

Version of All the Mods:
1.31 & 1.32
Added mods (Optifine, Fastcraft, etc.):

1. More Overlays

[Crash report](http://pastebin.com/iSxU4BKg)

**Comment by ZiggyAdventures** [comment]
Relevant bug: https://github.com/Ordinastie/MalisisCore/issues/83
Fixed in All the Mods 1.33
