### ISSUE TITLE
IC2 Console spam in 1.37

### ISSUE THREAD

**Issue by ProsperCraft** [whatthedrunk/allthemods#211]
http://pastebin.com/94kGdPzp

On a side note, and somewhat related- 
https://github.com/TechReborn/TechReborn/issues/771

**Comment by ProsperCraft** [comment]
The console spam continues in 1.37

http://pastebin.com/EZw8nthX

The client crashes are continuing to happen, I really wish IC2 was not in this pack.

**Comment by DnTheMn** [comment]
does this still happen?
