### ISSUE TITLE
Sleeping Bag Crash

### ISSUE THREAD

**Issue by Apexii** [whatthedrunk/allthemods#212]
[Crash Report](http://pastebin.com/19xjFFwE)

Issue Description: Sleeping bag crash

What happens: When pressing "P" (keybind for placing an item in the world DE) while holding a sleeping bag. If you mouse over to the sleeping bag the game crashes to your client.

What you expected to happen: No crashes pl0x

Steps to reproduce:

1. Create a New World
2. Get a Sleeping bag
3. Press "P" (or whatever key you set it to) on the ground
4. Mouse over the sleeping bag.

Version of All the Mods: 1.32

Added mods (Optifine, Fastcraft, etc.):

1. Optifine 1.10.2 U C3

**Comment by ZiggyAdventures** [comment]
Vanilla bug, duplicate gripe #196
