### ISSUE TITLE
Unknown Crash: java.lang.IllegalArgumentException: Comparison method violates its general contract!     at java.util.TimSort.mergeLo(TimSort.java:777)

### ISSUE THREAD

**Issue by megajunky** [whatthedrunk/allthemods#216]
Issue Description:
Once I start my savegame,  for 5 sec everything looks normal, but than the screen gets blue and minecraft crashes. This happend first after I wanted to smelt in the "Alloy Smelter" from EnderIO, but I dont know if this is the issue.

Crash Report: 
[http://pastebin.com/8Hyy4xir](url)

Version of All the Mods: 
v1.32

Added mods (Optifine, Fastcraft, etc.):
no

**Comment by rupnerd** [comment]
upgrading to 1.33 fixed the issue for me, had the same problem, i think it came from malisis core which is updated in the new version...

**Comment by ZiggyAdventures** [comment]
You are correct, was MalisisCore and he fixed it, someone can close this.
