### ISSUE TITLE
BQ All the mods 

### ISSUE THREAD

**Issue by SpiCraftsman** [whatthedrunk/allthemods#218]
PLs add hardcore questing mod i really like it
 
thank you 
for your time

**Comment by bookerthegeek** [comment]
I would prefer [Better Questing](https://mods.curse.com/mc-mods/minecraft/238856-better-questing) to [HQM](https://mods.curse.com/mc-mods/minecraft/hardcore-questing-mode) mainly due to HQM still being on 1.7.10

**Comment by SpiCraftsman** [comment]
Ok doesn't matter i want quests nothing else

**Comment by DnTheMn** [comment]
this is already planned we are waiting on a bug to be patched
