### ISSUE TITLE
Model Load Crash

### ISSUE THREAD

**Issue by FarisRafael** [whatthedrunk/allthemods#219]
Model Load Crash:

What happens:
when i open minecraft and let it load all the mods but when it come to
render the model it just stop and crash

Please Tell Me How To Fix it

Steps to reproduce:

1.Load The Mods
2.Load The Texture
3.Load The Model
4.Crash

Version of All the Mods: 1.34

Added mods (Optifine, Fastcraft, etc.):

1.Optifine
2.BetterFps

[Crash Log](http://pastebin.com/Nu1ERb66)

**Comment by magicbel** [comment]
Same problem for my friend and me.
If you searching with the error log, you can see the reason : Optifine and Forge :/
Disable Optifine and the game start but, for me only, i turn with 2fps.

I expect an update

**Comment by FarisRafael** [comment]
I Tried To Remove Optifine But It Not Work for Me

**Comment by magicbel** [comment]
Back to 1.33 👎

**Comment by ZiggyAdventures** [comment]
Downgrade extrautil, the latest version is incompatible with Optifine.

**Comment by magicbel** [comment]
👍 Nice ! I try with a old version, tks !

**Comment by ZiggyAdventures** [comment]
Use Optifine C4 under preview versions of Optifine Downloads page.
