### ISSUE TITLE
[Suggestion] Add CraftingTweaks mod (Quality of Life)

### ISSUE THREAD

**Issue by jmcaffee** [whatthedrunk/allthemods#22]
Crafting Tweaks (not Craft Tweaks) adds buttons and key binds to crafting tables allowing for single key clearing of the grid, rotation of the grid and balancing of the grid. 

I've added it to my local copy of this pack and think it would be a great addition to this pack. It works both client and server side.

[minecraft.curseforge.com/projects/crafting-tweaks](http://minecraft.curseforge.com/projects/crafting-tweaks)

**Comment by whatthedrunk** [comment]
Adding it right now if it works out well it will stay, thanks!

**Comment by jmcaffee** [comment]
Great!

FYI, to get the tweaks to work with TiCon crafting benches, I used the linked configs:

[craftingtweaks.cfg](http://pastebin.com/GmqaEYTz)

[TinkerModules.cfg](http://pastebin.com/iFHjd4pB)  See the last line...
