### ISSUE TITLE
CTD when re-connecting to multiplayer server

### ISSUE THREAD

**Issue by Andruvan** [whatthedrunk/allthemods#220]
**Issue Description:** After disconnecting/being disconnected from a multiplayer server the client crashes to desktop when attempting a reconnect.

**What happens:** CTD on attempt to reconnect
**What you expected to happen:** No CTD

Steps to reproduce:
1. Connect to multiplayer server
2. Disconnect from said server
3. Attempt to join server again

Version of All the Mods: 1.34, 1.32, 1.31

Added mods (Optifine, Fastcraft, etc.): None
[crash-2016-10-08_14.59.54-client.txt](https://github.com/whatthedrunk/allthemods/files/517699/crash-2016-10-08_14.59.54-client.txt)

**Comment by DnTheMn** [comment]
this is the ic2 crash its still around but only happens when the game has been left open so i'll keep this open until its resolved and in future can you please use pastebin or ubunta to share you reports thanks.
