### ISSUE TITLE
Crash on mod load (clean MC and forge install)

### ISSUE THREAD

**Issue by XiloTheOdd** [whatthedrunk/allthemods#221]
Issue Description: upon loading forge profile operation stops and a log is produced: http://pastebin.com/VpUDmXYT

What happens:
Log read an Error on 3 Mekanism related mods
What you expected to happen:
for it to function as intended and load to the title screen

this all done on a brand new install of minecraft, forge, and the latest version of allthemods, and forge.
this pack looks really awesome i hope i can get this figured out.

edit: i updated the mekanism homebrew all to the 3 seprate ones of the Mekanism official page ver. 292, the game now loads the mods appropriately. however it fails on world initialization.

conclusion: i dont know why at this point but all i had to do was remove Mekanism, replace it with the 3 seperated version of Mekanism from the official webpage, then after loading a world, re-add the original Mekanism file, and now the game loads it just fine. very strange.

**Comment by ZiggyAdventures** [comment]
You are trying to run the manifest, and it's running the overrides only(hence missing mcmultipart from the manifest. Use either Curse App or Vazkiis downloader. The website download button is manifest only. As an alternative you can download the server files from the website, but it won't have client side mods.

**Comment by XiloTheOdd** [comment]
wait so downloads directly off the curse website arent the whole modpack? thats... i cant even describe how backwards that is. i never needed curse app to mod MC before i'd rather manually add the files myself.

checking my mods there does seem to be a massive amount missing. just what is the total file size of the mod? cant be that big.
