### ISSUE TITLE
Crash on save-world

### ISSUE THREAD

**Issue by Micro2444** [whatthedrunk/allthemods#224]
Issue Description:  Crash on save world.

Version: 1.10.2 v1.35 (Release)(current)
Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: It crashes out and says the server is closed.

What you expected to happen:  To save the world or any auto save.

Steps to reproduce:
1. Login to MP Server
2. /save-world
3. Game crash
   ...

Version of All the Mods: No added mods/whatever I downloaded

Added mods (Optifine, Fastcraft, etc.):

1.
2.
3.
...

Crash Report: [crash-2016-10-12_16.50.17-server.txt](https://github.com/whatthedrunk/allthemods/files/525621/crash-2016-10-12_16.50.17-server.txt)

Start bat:

java -server -Xms1G -Xmx6G -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=20000 -jar forge.jar nogui

**Comment by ProsperCraft** [comment]
/save-world is not a command, doing /save-all does work with no crash on ProsperCraft, Forge no Sponge.
