### ISSUE TITLE
Now the server is just crashing after it boots.

### ISSUE THREAD

**Issue by Micro2444** [whatthedrunk/allthemods#225]
Issue Description: Crashing after the server boots up.

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: Crashes after server boots up.

What you expected to happen: For the server to boot correctly.

Steps to reproduce:

1. Start server 
2. Wait for server
3. Server crashes
...

Version of All the Mods: Current release versions

[crash-2016-10-12_17.18.00-server.txt](https://github.com/whatthedrunk/allthemods/files/525673/crash-2016-10-12_17.18.00-server.txt)
 

Added mods (Optifine, Fastcraft, etc.):

1. None 
2. None
3. None
...

**Comment by whatthedrunk** [comment]
Looks like you have something here 518,57,61/518,58,64 that you will want to mcedit out, if its still giving you issues in the new version I can submit the crash report to the correct place.
