### ISSUE TITLE
ESD (Actually Additions) cannot pull (inbound) from Vacuum Chest (EnderIO)

### ISSUE THREAD

**Issue by Uphio** [whatthedrunk/allthemods#227]
Issue Description: Actually Additions' ESD cannot pull items from the EnderIO Vacuum Chest.

What happens: The ESD does not pull any items from any slot in the Vacuum Chest, despite proper inventory slot and cardinal direction configurations.

What you expected to happen: The ESD should be able to pull from the Vacuum Chest!

Steps to reproduce: 
1. Place an ESD. Place a Vacuum Chest beside it (touching!)
2. Place a chest (output) on another side of the ESD.
3. (Using F3 for cardinal directions) Configure the ESD's _inbound_ (side with vacuum chest) and _output_ (the chest).
4. Regardless of ESD slot selections for either inventory, nothing will be pulled from the Vacuum Chest.

Version of All the Mods: **1.35**

Added mods (Optifine, Fastcraft, etc.): **None**

**Comment by Ellpeck** [comment]
What version of EnderIO have you tried this with? Because with 3.0.1.125_beta it works perfectly.

**Comment by DnTheMn** [comment]
he was using EnderIO: 3.0.1.1,120_beta.jar so an update will fix it thanks :)
