### ISSUE TITLE
Crash when using PA Wrench on Progressive Automation blocks

### ISSUE THREAD

**Issue by Wiregeek** [whatthedrunk/allthemods#228]
Issue Description:

Crash when shift-right-click on Progressive Automation chopper, crafter with PA Wrench

What happens:
Server crash

What you expected to happen:
Output, Input, FuelInput, set or Rotation of block
Steps to reproduce:
1. place crafter or chopper, place inventories next to
2. shift right click with PA Wrench
3. ???
4.  Server crash
   ...

Version of All the Mods:
1.35 from Curse
Added mods (Optifine, Fastcraft, etc.):
1. Veinminer
2. Disabled primary Spice of Life functionality with config file.
   3.
   ...

**Comment by ozhound** [comment]
Does not Crash the Server. Causes a Client Crash

https://paste.ubuntu.com/23446269/

Still current as at 1.42b version of the pack
