### ISSUE TITLE
White Texture On Animals

### ISSUE THREAD

**Issue by MokahTGS** [whatthedrunk/allthemods#229]
Issue Description:

All animals have a white texture instead of normal textures.

What happens:

What you expected to happen:

Steps to reproduce:

1. Download mod pack and launch new world.
2.White textures on animals
3.
...

Version of All the Mods:
Newest from the Curse Launcher

Added mods (Optifine, Fastcraft, etc.):

None

**Comment by CvoidWyvern** [comment]
How did you find fastcraft for 1.10?

Also, "etc" doesn't cut it as mods like those are known to cause problems like this.

**Comment by MokahTGS** [comment]
I didn't...that was in your bug report template.  There aren't any added mods...just your modpack.  The issue is the latest version of Journeymap...switch to the release and not the beta and the issue is fixed.
