### ISSUE TITLE
[1.37] Mekanism "Electric Bow" does not use Bullseye arrows

### ISSUE THREAD

**Issue by Boomflex** [whatthedrunk/allthemods#232]
Issue Description: Mekanism "Electric Bow" does not use Bullseye arrows

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: Mekanism "Electric Bow" does not use Bullseye arrows

What you expected to happen: Mekanism "Electric Bow" to use Bullseye arrows

Steps to reproduce:
1. Make Electric Bow from Mekanism
2. Make Bomb Arrow from Bullseye
3. Use Bow, arrow doesn't work and turns to "Training Arrow" upon contact of animal/mob/wall
   ...

Version of All the Mods: Latest as of ATM 1.37

Added mods (Optifine, Fastcraft, etc.):
1. n/a
   2.
   3.
   ...

**Comment by ZiggyAdventures** [comment]
Mekanism is on a slow update schedule since Aiden started college. Unfortunately this issue will remain for a while.

**Comment by DnTheMn** [comment]
fixed in 1.42 bullseye got removed
