### ISSUE TITLE
Engineer's Manual crash

### ISSUE THREAD

**Issue by Traville** [whatthedrunk/allthemods#233]
Issue Description: Crash upon viewing the "Ear Defenders" page in the immersive Engineering Engineer's Manual

What happens: Crash to launcher

Steps to reproduce:

1. Open the Engineer's Manual
2. Click on the "Ear Defenders" page
3. Profit!
...

Version of All the Mods: 1.37

Added mods (Optifine, Fastcraft, etc.):

1. Applied Energistics 2

Crash Log:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000000764831fa, pid=15180, tid=9904
#
# JRE version: Java(TM) SE Runtime Environment (8.0_25-b18) (build 1.8.0_25-b18)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.25-b02 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# V  [jvm.dll+0x4431fa]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# A:\Big Ol' Programs\CURSE\Minceraft\Instances\All the Mods\hs_err_pid15180.log
#
# Compiler replay data is saved as:
# A:\Big Ol' Programs\CURSE\Minceraft\Instances\All the Mods\replay_pid15180.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
#
AL lib: (EE) alc_cleanup: 1 device not closed
[0x7FF99A6E3560] ANOMALY: meaningless REX prefix used
[0x7FF971E64450] ANOMALY: meaningless REX prefix used
[0x7FF971E690E0] ANOMALY: meaningless REX prefix used
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0

**Comment by DnTheMn** [comment]
i believe it has been resolved by updating java to latest if not please reopen this issue
