### ISSUE TITLE
All the Sky - Report unobtainable items here

### ISSUE THREAD

**Issue by whatthedrunk** [whatthedrunk/allthemods#237]
[Pack is located here if you want to help out with the super early build. ](https://minecraft.curseforge.com/projects/all-the-sky)
- [x] Osmium
- [x] Bee's 
- [ ] Apatite
- [ ] Rubber Tree sapling IC2
- [ ] Rubber Tree sapling TechReborn
- [ ] yellorium 

Things to add to oredict
- [ ] IC2 and Tech Reborn Sapplings
- [ ] IC2 Raw Carbon Fibre & Tech Reborn Carbon
- [ ] IC2 Raw Carbon Mesh & Tech Carbon Mesh
- [ ] IC2 and Tech Reborn Carbon Plate

**Comment by rgtexa** [comment]
Unable to craft Actually Additions Dough - recipe conflicts with Ex Compressum Cow Bait.

**Comment by mjctechguy** [comment]
Apatite

**Comment by stripeyhorse** [comment]
Osmium can be fixed with the Ex Nihilo Config.

B:"force osmium"=true

**Comment by stripeyhorse** [comment]
yellorium is unavailable.

**Comment by stripeyhorse** [comment]
Actually Additions Dough is craftable. use the button in the crafting table to switch between recipes,

CONFIRMED working.

**Comment by Oli4TheWin** [comment]
pestle and mortar isnt craftablr right?

**Comment by OrdinatorStouff** [comment]
closing due to mostly no longer being relevant
