### ISSUE TITLE
techreborn issue 2

### ISSUE THREAD

**Issue by DnTheMn** [whatthedrunk/allthemods#239]
Issue Description: wrench no work

What happens:the wrench dont work

What you expected to happen: the tech reborn wrench to rotate and pick up blocks

Steps to reproduce:

1.get wrench (techreborn) 
2.place machine 
3.try to rotate or pickup
4.say good bye to the machine because you broke it with the wrong tool

Version of All the Mods:1.38

**Comment by modmuss50** [comment]
Are you talking about the ic2 wrench? Or the Techreborn one?

**Comment by DnTheMn** [comment]
tech reborn wrench

**Comment by DnTheMn** [comment]
"Steps to reproduce:

1.get wrench (**techreborn**)"

**Comment by whatthedrunk** [comment]
Let me know if this has been fixed in the newest version.

**Comment by modmuss50** [comment]
It hasnt just yet. I think I'm gonna do some more version 1 bug fixes while we work on 2. As it's taking longer than I had hoped.

**Comment by modmuss50** [comment]
I also put a beta out today that should fix at least two known dupe bugs.

**Comment by whatthedrunk** [comment]
Yeah when I did my hotfix I made sure to put your new update in. Really looking forward to 2.0 but bug fixes are always nice. Once 2.0 comes out I may add it to lite and @al132 may add it back to expert once its stable. Is there a changelog on what this fixed?
