### ISSUE TITLE
DUPE BUG (JUST CREOSOTE BOTTLES)

### ISSUE THREAD

**Issue by cmann21** [whatthedrunk/allthemods#241]
Issue Description: When I put Creosote bottles (16) in crafting table from tinkers, with planks to create immersive engineering treated wood, I shift click and instead of giving me empty bottles back, it gives me a stack of full creosote bottles. 

What you expected to happen: I only expect to get empty bottles and the stack size is only 16 but it gives me a stack of 64 full creosote bottles

Steps to reproduce:

1.put 16 creosote bottles in middle of tinker constuct crafting table
2.put planks all the way around 
3.shift left click to get end result
...

Version of All the Mods: This is the most updated version as of 10-20-16

Added mods (Optifine, Fastcraft, etc.):    No added mods.

1.
2.
3.
...

**Comment by DnTheMn** [comment]
looks to be fixed and with the new version of railcraft due to be released on 31 october

**Comment by DnTheMn** [comment]
can you let me know if this is still the case in 1.40b
