### ISSUE TITLE
Chestcarts are visible through terrain

### ISSUE THREAD

**Issue by ozhound** [whatthedrunk/allthemods#243]
Issue Description: Chestcarts are visible through the terrain making it easy to find abandoned mineshafts

Version of All the Mods: 1.38b

Added mods (Optifine, Fastcraft, etc.):

Tested with and without optifine and on multiple servers (ATM Testing server and new personal server)

![image](https://cloud.githubusercontent.com/assets/3649237/19591757/29c9ab9a-97ab-11e6-9a37-6ffc192e1fbd.png)
![image](https://cloud.githubusercontent.com/assets/3649237/19591762/2f988ae6-97ab-11e6-8534-736bc0067a26.png)
![image](https://cloud.githubusercontent.com/assets/3649237/19591774/3c447f7a-97ab-11e6-84ac-16be26596e98.png)

**Comment by DnTheMn** [comment]
fixed in next update
