### ISSUE TITLE
All the Sky: Heavy Sieve recipe results don't match actual

### ISSUE THREAD

**Issue by rgtexa** [whatthedrunk/allthemods#244]
Issue Description:

The results listed in JEI for the result of sieving compressed blocks do not match what is received.

What happens: Sieve compressed blocks in a heavy sieve with an any mesh (tested with silk and iron) and receive less items than indicated in JEI (for example, 1 diamond vs. the 14 shown in JEI, or 3 lapis vs, the 7 shown in JEI).

What you expected to happen: Receive number of items in line with JEI recipe result.

Steps to reproduce:
1. Craft heavy sieve and place. Craft iron mesh and place in heavy sieve.
2. Sieve compressed gravel and compare number of items received to recipe result shown in JEI,
   ...

Version of All the Sky: 0.3

Added mods (Optifine, Fastcraft, etc.):
N/A

**Comment by OrdinatorStouff** [comment]
![2016-12-26_11 07 52](https://cloud.githubusercontent.com/assets/6283913/21487432/da5022c4-cb85-11e6-8f05-3f298d2f7de6.png)
![2016-12-26_11 08 02](https://cloud.githubusercontent.com/assets/6283913/21487431/da4fb4f6-cb85-11e6-84e9-d2c882a3c4a1.png)

I do see what is mentioned here. Tooltip seems to imply x14 drops although only 1 makes more sense. There doesn't seem to be any crafttweaker recipes that would be interfering so maybe it's just a tooltip bug... will need to investigate a little farther.

**Comment by OrdinatorStouff** [comment]
going to assume this is intended by ex compressum or a tooltip bug and leave it at that.
