### ISSUE TITLE
All the Sky: Compressed Hammers repair themselves

### ISSUE THREAD

**Issue by rgtexa** [whatthedrunk/allthemods#245]
Issue Description:

Compressed Stone Hammer repairs itself. Have not tested iron or diamond compressed hammers.

What happens: Use the compressed stone hammer to hammer compressed blocks and the hammer shows durability damage, but will repair itself if not in use.

What you expected to happen: Durability damage should not be repaired.

Steps to reproduce:
1. Craft compressed hammer and use it on compressed blocks.
2. Leave hammer unused in inventory and the damage will repair in a few seconds.

Version of All the Sky: 0.3

Added mods (Optifine, Fastcraft, etc.):
N/A

**Comment by OrdinatorStouff** [comment]
I was unable to reproduce this. @rgtexa are you still experiencing this and if so are you able to reproduce the issue on a new instance (fresh pack install) single-player world as well?

Possibly config related?
