### ISSUE TITLE
ATS: v0.3 Might want to consider removing or moving Slime Islands.

### ISSUE THREAD

**Issue by kd0pls** [whatthedrunk/allthemods#246]
Issue Description:  Created a new world to play in and spawned in to see  [http://imgur.com/uCsG774](url).

What happens:  Slime Island next to spawn island.

What you expected to happen:  No Slime Island or have them higher in the sky.

Steps to reproduce:
1.  seed is:  -2479854951853939199
2. Turn to look directly east of spawn.

All the Sky v0.3

Added mods (Optifine, Fastcraft, etc.):
1.  N/A

**Comment by OrdinatorStouff** [comment]
Confirmed this is a bit out-of-place still in v1.0.1
I created a new world of a random seed and an island was nearby and of same height. Should be fixed to not create slime islands near spawn (or just reduce spawn rates) as well as make them higher up if possible as well.

**Comment by OrdinatorStouff** [comment]
To-Be-Active in pack version 1.0.2 --
Disabled Slime Island Generation in the main Overworld. These should still generate in custom dimensions, though.
