### ISSUE TITLE
Mod recommendation: Default Options for preset MipMap:0 for AtM lite

### ISSUE THREAD

**Issue by ZiggyAdventures** [whatthedrunk/allthemods#247]
Recommend Default Options to auto-set MipMap to 0 for All the Mods lite:

Mod Link:
https://mods.curse.com/mc-mods/minecraft/232131-default-options

Configured Options for MipMap:0, place in config folder.
https://drive.google.com/open?id=0BzPjAURW54rQWVNiOHpSWEhaZnM

Note: This only takes effect on first load where Options.txt does not exist. it will not effect already ran instances.

**Comment by DnTheMn** [comment]
this is added thanks Z
