### ISSUE TITLE
[1.10.2 v0.7] Lunch Box broken texture

### ISSUE THREAD

**Issue by OuweMickey** [whatthedrunk/allthemods#25]
In the newest version the Lunch Box (when ready to eat) is missing the texture.

**Comment by Carrots4U** [comment]
It's being looked into by the developer :) We will update when he releases the fix.

**Comment by whatthedrunk** [comment]
This has been fixed and will be in the new Alpha tonight. If you are playing single player just delete the Reliquary config file and you should be good to go.
