### ISSUE TITLE
end crystals not removeable, dragon heart does not drop

### ISSUE THREAD

**Issue by acidjazz** [whatthedrunk/allthemods#250]
This is on allthemods from v1.38b to v1.39 now

the crystals are not able to be damaged anymore, even block breakers and pistons do nothing.
also if i summon the dragon the vanilla way and kill him even w/ the health regen, no dragon heart drops.
the animations of the dragon being healed have also stuck at the top of x0, z0, even though he's dead

![image](https://cloud.githubusercontent.com/assets/967369/19714324/23d6590e-9b02-11e6-8906-101fd03dd53a.png)

**Comment by DnTheMn** [comment]
what way did you spawn it in the first place the end crystals are craftable hense you cant move them anymore i believe
