### ISSUE TITLE
Old JEI version is causing ReadTimeoutException on Server

### ISSUE THREAD

**Issue by Rain336** [whatthedrunk/allthemods#252]
## Issue Description:
JEI is Initializing it's plugins during the world load.
This delayes the Packets for 30 seconds or longer and causes a ReadTimeoutException at the Server.
The Problem has been fixed with JEI version 3.13.0. (mezz/JustEnoughItems#353)

## What happens:
A RedTimeoutException during Serverlogin.

## What you expected to happen:
Not a ReadTimeoutException during Serverlogn.

## Steps to reproduce:
1. Setup a Dedicated Server.
2. Join The Server with a Client.

## Version of All the Mods:
V1.39

### Server only:
1. SpongeForge
2. Worldedit

**Comment by DnTheMn** [comment]
is it possiable that this could be a sponge issue?

**Comment by nightred** [comment]
I am experiencing the same issue with many of my players, and do not have sponge installed.

**Comment by DnTheMn** [comment]
ok see the new version well last from latest wasnt working with plugins and loading twice

**Comment by DnTheMn** [comment]
fixed when 1.40 is out in 30-60 mins
