### ISSUE TITLE
[Expert] Can't progress in Embers; no access to lead ore

### ISSUE THREAD

**Issue by diggoran** [whatthedrunk/allthemods#256]
In order to pump items out of an Ember Bore, you need an Item Pump, which is made using Item Pipes, which require lead nuggets. So far, I only have access to flint pickaxes, which can't mine at level Iron, needed for Lead mining.

Am I missing something? The guide book told me to follow an Embers guide, and I assume there aren't any better picks available yet, nor any alternate ways of pumping items out of a Bore, since you can't put a hopper underneath it.

**Comment by DnTheMn** [comment]
@al132 issue for you i think

**Comment by DnTheMn** [comment]
"lead is mineable with reinforced stone tools from calculator
so they have access to better than flint" (Thanks to goosezilla)

if you have more questions or possiably bugs you should swing by the curse chat and we can confirm if its a bug or not :)
https://www.curse.com/servers/y7A2Cr
