### ISSUE TITLE
Crash report for private server

### ISSUE THREAD

**Issue by TheKiwog** [whatthedrunk/allthemods#258]
Issue Description: Server crashes expected to be because of AbyssalCraft AbyssalZombie

What happens: server crashes

What you expected to happen: server not to crash

Steps to reproduce:

1.It happens while playing Randomly

Version of All the Mods: 1.40

Added mods (Optifine, Fastcraft, etc.):

1. Veinminer

[crash-2016-10-31_23.22.56-server.txt](https://github.com/whatthedrunk/allthemods/files/561710/crash-2016-10-31_23.22.56-server.txt)

**Comment by DnTheMn** [comment]
this has been reported by myself ti the abyssalcraft guys you can fix it by changing the time in the host pc
as a temp fix

**Comment by DnTheMn** [comment]
https://github.com/Shinoow/AbyssalCraft/issues/155#issuecomment-257228267

**Comment by DnTheMn** [comment]
fixed with new update
