### ISSUE TITLE
Continuos Crash

### ISSUE THREAD

**Issue by quiquecal** [whatthedrunk/allthemods#261]
Issue Description: After a couple of minutes playing the game crashes

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: I send the crash report below
[crash-2016-10-31_11.27.07-server.txt](https://github.com/whatthedrunk/allthemods/files/562606/crash-2016-10-31_11.27.07-server.txt)

What you expected to happen:

Steps to reproduce:

1.
2.
3.
...

Version of All the Mods: 1,40b

**Comment by DnTheMn** [comment]
https://github.com/Shinoow/AbyssalCraft/issues/155#issuecomment-257228267

**Comment by DnTheMn** [comment]
fixed with new update
