### ISSUE TITLE
Random CTDs

### ISSUE THREAD

**Issue by Retrov101** [whatthedrunk/allthemods#262]
Issue Description: CTD (from Brandon Core & Tesla?)

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: The modpack randomly ctds on occasion, the crash report mentions Brandon Core and the Tesla mod, neither of which I use or know about. (Crash report at end)

What you expected to happen: Stable gameplay.

Steps to reproduce: None, occurs randomly. Happened when placing a sign, looking at achievements, and without any reason whatsoever.

1. Placing a sign
2. Looking at achievements
3. Without any reason whatsoever
...

Version of All the Mods: v1.41

Added mods (Optifine, Fastcraft, etc.): None

1.
2.
3.
...

One of The Crash Reports:
[crash-2016-10-31_17.17.11-client.txt](https://github.com/whatthedrunk/allthemods/files/563102/crash-2016-10-31_17.17.11-client.txt)

**Comment by DnTheMn** [comment]
i believe its looking at achievements that caused it what page were you on?

**Comment by Retrov101** [comment]
I went to the Actually Additions achievement page through the guidebook, but there were 3 or 4 other crashes with the same error message that I don't think were related to achievements directly.
-------- Original message --------From: daniel tully <notifications@github.com> Date: 11/1/16  4:47 AM  (GMT-08:00) To: whatthedrunk/allthemods <allthemods@noreply.github.com> Cc: Retrov101 <trexgolden@gmail.com>, Author <author@noreply.github.com> Subject: Re: [whatthedrunk/allthemods] Random CTDs (#262) 
i believe its looking at achievements that caused it what page were you on?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/whatthedrunk/allthemods","title":"whatthedrunk/allthemods","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/whatthedrunk/allthemods"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DnTheMn in #262: i believe its looking at achievements that caused it what page were you on?\r\n"}],"action":{"name":"View Issue","url":"https://github.com/whatthedrunk/allthemods/issues/262#issuecomment-257547384"}}}

**Comment by ozhound** [comment]
Ive logged an issue with Ellpeck. waiting his response

https://github.com/Ellpeck/ActuallyAdditions/issues/321

**Comment by Retrov101** [comment]
I managed to replicate the crash on the achievements page, I think the others were random and unrelated, but this one is reproducible. If you zoom out all the way and drag the page to the top left, the game crashes. It happens on the Actually additions page and botania page, and probably the others too. Here is the new crashlog.
[crash-2016-11-05_16.58.48-client.txt](https://github.com/whatthedrunk/allthemods/files/573576/crash-2016-11-05_16.58.48-client.txt)

**Comment by DnTheMn** [comment]
unfortunatly ellpeck cant fix it
