### ISSUE TITLE
Can't leave bed

### ISSUE THREAD

**Issue by syntaxjedi** [whatthedrunk/allthemods#263]
Issue Description: Randomly can't leave the bed. When waking up, escaping out, or pressing "leave bed" the gui refuses to close and have to close/relaunch the game.

Steps to reproduce: There are no steps to reproduce, it seems to happen randomly.

Version of All the Mods: 1.10.2/v1.41

Added mods (Optifine, Fastcraft, etc.): no added mods

There is no error log, the game shut down safely.

**Comment by CvoidWyvern** [comment]
It's a vanilla bug.  Not sure if it happens more frequently in modded or if it just looks that way because modded players report bugs more often.

**Comment by syntaxjedi** [comment]
I'm updating it now, but I figured out it only happens when you hold something in your main hand.

**Comment by MitoniKatsu** [comment]
Have had the same issue on our server. best solution seems to be to spam emotes til server kicks you, and relogin

**Comment by syntaxjedi** [comment]
I have only seen it in single player.

**Comment by ozhound** [comment]
happens all the time in multiplayer

**Comment by DietmarKrause** [comment]
I have seen the bed bug almost every time after i teleport (may it be in SP with the journeymap command, may it be Nether portal or RF teleporter), rarely without that. After teleportation i relog always out of that reason.

**Comment by ozhound** [comment]
Vanilla Bug - Still unresolved since November 2015

https://bugs.mojang.com/browse/MC-92216
