### ISSUE TITLE
Crash/World Corruption from clicking bits in a bit bag

### ISSUE THREAD

**Issue by MitoniKatsu** [whatthedrunk/allthemods#264]
Issue Description: Crash/World Corruption from clicking bits in a bit bag

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: Server crashes and world is corrupted thereafter when you open a bit bag and click on any bits.

What you expected to happen: nothing, worked fine prior to 1.41 update

Steps to reproduce:

1. Open a chisels and bits Bit Bag with any type of bits in it and click on them
2.Crash is immediate
3. Server has to be restored from backup before anyone can login again without getting immediately disconnected. Restored from backup, and duplicated issue immediately after trying to click on bits in bit bag again.

Crash Log: http://pastebin.com/kBVbvctr
...

Version of All the Mods: v1.41

Added mods (Optifine, Fastcraft, etc.):

1. n/a
2.
3.
...

**Comment by instinxx** [comment]
Fixed in latest FYI
https://github.com/AlgorithmX2/Chisels-and-Bits/issues/159

**Comment by DnTheMn** [comment]
fixed in 1.42
