### ISSUE TITLE
All The Sky: Crash When Start The game

### ISSUE THREAD

**Issue by FarisRafael** [whatthedrunk/allthemods#265]
Issue Description:
In A.T.S ver 0.6 when i tried to play the game crash

What happens:
At First I Thing I Just The Mod That i Add But When I Delete Them All its Still Crash Im So Cenfused So
Any Help......

Crash Log:
[LOG](http://pastebin.com/BRY2sG4i)

What you expected to happen:
Play Normaly

Steps to reproduce:

1.Hits Play
2.Crash
Version of All the sky:0.6

Added mods:

1.sampler
2.BetterFPS

**Comment by OrdinatorStouff** [comment]
A fresh pack install install (new, unmodified profile of latest version) should fix this issue.

Some quick research on InvocationTargetException alludes to either outdated mods or conflicting/duplicate mods or configs. Also I believe the sampler mod referred to is a coremod for low-level profiling and if so could introduce many issues and should only be used as a troubleshooting tool when needed and not left installed all the time.

**Comment by OrdinatorStouff** [comment]
please open a new issue if you're having any issues still after 1.0.7 update
