### ISSUE TITLE
Chisels and bits bitbag emptying crashes the server.

### ISSUE THREAD

**Issue by ProsperCraft** [whatthedrunk/allthemods#266]
https://github.com/AlgorithmX2/Chisels-and-Bits/issues/161

**Comment by AlgorithmX2** [comment]
https://github.com/whatthedrunk/allthemods/issues/264 - Already Fixed.

**Comment by DnTheMn** [comment]
were gonna push a hotfix in the next few days hopefully

**Comment by DnTheMn** [comment]
fixed in 1.42
