### ISSUE TITLE
[expert] Black Screen When Looking at Chest Carts

### ISSUE THREAD

**Issue by TieMonkey** [whatthedrunk/allthemods#267]
Issue Description: [expert] Black Screen When Looking at Chest Carts

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: screen goes black when Chest Carts are spawned into the world in mineshafts

What you expected to happen: Not to go blind.

Steps to reproduce:

1. Load World Up.
2. Find a Mineshaft that has Chest Carts in them.
3. Look at said Chest Carts
...

Version of All the Mods: [expert] v.0.64Beta

Added mods (Optifine, Fastcraft, etc.):

1. Optifine (but happens without Optifine as well.)
2.
3.
...

Heres a gif of what it looks like from above ground.

https://gyazo.com/a660e98275e1de45740fb53d6bc3ddf7

When I searched in creative to find what those bright spots were i found this

https://gyazo.com/199c7668047a28f48e7e296a3487e506

When I broke one of the Carts, the black screen would go away as long as no other carts were in render distance and in line of sight

**Comment by al132** [comment]
This is probably a bug with the Railcraft "Halloween event". The next release of the expert pack will have the updated version of railcraft, but until then there should hopefully be a config option in the version of railcraft currently in the pack. See https://github.com/CovertJaguar/Railcraft/issues/956#issuecomment-255287428

**Comment by TieMonkey** [comment]
ahh yea that makes sence, thank you
