### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by DnTheMn** [whatthedrunk/allthemods#269]
Remove - Auto Packager - Not needed and cant compared to rft crafter

Remove - Easy Breading - Simply not needed and not many people know what it even does

Remove - Corrilated (fake ae mk1) - it was useful at the start but it has became useless 2 ae mods is enough.

Remove - Experience Rings - exp isnt hard to get and the rings are really rare i have yet to find one and that only shows that its not needed

Remove - wawla - forces players on servers to use waila as its a dependecy cant use wit or any other hud mods.

Remove - Login Shield - The mobs are rare now and arent as op as they usted to be mostly so its not too bad ive never logged in to find a monster killing me.

**Comment by bookerthegeek** [comment]
Seems more of "what you think is good for you" then what is good for the pack. Variety is good,  even if you don't use them.

**Comment by ozhound** [comment]
optimizing the pack is our priority, it has grown to a point where lots of people are having problems running it. Nothing is taken out that would affect the majority of the community. The age old saying comes to mind here. "You can't please everyone"
