### ISSUE TITLE
Malisis Doors: Shift clicking an item into or out of the Door Factory causes a crash.

### ISSUE THREAD

**Issue by Uphio** [whatthedrunk/allthemods#270]
What happens: _Client crash upon shift-clicking anything into or out of a Door Factory._

Steps to reproduce: 
1. Pick an item, any item. 
2. Attempt to Shift-Click the item into or out of the Door Factory. Crash happens upon click.

Version of All the Mods: **v1.41**

**Comment by Boomflex** [comment]
@Uphio you are better messaging the Mod author on this one as it is not because of the pack, it is an error with the mod itself.

**Comment by Boomflex** [comment]
@Uphio The dev has been made aware

https://github.com/Ordinastie/MalisisDoors/issues/109

**Comment by DnTheMn** [comment]
https://github.com/whatthedrunk/allthemods/issues/248 dupliciate
