### ISSUE TITLE
Crafting Conflict: Super Circuit Maker Unplayable

### ISSUE THREAD

**Issue by MitoniKatsu** [whatthedrunk/allthemods#271]
Issue Description: Cant craft tiny redstone dust for Super Circuit Maker

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: 1 redstone dust shapelessly crafts to 4 small piles of redstone dust from substratum instead of 9 tiny piles of redstone dust from super circuit maker. This makes the Super Circuit Maker mod unplayable

What you expected to happen:

Steps to reproduce:

1. 1 redstone dust in any crafting grid
2.
3.
...

Version of All the Mods: 1.42

Added mods (Optifine, Fastcraft, etc.):

1.
2.
3.
...

**Comment by whatthedrunk** [comment]
I will take a look at this later for a better solution but you should be able to press that little arrow in your crafting grid to see other outputs. http://i.imgur.com/LUBCiMr.png

**Comment by whatthedrunk** [comment]
Pushed a small update to fix it.
