### ISSUE TITLE
can't craft amor plus tools

### ISSUE THREAD

**Issue by DaFuJosh** [whatthedrunk/allthemods#272]
Issue Description:

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:

What you expected to happen:

Steps to reproduce:

1.not showing recipes 
2.not able to craft tools
3.
...

Version of All the Mods:

Added mods (Optifine, Fastcraft, etc.):

1.optifine HD U D1
2.
3.
...

**Comment by DnTheMn** [comment]
you have to use the armor forge and advanced armor forge
