### ISSUE TITLE
crafting conflict : Pams Harvestcraft Saucepan and an architecture craft item [1.40b]

### ISSUE THREAD

**Issue by DietmarKrause** [whatthedrunk/allthemods#276]
Issue Description:
On server play (Raphys server) you cannot build Pans Saucepan out of copper, JEI provides this recipe put it cannot be crafted. The alternative of iron leads to an item from architecturecraft instead of the saucepan. Raphys server has 1.40b as All the mods version. 
Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:

What you expected to happen:

Steps to reproduce:

1.
2.
3.
...

Version of All the Mods:

Added mods (Optifine, Fastcraft, etc.):

1.
2.
3.
...

**Comment by ozhound** [comment]
This works fine. The saucepan cannot be made from copper.

Please update to the latest version.

![image](https://cloud.githubusercontent.com/assets/3649237/20098826/a1d854ee-a5f0-11e6-8bf7-7cdb50d20e69.png)

**Comment by DietmarKrause** [comment]
either i am wrong or the recipe has changed somehow or was broken in the old version. Now it is working in 1.42 of the modpack . Thank you
