### ISSUE TITLE
[1.42b] Crashes when connecting to server

### ISSUE THREAD

**Issue by hjertis** [whatthedrunk/allthemods#277]
Issue Description: Game crashes when trying to connect to server

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: World starts to load in then crashes back to desktop.

What you expected to happen: I just wanted to play a little before work! :(

Steps to reproduce:

1. Start game
2. Try to connect to server
3. Cry when game crashes

Version of All the Mods: 1.42b

Added mods (Optifine, Fastcraft, etc.):

1. OptiFine 1.10.2 HD U D2

Crashlog attached
http://pastebin.com/kEEMCUpc

**Comment by ozhound** [comment]
You are using the Curse Native Java Launcher. Please try using the Jar Launcher as indicated in the images below

If nothing appears under the JAVA Version in the second picture, you need to install 64bit java. 
![image](https://cloud.githubusercontent.com/assets/3649237/20098208/a0993b14-a5ed-11e6-82ac-25569846dabd.png)
![image](https://cloud.githubusercontent.com/assets/3649237/20098243/dcb2d02e-a5ed-11e6-85e6-fe8aad848606.png)
