### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by brodycas3** [whatthedrunk/allthemods#279]
Could you possible look into adding these mods?

Mo Creatures - https://minecraft.curseforge.com/projects/mo-creatures
Better Achievements - Must have - https://minecraft.curseforge.com/projects/betterachievements
Mo' Villages - https://minecraft.curseforge.com/projects/mo-villages
Ding - https://minecraft.curseforge.com/projects/ding

Please look over these mods and think about adding them. Especially Better Achievements thats a must have. BTW I love this pack keep up the good work.

**Comment by bookerthegeek** [comment]
Out of those, the only one I think is must have is ding, very useful.

**Comment by brodycas3** [comment]
Yes ding and Better Achievements.

**Comment by DnTheMn** [comment]
is better achievements and ding not client side so it dosent matter of you add them client side

**Comment by DnTheMn** [comment]
please use https://github.com/whatthedrunk/allthemods/issues/173
