### ISSUE TITLE
Client-side crash to desktop when attempting to break Mekanism Logistical Transporters and Universal Cables

### ISSUE THREAD

**Issue by Daidez** [whatthedrunk/allthemods#280]
Mekanism Logistical Transporters and Universal Cables causes client-side crashes when attempting to break them.

Reproducible by attempting to break either of the aforementioned blocks. 100% Failure rate on every attempt.

Villagebox, Project-E, Xaero's Minimap + Xaero's Worldmap, and Sound Filters have been added to mods. Issue persists with or without BetterFPS installed.

According to recently-reported issues on the official Mekanism and MCmultipart repositories, it is related to Mekanism's cooperation with MCMultiPart 1.3.0. --Issue is not present with MCMultiPart 1.2.1 installed in the place of MCMultiPart 1.3.0.

AllTheMods 1.42b

Related crash report: [crash-2016-11-08_23.40.09-client.txt](https://github.com/whatthedrunk/allthemods/files/580047/crash-2016-11-08_23.40.09-client.txt)

Related MCmultipart issue: amadornes/MCMultiPart#58

**Comment by DnTheMn** [comment]
use the configurator in wrench mode you'll have to change the mode in controls ill kep this open for now until its fixed but there is a work around

**Comment by Daidez** [comment]
> use the configurator in wrench mode you'll have to change the mode in controls ill kep this open for now until its fixed but there is a work around

Thanks for the tip! Unless I start having issues, I think I'll use MCMultiPart 1.2.1 for the time being.

**Comment by DnTheMn** [comment]
oh. can you not load your world or join a server is so just get mc edit and replace the cable or pipe with dirt or something

**Comment by Daidez** [comment]
> oh. can you not load your world or join a server is so just get mc edit and replace the cable or pipe with dirt or something

Everything will work fine with MCMultiPart 1.3.0 installed unless you try to break a Universal Cable or Logistical Transporter... In which case it causes a client crash. (I know this because I am playing on a private server, and am managing it myself. --the server remains running after the crash.)

So for now, I'll use MCMultiPart 1.2.1 until they release a fix for 1.3.0.

**Comment by RealGrep** [comment]
A custom version can be built to fix this until Aidan fixes it. Here's the pull request that fixes it: https://github.com/aidancbrady/Mekanism/pull/3967
