### ISSUE TITLE
[Expert] Black Quartz AIOT works as Iron-level tool, when it should only be stone-level

### ISSUE THREAD

**Issue by saors** [whatthedrunk/allthemods#283]
Issue Description: see title

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: Black quartz AIOT works as iron-level tool and can mine lapiz, gold, diamond, and more, skipping much progress.

What you expected to happen: expected it not to work

Steps to reproduce:

1. create black quartz AIOT
2. mine at iron-level
3.
...

Version of All the Mods: 0.72

Added mods (Optifine, Fastcraft, etc.):

1. Otpifine
2.
3.
...

**Comment by al132** [comment]
It looks like you're talking about expert mode. I will address this in the next update.
