### ISSUE TITLE
ATM Expert : Immersive engineering wire and early game RF transfer/tech progression

### ISSUE THREAD

**Issue by Waisse** [whatthedrunk/allthemods#284]
LV wire are crafted with ic2 copper cable (IE copper wire have no uses). Yet MV and HV wire uses IE wire to craft. Why ? That make IE gated behind ic2 for no apparent reason.

At the same tech progression (coke oven + smeltery), you can have Actually Additions lasers for RF transfer : wireless, 16 block range, and transfer RF on all adjacent blocks. There's also easy coal gen/crusher/RF furnace available at this point, rendering IE absolutely useless with ic2 gating.

My suggestion is removing oredict for wire/cable and let the player choose its progression path, either ic2 or IE. And maybe gate some Actually Additions stuff further down the line, else nobody will use it,  like make crafting ingredients with IE crusher/squeezer/ Arc furnace.

**Comment by al132** [comment]
This has more or less been taken care of since an update or two ago.
