### ISSUE TITLE
[1.44][ATM Normal] Frequent, random FOV changes.

### ISSUE THREAD

**Issue by GTD-Carthage** [whatthedrunk/allthemods#286]
Issue Description:

Sudden FOV changes occur at random intervals throughout regular gameplay.

What happens:

While playing the game normally, there are instances FOV suddenly narrows down slightly without any discernible cause. The FOV restores seconds later. While it does not hinder gameplay, it is extremely disorienting.

Steps to reproduce:

- Not sure, really - it simply happens at random, without any seeming cause, although I feel it is most prominent when in the underground levels.

Version of All the Mods:
v1.44 (problem has been there since previous version, the one I first began playing)

Optifine 1.10.2_HD_U_2 is the only non-ATM mod installed alongside.

Currentlt running the Ebin-Shaders shaderpack.

**Comment by GTD-Carthage** [comment]
I have apparently found out that this may be linked to Optifine's shader code implementation and has more to do with it than All the Mods has, and a user has hinted this may have something to do with Optifine's shader code possibly wrongly reading slowness status effects. Nevertheless, I have never experienced this issue before, as I had previously been playing with shaders over FTB Infinity Evolved. (shader performance there is awful, but is now great-performing with 1.10.2)

**Comment by Notawallplan** [comment]
Try turning off dynamic fov under details.

**Comment by whatthedrunk** [comment]
I haven't noticed this for a while now, let me know if we should reopen.
