### ISSUE TITLE
Bug with tanks in v1.30 of Deep Resonance

### ISSUE THREAD

**Issue by jonathan-ng** [whatthedrunk/allthemods#288]
Issue Description:

Same issue described [here](https://github.com/McJty/DeepResonance/issues/137). Tanks not accepting RCL liquid when some is already present. Issue with current version (1.3.0) of Deep Resonance. Temp solution of rolling back to previous version of Deep Resonance and Elecore fixes this.

Version of All the Mods: 1.10.2 1.44

**Comment by al132** [comment]
Fixed in Deep Resonance v1.3.1 over a month ago, closing.
