### ISSUE TITLE
[1.10.2] Mekanism cardboard box

### ISSUE THREAD

**Issue by aard2** [whatthedrunk/allthemods#29]
(1.10.2) Using a Mekanism cardboard box to move a Quark chest does not preserve the chest inventory, and does not correctly re-place the chest. Using the cardboard box on a vanilla chest works correctly.

**Comment by jmcaffee** [comment]
I wrapped a trash can (accidentally) and was not able to unwrap the trash can. Sneak right-clicking simply placed the cardboard box back into the world.

**Comment by Carrots4U** [comment]
Fixed in next update
