### ISSUE TITLE
Crash when looking at Ember's Copper Cell

### ISSUE THREAD

**Issue by RoyAwesome** [whatthedrunk/allthemods#290]
Issue Description:

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: When I look at the copper cell, it crashes

What you expected to happen: it not to crash

Steps to reproduce:

1. Place Copper Cell
2. Look at it, then hit Shift
3. Crash
...

Version of All the Mods: ATM Expert v0.77

Added mods (Optifine, Fastcraft, etc.):

1. Optifine

Crash Report: 

[crash-2016-11-20_02.38.51-client.txt](https://github.com/whatthedrunk/allthemods/files/601965/crash-2016-11-20_02.38.51-client.txt)

**Comment by RoyAwesome** [comment]
It appears hitting sneak is a requirement for the crash.

**Comment by al132** [comment]
Looks like the issue has been addressed. Closing.
