### ISSUE TITLE
ATM 1.46 - Gaia 2 Fight crashes client

### ISSUE THREAD

**Issue by SephirothWS** [whatthedrunk/allthemods#291]
Issue Description: This issue is a bit of an interesting one. Sometimes (Not all the time) while playing on a multi-player server, summoning Gaia 2 from Botania causes a client crash for those nearby. Server does -not- crash and continues operating normally.

What happens: Gaia ingot is used up, Gaia 2 spawns, begins attacking the player, player crashes out with the following crash report: https://gist.github.com/SephirothWS/0172a86da58fed5b2d39adaf4de93296

I originally thought this was an issue with Botania itself, so I created a report here: https://github.com/Vazkii/Botania/issues/2044 Got redirected to https://github.com/Vazkii/Botania/issues/2024 which mentions that something in the pack may be modifying something it shouldn't be modifying.

What you expected to happen: Gaia ingot is used up, Gaia 2 spawns, begins attacking the player, but the player can actually fight back because no client crash.

Steps to reproduce:

1. Craft a Gaia Ingot
2. Summon the Guardian of Gaia 2 via right-clicking a beacon in the proper arena to summon the boss.
3. Watch as the Guardian of Gaia 2 spawns in.
4. Crash once it begins attacking you.

Version of All the Mods: 1.46

Added mods (Optifine, Fastcraft, etc.):

1. Chat Tweaks (1.10.2, v. 4.1.6)
2. Builder's Guides (1.10.2, v. 1.0.2)
3. Chance Cubes (1.10.2, v. 2.3.2.131)
4. DiscordIntegration (1.10.2, v.2.1.0)
...

**Comment by SephirothWS** [comment]
@whatthedrunk Why was this closed?

**Comment by whatthedrunk** [comment]
I cannot duplicate the issue. http://imgur.com/a/IgKLD
