### ISSUE TITLE
REQUEST: Add "Malisis Blocks

### ISSUE THREAD

**Issue by ArroganTz** [whatthedrunk/allthemods#292]
@whatthedrunk @pobiega @ozhound @Carrots4U @goosezilla 
I started playing around with Malisis and went to Youtube for several tutorial videos/ideas what to do with it. I saw items like the "player sensor" or "vanishing frames" that i couldnt find ingame so i googled for it. Seems like they are packed into another mod called "Malisis Blocks". Since you added the "Malisis Doors" mod i thought this one would be a great addition.
You can find the mod here:

[http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2558284-malisisblocks-1-10-2-4-1-2-19-10-2016](url)

**Comment by whatthedrunk** [comment]
Added to https://github.com/whatthedrunk/allthemods/issues/173 for a later review
