### ISSUE TITLE
Any version past 1.38b takes 20 - 25 mins on step 7/7 Texture uploading and mipmap

### ISSUE THREAD

**Issue by HotdogDaddy** [whatthedrunk/allthemods#293]
Issue Description:
Any version past 1.38b takes 20 - 25 mins on step 7/7 Texture uploading and mipmap

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:
Since updating past forge 12.18.2.2107 when my laptop gets to step 7/7 Texture uploading and mipmap it takes 20-25 minutes to finish that step. 

What you expected to happen:
With 1.38b it would take 30 secs

Steps to reproduce:

1.Update to any version of the mod past 1.38b
2.
3.
...

Version of All the Mods:Any version past 1.38b

Added mods (Optifine, Fastcraft, etc.):

1.
2.
3.
...

**Comment by bookerthegeek** [comment]
Please delete the instance, reinstall the instance, and upload all the logs the ghist and paste them here.

**Comment by HotdogDaddy** [comment]
Laptop was using Intel HD GPU instead of the Geforce 940M. The small update to forge for some reason after 2110 runs really slow with the Intel but thanks to issue I switched from auto selecting the GPU to always using the Geforce.
