### ISSUE TITLE
Super Circuit Maker Recipe Conflict

### ISSUE THREAD

**Issue by Hirsu** [whatthedrunk/allthemods#296]
Issue Description:

What happens:

To make a tiny pile of glowing redstone, you need a tiny pile of glowstone. According to JEI, if you put a piece of glowstone in a crafting table, it should give you 4 tiny piles of glowstone. Instead, you get 4 small piles of glowstone dust from substratum. Those can not be used in the SCM recipe.

What you expected to happen:

1 Glowstone -> 4 tiny piles of glowstone dust

Version of All the Mods: v1.47

Added mods (Optifine, Fastcraft, etc.):

1. Nature's Compass
2. Login Shield
3. Literal Ascension ( + dependencies)
4. Akashic Tome
5. Neat
6. Dynamic Surroundings Unofficial
7. Sound Cap
8. Sound Filters
9. Optifine

Removed mods:

1. Infernal Mobs

**Comment by whatthedrunk** [comment]
There should be a little arrow in the crafting grid to switch around recipes with conflicts but when I get back from vacation I will push an update to make SSM be the default one like I did with redstone. Thanks.

**Comment by Hirsu** [comment]
I had no idea what purpose that arrow served! Thanks for the tip :)
