### ISSUE TITLE
v1.46 and 1.47 magically disappeared off CurseForge

### ISSUE THREAD

**Issue by SephirothWS** [whatthedrunk/allthemods#297]
Issue Description: See title

Two releases of ATM vanished off CurseForge, and a server I play on was in the process of updating to v1.47 during the (brief?) time it was out.

**Comment by whatthedrunk** [comment]
Curse is having issues at the moment, they should be back up soon.

**Comment by SephirothWS** [comment]
I see, thank you sir.
