### ISSUE TITLE
extrautil2 solar panel

### ISSUE THREAD

**Issue by grazazel** [whatthedrunk/allthemods#3]
Seems to be that if you try to place extrautil2 solar panel on chiselled block it crashes the client
Here is pastebin with the crash log for it.  solar placed ok on normal cobble
[http://pastebin.com/UR55cwAt](url)

**Comment by whatthedrunk** [comment]
I will look at this tonight. Does it crash the server or let you log back in? If it lets you log back in, is the Solar placed? Thanks.

**Comment by grazazel** [comment]
doesn't crash the server i don't think just the client, solar wasn't placed when I logged back in and placed fine on non chisel block

**Comment by whatthedrunk** [comment]
Hopefully the new Version of Chisel fixes this tonight. Expect another update later today.

**Comment by whatthedrunk** [comment]
Have you tried with the new update?
