### ISSUE TITLE
[1.10.2] Mobs wielding Mekanism Weapons

### ISSUE THREAD

**Issue by Spectrekillol** [whatthedrunk/allthemods#30]
When a zombie holds a weapon from Mekanism it holds it in the form of an item. See the screenshot below.
![2016-07-09_20 45 25](https://cloud.githubusercontent.com/assets/15530949/16707562/5fd8e6c4-4616-11e6-98fa-3ee09058358d.png)

**Comment by Carrots4U** [comment]
Seems fixed in the latest version.
