### ISSUE TITLE
Jump Cushion Crash

### ISSUE THREAD

**Issue by BeardlessBrady** [whatthedrunk/allthemods#304]
Issue Description: When placing a 'Jump Cushion' from immersive engineering, client crashes.

What happens: Crashes when placing 'Jump Cushion'

What you expected to happen: Not to crash

Steps to reproduce:

1. Spawn a Jump Cushion
2. Place it
3. Crash
...

Version of All the Mods: 1.0.0 and 1.0.1

Added mods (Optifine, Fastcraft, etc.): None, Fresh Version

Crash Log: [Here](http://pastebin.com/fU92B8NZ)

**Comment by al132** [comment]
Closing, this issue was fixed two updates ago
https://minecraft.curseforge.com/projects/immersive-engineering/files/2351015
