### ISSUE TITLE
[Expert] Add AbyssalCraft Integration

### ISSUE THREAD

**Issue by Shinoow** [whatthedrunk/allthemods#305]
Hey, developer of AbyssalCraft here.
Noticed that the "Expert mode" version of All The Mods didn't have AbyssalCraft Integration, which could be a good addition since it allows more modification through MineTweaker (among other things), so adding that to the pack would allow you to change things regarding AbyssalCraft on a deeper level.
The mod can be found over at https://minecraft.curseforge.com/projects/abyssalcraft-integration

**Comment by al132** [comment]
Hey, I had foolishly assumed that it was no longer compatible or that it would be buggy since it hadn't updated since June, even though Abyssalcraft had been updated many times since. I will take a look, thanks. If you're playing the pack I hope you're enjoying it.

**Comment by Shinoow** [comment]
The 1.9.4 version is forwards compatible with 1.10.2, which is why I haven't released any updates for it, since everything has been working accordingly.

**Comment by Wubbbi** [comment]
@al132 The mod just updated some days ago to be compatible with the current version of abyssalCraft! I really would like to see this mod in the pack <3

Greetings

**Comment by al132** [comment]
Closing this, combining with #327
