### ISSUE TITLE
[FULL][1.48] Chisel Generating Huge Log Entries, Killing Performance

### ISSUE THREAD

**Issue by AJ-AllTheMods** [whatthedrunk/allthemods#306]
Issue Description:

Chisel Generating Huge Log Entries, Killing Performance.

What happens:

When rendering a 'chiseled' Factory block that has been placed into the world, multiple lines are periodically written to the log file "fml-client-latest.log" for each chiselled block that is being rendered.  This severely impacts performance causing stuttering, severe frame drops and sometimes complete lock-up.   Also has the effect of filling disk space, I have seen approx 1-2MB/s being written at times.

May also be caused by other blocks, but first observed issue with Factory blocks and have been able to reproduce the issue with them.

What you expected to happen:

Log entries not to be written.

Steps to reproduce:

1. Load a world, either single or multiplayer.
2. Obtain a Diamond Chisel and a Factory block from the 'Chisel' mod.
3. Chisel the block and place it down.
4. Open file "Instances\All the Mods\logs\fml-client-latest.log"
5. Observe log entries being written as shown in images below.

1 FPS!
![2016-11-29_05 49 02](https://cloud.githubusercontent.com/assets/24242986/20701009/904b6a36-b608-11e6-8fc3-c9a2d4e033a7.png)

Entries generated during screenshot above:
![realworld](https://cloud.githubusercontent.com/assets/24242986/20701433/de20e838-b60a-11e6-8287-5c29595dec85.PNG)

Entries generated during test:
![chisel2](https://cloud.githubusercontent.com/assets/24242986/20701098/fb2b727e-b608-11e6-8d38-47d4ae89861a.png)

Version of All the Mods:

Added mods (Optifine, Fastcraft, etc.):

1. Initially had BetterFPS-1.3.2 installed in screenshot above
 but removed to test, issue still present without BetterFPS.

**Comment by SephirothWS** [comment]
Update chisel to 0.0.7.5, 0.0.7.4 which v1.48 has .. has this problem.

**Comment by AJ-AllTheMods** [comment]
Confirmed, issue is resolved in 1.48B
