### ISSUE TITLE
[1.10.2 v0.8] Abyssalcraft coralium transmutation non-tin ores into abyssal tin

### ISSUE THREAD

**Issue by CvoidWyvern** [whatthedrunk/allthemods#31]
Abyssalcraft coralium turns copper ore (any type other than abyssal), appetite ore, industrialcraft lead and uranium ore, osmium ore, and any substratum ore excluding nether ores into abyssal tin ore instead of it's respective abyssal ore (if one exists).  Tin ores still yield abyssal tin ore as expected.  From the looks of it this only affects mods that add tin ore.

**Comment by Carrots4U** [comment]
Fixed in the next Update.
