### ISSUE TITLE
ATM expert can't be running with Spongeforge 

### ISSUE THREAD

**Issue by Cavesnakes** [whatthedrunk/allthemods#313]
Issue Description: One or more of the ATM expert's coremod breaks down Spongeforge

[Note]
ATM expert version: 1.4
Spongeforge version: spongeforge-1.10.2-2171-5.1.0-BETA-1957 (I've updated forge mod to meet with spongeforge version)

What happens:
Modpack's coremod breaks down Spongeforge 

Full log: http://pastebin.com/VG9rRFyL

What you expected to happen:
I want to run ATM experts with Spongeforge for better server administration

**Comment by al132** [comment]
I really don't think I can help you with this unfortunately. I can't discern which mod(s) cause(s) the problem, and even if I could it's very unlikely that I would remove any mods to fix sponge compatibility unless the mod was relatively trivial.

**Comment by bookerthegeek** [comment]
AE2 had some issues unless your running the unofficial patch version,  or they updated. 

You should report this to sponge of it is a different mod causing the issue.

**Comment by Cavesnakes** [comment]
appliedenergistics2-rv4-alpha-7 is source of problem

If someone is willing to use spongeforge with this modpack

use AE2-rv4-alpha 8 build

thanks for bookerthegeet :D

**Comment by al132** [comment]
I have decided i'm not going to try to support sponge.

**Comment by bookerthegeek** [comment]
Makes sense,  as this is a mod issue that is not fixable by pack authors unless you remove that mod in question.
