### ISSUE TITLE
[BUG] Green Gold recipe makes Rose Gold

### ISSUE THREAD

**Issue by tjsd** [whatthedrunk/allthemods#314]
Issue Description:
In JEI it shows Gold, Silver, Copper, Cadmium in the Metal Alloyer should make green gold, but I only get Rose Gold.

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:
You insert the dusts listed in JEI in the correct order and out comes Rose Gold ingots.

What you expected to happen:
Green Gold Ingots

Steps to reproduce:

1. Put 5 gold dust, 2 silver dust, 1 copper dust and 1 cadmium dust in the Metal Alloyer
2. Wait for it to finish making it
3. Look horrified at the result that is Rose Gold ingots, gold being so rare and you just wanted green gold to make the Farmer from Actually Additions.
4. Despair

Version of All the Mods:
v1.0.5 Expert
Added mods (Optifine, Fastcraft, etc.):

1. none
2.
3.
...

**Comment by al132** [comment]
Thanks for the heads up. This should be fixed now, as well as some other potential recipe conflicts in the metal alloyer. If you are playing single player you can download it [here](https://minecraft.curseforge.com/projects/rockhounding-atm-fork/files/2352744) if you don't want to wait until the pack updates.
