### ISSUE TITLE
[Expert] AA Crusher + Copper Ore = Copper Dust

### ISSUE THREAD

**Issue by mike347** [whatthedrunk/allthemods#315]
Issue Description:
If you use the AA Crusher on copper ore, it produces Copper dust.. which can only be used in either the crossroads crucible and a few other places.. but not in a furnace. The dust not smelting is intentional to gate copper behind crossroads.. but I'm thinking the crusher should produce IC2 'Crushed Copper' instead of copper dust. The IC2 Macerator produces 'Crushed Copper' if you crush ore, and 'Copper dust' if you crush copper ingots.. Which seems fitting.

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: Crush Copper ore in the AA Crusher or Double Crusher

What you expected to happen:
Receive crushed copper ore
Steps to reproduce:

1. Mine copper ore
2. Insert into AA Crusher
3. Wait for it
... Receive Copper dust

Version of All the Mods: Latest, on test server.

Added mods (Optifine, Fastcraft, etc.):

1. Optifine

Thanks!
-Qon

**Comment by tjsd** [comment]
I just discovered this as well in v.1.0.6. Leaving me with loads of copper dust that is very hard to turn into ingots.

**Comment by mike347** [comment]
@tjsd Yeah. I ended up setting up my crossroads stuff again temporarily. I feed copper into my ic2 macerator until this is fixed.

**Comment by tjsd** [comment]
The same is true for Osmium Dust. It outputs the Rockhound version that can not be smelted in a furnace.

**Comment by al132** [comment]
The osmium dust is intentional. It is supposed to be smelted in the arc furnace. The copper dust however, I will do something about.

**Comment by al132** [comment]
This has been addressed in ATM:E 1.0.7
