### ISSUE TITLE
[LATEST][Normal] Game not loading

### ISSUE THREAD

**Issue by luqmannul** [whatthedrunk/allthemods#317]
Issue Description:

Game is not loading past forge initialization modelloader screen

Steps to reproduce:

Launch the game from ANY Launcher (I used MultiMC to generate logs)

Added mods :

1.Optifine 
2.BetterHUD

[LOG](http://pastebin.com/TkjKz3uw)

**Comment by tukib** [comment]
The current version of forge is not compatible with the version of optifine you are using

**Comment by luqmannul** [comment]
Wait a sec i'll test that.

**Comment by luqmannul** [comment]
Thanks. It works now. (Why Optifine...)
