### ISSUE TITLE
Bug with ATM Rockhounding 

### ISSUE THREAD

**Issue by tjsd** [whatthedrunk/allthemods#318]
Issue Description: Not sure to post here or find different github for rockhounding.
The issue is, if you have any Compound in the machine and rotate the machine with a wrench it deletes the compound bottles. Just tested with liquids, it doesnt keep anything in inventory when rotating, even the power goes away.

What happens:
You use the Lab Oven to make any of the acids, if you right click the lab oven with a wrench the machines rotates. But everything inside just goes poof.

What you expected to happen:
My stuff to still be inside the machine when rotating.

Steps to reproduce:

1. Place a Lab Oven, make something in it
2. Rotate the Lab Oven by right clicking iwth a ic2 wrench or IE hammer
3. Open up the GUI, everything is gone like magic.
...

Version of All the Mods:
v1.0.6

Added mods (Optifine, Fastcraft, etc.):

1. optifine
2.
3.
...

**Comment by al132** [comment]
Fixed in [ATM Rockhounding - v1.1.14](https://minecraft.curseforge.com/projects/rockhounding-atm-fork/files/2354881), will be in the next pack update.
