### ISSUE TITLE
[Expert] Botania gated behind apiary, which is gated behind botania.

### ISSUE THREAD

**Issue by mike347** [whatthedrunk/allthemods#319]
Issue Description:
Recent update changed the recipe for apiaries to require living wood, which requires botania.
Botania floral fertilizer, which is required to start Botania, is gated behind apiaries (in the form of needing pollen.

Perhaps instead of living wood, use creosote wood which would be available at the tech level you need
botania for. You could also consider adding another recipe for floral fertilizer that uses chrous fruit instead of pollen, which is fairly hard to get as well but at least it's not impossible as living wood currently is.

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:
I can't start Botania.

What you expected to happen:
I can start Botania.

Steps to reproduce:

1. Look at recipe for floral fertilizer.
2. Look at recipe for apiary.
3. Shake head.
... What the drunk?

Version of All the Mods:
Latest ( on test server)
Added mods (Optifine, Fastcraft, etc.):

1. Optifine
2.
3.
...

**Comment by goosezilla** [comment]
You don't need apiaries to get pollen. Either trade with villagers, break wintry hives with a scoop or use bee houses which only require treated wood and frames.

**Comment by mike347** [comment]
Thanks. I missed that bee houses can make the combs too. Duh on my part. :)
