### ISSUE TITLE
[1.10.02 v7] - Morph-o-Tool Crash

### ISSUE THREAD

**Issue by ozhound** [whatthedrunk/allthemods#32]
After loading several wrenches, when you look at a machine that causes the tool to morph, the client gets kicked from the server. Note that the Client does not Crash to Desktop

**Comment by Carrots4U** [comment]
Is it still happening? I can't seem to get to happen to me.

**Comment by ozhound** [comment]
ill try it again today

**Comment by ozhound** [comment]
The first thing i did was load a wand of the forrest into it and looked at
a pedistal and it crashed

**Comment by whatthedrunk** [comment]
we just updated it, let me know if its still causing problems

**Comment by ozhound** [comment]
works great, supports the yeta wrench now

**Comment by ozhound** [comment]
so I client crashed (not related to the tool) after I configured the tool
with a few wrenches and it changed permanently into the laser wrench. This
was the last active wrench.

**Comment by Carrots4U** [comment]
I'm not sure I'm understanding what the new bug is. Mind elaborating a bit?

**Comment by ozhound** [comment]
never mind. it seems that it was a once of and a perfect storm situation
where my client crashed during the session that i created the morph-o-tool.
i suspect if i had exited the session correctly it wouldnt have "stuck" on
the last tool i was using.

in any event it hasnt happened again.

**Comment by Carrots4U** [comment]
Okay if it becomes are reoccurring problem, reopen this :)
