### ISSUE TITLE
[Expert] Add support for Chisel raw stones on Forestry's Digger's Backpack

### ISSUE THREAD

**Issue by starg09** [whatthedrunk/allthemods#320]
~~Currently Alabaster and Basalt seem to not get sucked into the backpack, as of version 1.0.6 of ATM:Expert. Being common stones found underground, it probably would be useful if they were sucked into it. ~~ **EDIT:** My bad, it was the Basalt from chisel. Stones from Environmental work as intended. Read what I added below.

Chisel's plain marble and limestone would also be good to have doing the same, just as vanilla dirt is sucked but not the chiseled one (that one goes to the builder's backpack). **EDIT AS WELL:** So, the suggestion would be to include chisel's raw basalt, marble and limestone to the digger's backpacks :P

**Comment by al132** [comment]
Will be in the next version
