### ISSUE TITLE
ATM:E - IC2 spam and bug

### ISSUE THREAD

**Issue by tjsd** [whatthedrunk/allthemods#321]
Issue Description:
Often when I log in the IC2 machines wont recive energy from my coal generator. I have to break and replace the the generator and machines. This results in the server console endless spamming the message:
[12:51:59] [Server thread/INFO] [IC2.EnergyNet]: No tile found for ic2.core.block.comp.Energy$EnergyNetDelegate@772b4041 at dim 0: -111/62/152.

And only way to stop this is stopping and starting the server. My guess this has something to do with forge/ic2/ftb chunkloading.

What happens:
Sometimes IC2 machines does not recieve power from generator, have to break and replace them

What you expected to happen:
Machines to recieve power from coal generator

Steps to reproduce:

1. Place down a coal generator with coal in and a macerator
2. Chunkload your chunks with FTB Utilities
3. Go far away from your loaded chunks and look at the console output
.
...

Version of All the Mods:
v1.0.6
Added mods (Optifine, Fastcraft, etc.):

1. Server: None
2. Client: Optifine
3.
...

**Comment by Meller127** [comment]
This is fixed in the leatest build of Ic2
- 0002021: [E-Net, cabling, storage/transformer blocks] Console Flood IC2 "No tile found" (Aroma1997) - resolved.

@al132 Maybe time to grab the leatest jenkins from Ic2, 40issues resolved.

**Comment by al132** [comment]
IC2 put a new release out on curse today, should be fixed on next pack update

**Comment by al132** [comment]
The pack is now updated, you can reply to this if you are still having problems
