### ISSUE TITLE
Items not rendering properly

### ISSUE THREAD

**Issue by SummaryPick** [whatthedrunk/allthemods#322]
Issue Description: Some items are not rendering properly. (i.e. Ruby axe operates the way it is supposed to, degrades like usual, the only issue is that instead of being a ruby axe in my hand its a 2D black box).  I am on a Mac.

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:

What you expected to happen:

Steps to reproduce:

1.
2.
3.
...

Version of All the Mods: allthemods 1.10.2 v1.50

Added mods (Optifine, Fastcraft, etc.):
None.
1.
2.
3.
...

**Comment by whatthedrunk** [comment]
Will need more info if this is still happening.
