### ISSUE TITLE
Expert - Recipie Bug - Sunny Quartz

### ISSUE THREAD

**Issue by tjsd** [whatthedrunk/allthemods#324]
Issue Description:
In JEI it says to use atomc reconstructor from AA to make nether quartz into sunny quartz. But nothing happens when you do that

What happens:
You drop netherquartz infront of the recontructor and it fires of the laser but nothing happens to the quartz.

What you expected to happen:
That it would turn into sunny quartz.

Steps to reproduce:

1. Place down atomic recontstructor and power it
2. Drop nether quartz where the beam hits an obstacle
3. Pick up quartz and discover its still nether quartz
...

Version of All the Mods:
v1.0.8

Added mods (Optifine, Fastcraft, etc.):

1. Optifine
2.
3.
...

**Comment by Meller127** [comment]
Do you have atleast 151.000 RF in your Reconstructor?
Just tested in my World on 1.0.8 and no problems

**Comment by tjsd** [comment]
yup, I was not paying attention to the power requirement. After making sure the reconstructor was fully powered I managed to convert 1 piece.
