### ISSUE TITLE
Expert - Apocalyptic bee ghast tear

### ISSUE THREAD

**Issue by Meller127** [whatthedrunk/allthemods#325]
The Apocalyptic bee sahll produce ghast tears, JEI even links to it.

What you expected to happen:
Produce ghast tear from the bee

Steps to reproduce:
1. Search for ghast tear and show Bee produce

Version of All the Mods: 1.0.8
Added mods (Optifine, Fastcraft, etc.):

1. Optifine

**Comment by MigukNamja** [comment]
I just bred this bee and didn't get a Ghast Tear for a while, but I eventually got one.

It's true that JEI matches the Apocalyptic Bee when you search for what makes a Ghast Tear and then doesn't show the bee actually producing it, but I think it's a JEI-only thing. The [source code](https://github.com/Lach01298/MoreBees/blob/e70f1bc8b8addfc9cf6e00eb8c9306b5e5af5fce/src/main/java/lach_01298/moreBees/Genetics/BeeSpecies.java) for MoreBees looks correct:

beeSpecies.addProduct(PluginApiculture.items.beeComb.get(EnumHoneyComb.SIMMERING, 1), 0.30f).addProduct(new ItemStack(Items.BLAZE_POWDER), 0.2f).addProduct(new ItemStack(Items.GUNPOWDER), 0.2f).addProduct(new **ItemStack(Items.GHAST_TEAR), 0.05f**).setTemperature(EnumTemperature.HELLISH).setHumidity(EnumHumidity.ARID);

...and my game did indeed produce a Ghast Tear. Note the drop rate is very, very low (bolded above).

**Comment by al132** [comment]
In that case I will close this issue.
