### ISSUE TITLE
Expert - Suggestion - Prismarine shard

### ISSUE THREAD

**Issue by tjsd** [whatthedrunk/allthemods#326]
Issue Description:
Prismarine shards is only obtainable trough killing the temple fishes or go deep into bees. I suggest adding a alchemy catalyst recipie or maybe netherquartz + fish in alloy smelter. That would push it a good way into the pack and not break any progression.

**Comment by Meller127** [comment]
Just take a Guardian in a soul vial and spawn them over punji sticks.. Prismarin shards in the millions

**Comment by al132** [comment]
An update or two ago I added a recipe to the Molecular Transformer, alternatively you can do something similar to what Meller suggests. Closing.
