### ISSUE TITLE
[Expert] All mod suggestions

### ISSUE THREAD

**Issue by al132** [whatthedrunk/allthemods#327]
Here are all the mods that have been suggested for the pack, feel free to suggest more.

[Refraction](https://mods.curse.com/mc-mods/minecraft/253578-refraction)
[Totemic](https://minecraft.curseforge.com/projects/totemic)
[Better With Mods](https://minecraft.curseforge.com/projects/better-with-mods)
[Abyssalcraft Integration](https://mods.curse.com/mc-mods/minecraft/234851-abyssalcraft-integration)
[Agricraft](https://minecraft.curseforge.com/projects/agricraft)
[Simple Void World](https://mods.curse.com/mc-mods/minecraft/254466-simple-void-world)
[Mod Name Tooltip](https://minecraft.curseforge.com/projects/mod-name-tooltip)
[ImmersiveCraft](https://minecraft.curseforge.com/projects/immersive-craft)
[Aqua Mundi](https://minecraft.curseforge.com/projects/aqua-munda)
[OpenBlocks Elevator](https://minecraft.curseforge.com/projects/openblocks-elevator)
[Advanced Machines](https://minecraft.curseforge.com/projects/advanced-machines?gameCategorySlug=mc-mods&projectID=251205)
[Vitality](https://minecraft.curseforge.com/projects/vitality)
[Open Glider](https://minecraft.curseforge.com/projects/open-glider)
[Just Enough Dimensions](https://minecraft.curseforge.com/projects/just-enough-dimensions)

**Comment by BuggaNoia** [comment]
OpenBlocks Elevator:
[[https://minecraft.curseforge.com/projects/openblocks-elevator/images](url)
Reason: I hate stairs and ladders as well ;)

**Comment by al132** [comment]
I'm not sure how they compare, but I know RFTools has an elevator.

**Comment by BuggaNoia** [comment]
@al132 direwolf20 uses the RFTools elevator in his current 1.10 LP: It moves a 3x3 section slowly up and down. Not that much useful. He already abandoned to use it.
OpenBlocks Elevators are just space/jump or lshift/sneak to teleport to an other floor. 
But I understand, if you just don't want to clutter the pack a lot of here-an-then / one-trick-pony mods. Was just an idea of me - and yes, I just can add it to my client by my own of course.

**Comment by al132** [comment]
Okay, thanks for explaining the difference. I'll add it to the list at least

**Comment by bird191** [comment]
advanced machines(Add on for ic2) it adds advanced versions of each machine equivalent to the boost the electric furnace gets when upgraded to induction furnace

**Comment by raphydaphy** [comment]
Vitality 😛 

But srsly tho it adds a spell to extract essence from trees, so it can be used very early-game, and another that places torches using the stuff you get from trees, which is good if u don't have optifine or just want moar torches before you get a flint pick for coal.

Also adds more options for combat during early-game, including explosion spell and fireball spells which can be obtained just after killing a few creepers. 

And also adds mid-game way of filling your hunger that bypasses spice of life, which is good once you reach a point where spice of life is just an annoyance and you cant have an environmental controller with you when traveling.

**Comment by ShaunDreclin** [comment]
Posted this one in discord but I think it was missed, would be great to get the computronics addon for opencomputers!
http://wiki.vex.tty.sh/wiki:computronics

**Comment by BuggaNoia** [comment]
Project Red for 1.10 is out now: https://minecraft.curseforge.com/projects/project-red-base

**Comment by Dijkstra1** [comment]
Mob Grinding Utils: https://mods.curse.com/mc-mods/minecraft/254241-mob-grinding-utils
i dont care if disable recipes for everything but the death mufflers, wither killing spawning sounds are getting to me

**Comment by OrdinatorStouff** [comment]
Closing, please use this on the new tracker for further suggestions: https://github.com/AllTheMods/ATM-Expert/issues/7
