### ISSUE TITLE
Agricraft Crash

### ISSUE THREAD

**Issue by Soloun** [whatthedrunk/allthemods#328]
Issue Description: When I try to break a agricraft block, irrigation channel, sprinkler or seed analyser the game crashes

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this. Updated to latest version of the pack which added Agricraft

What happens: Using an Osmium Pick to break seed analyser game crashes as I hit it, bronze axe on a irrigation channel or sprinkler same

What you expected to happen: Block should break

Steps to reproduce:

1. Go to a village with Agricraft stuff
2. Try to break the above blocks
3.
...

Version of All the Mods:

Added mods (Optifine, Fastcraft, etc.):

1. Custom Mob Spawner
2. Mo Creatures
3. Projecte
...

**Comment by bookerthegeek** [comment]
Crash log 

What are you breaking it with?

**Comment by mercsniper** [comment]
http://pastebin.com/Y7t5SCxm

**Comment by mercsniper** [comment]
Open Fist or Pick. Seeds would not grow or mutate. Only weeds and what seemed like 80% reduction in tick rate for seeds growing in crops.

**Comment by bookerthegeek** [comment]
Weird, it is showing two other mods, not agricraft at all.

**Comment by whatthedrunk** [comment]
Mod has been removed from atm until its out of alpha. Sorry about all that mess.
