### ISSUE TITLE
[1.10.2] Oredict Issues

### ISSUE THREAD

**Issue by TheReidMan1** [whatthedrunk/allthemods#33]
When the Ender IO alloy smelter smelts tin or copper dust, the AbyssalCraft versions are created. Same happens with the Ore Converter, copper and tin convert to the AbyssalCraft versions. This is messing up automated ore input into my storage system, as AbyssalCraft ingots do not load into Storage drawers through a drawer controller. Can the Oredict be changed such that the default for copper is Forestry and the default for tin is IC2. (I believe right now the first defined ore is the result of the conversion which is probably why AbyssalCraft is taken as it begins with "a".)

**Comment by Carrots4U** [comment]
Fixed in the next Update
