### ISSUE TITLE
[Suggestion] [Expert] AA Laser Relays

### ISSUE THREAD

**Issue by mike347** [whatthedrunk/allthemods#331]
Currently the AA Laser Relay is prohibitively expensive.. by the time you can make them, they're really not worth much, IMO.

I would like to suggest an alternative recipe to make it more affordable, but still expensive.

R G R
A P A
R M R

4 blocks of restonia, one in each corner. (R)
2 Advaned Coils (A)
1 Printed Circuit board (P)
1 Machine base (M) 
1 Red stained glass pane (G)

If that is acceptable, you will need to make the two higher tiers of laser relays more expensive. Perhaps  using botania lens (think focusing the power) and the AA battery packs to boost the power output.

Anyhow, just a suggestion.
Cheers.

**Comment by al132** [comment]
I got way too carried away with the recipe, so I did make it easier for this next update, but it is still more difficult than what you presented here. Thanks for the suggestion though.
