### ISSUE TITLE
ATM Rockhounding - Missing Carbon values on the different coal types

### ISSUE THREAD

**Issue by tjsd** [whatthedrunk/allthemods#332]
Issue Description:
The different coal types that atm rockhounding produces does not contain carbon values only burntime.
This makes it impossible to use the coals with Advanced Generators (syngass) since it looks for carbon value like coal, charcoal and coal coke has (even wood).

Also, it would be nice if you added sagmill/crusher recepies for crushed coal for those 3 types. Like different ammount depending on burntime/carbon value. You need loads of coal powder to make IC2 armor.

**Comment by al132** [comment]
I have added a decent number of fuels to the advanced generators valid fuel list for the next update. I don't plan on adding any recipes for crushed coal from the rockhounding coals for now. They can all be crafted into coal pellets, which can be crafted into coal.
