### ISSUE TITLE
[Expert] [Bug] [Recipes] Blutonium uncraftable

### ISSUE THREAD

**Issue by Dijkstra1** [whatthedrunk/allthemods#335]
Issue Description:
Blutonium is uncraftabel.

What happens:
The recipe conflicts Cyanite ingot recipe resulting getting a Cyanite ingot and not Blutonium.

What you expected to happen:
For a Blutonium ingot to craft

Steps to reproduce:

1. Make an Arc furnace 
2. Put one Cyanite dust in the main slot and one tiny plutonium in extra spot
3. Curse Al for getting a Cyanite ingot after he "Fixed It"

Version of All the Mods:
1.09 or something (latest as of the 18/12/2016)
Added mods (Optifine, Fastcraft, etc.):

1. Optifine (Does not matter)

**Comment by al132** [comment]
Fixed for real this time in next update
