### ISSUE TITLE
[Expert] [Bug] [Recipe] Track Layer Cart is uncrafable

### ISSUE THREAD

**Issue by Dijkstra1** [whatthedrunk/allthemods#337]
Issue Description:
The track layer cart can not be crafted

Note: Make sure you update to the latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:
Nothing, looks like it down the meta on the crowbars

What you expected to happen:
Item to craft

Steps to reproduce:

1. Put the items in the crafting grid.

Version of All the Mods:
1.09 or something (latest as of the 18/12/2016)

Added mods (Optifine, Fastcraft, etc.):

1. Optifine (Does not matter)

**Comment by al132** [comment]
Fixed in next update
