### ISSUE TITLE
[Expert] [Bug] [Recpice] Track Remover Cart

### ISSUE THREAD

**Issue by Dijkstra1** [whatthedrunk/allthemods#338]
Issue Description:
The track remover cart can not be crafted

Note: Make sure you update to the latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:
Nothing, looks like it down the meta on the crowbars

What you expected to happen:
Item to craft

Steps to reproduce:

Put the items in the crafting grid.
Version of All the Mods:
1.09 or something (latest as of the 18/12/2016)

Added mods (Optifine, Fastcraft, etc.):

Optifine (Does not matter)

**Comment by al132** [comment]
Fixed in next update
