### ISSUE TITLE
Expert - Balance Issue - Nickel

### ISSUE THREAD

**Issue by tjsd** [whatthedrunk/allthemods#339]
Issue Description:
Nickel Ore generates at 
y10 at 0.063%
y19 at 0.031%
y21 at 0.063%

That is the only places it generates and at a horrible low rate. You need nickel to make constantine in many recepies. I suggest you up the generation of it and spread it out at more then 3 y levels.

Version of All the Mods:
v1.0.9

Added mods (Optifine, Fastcraft, etc.):

1. optifine
2.
3.
...

**Comment by al132** [comment]
The height/probability graph in JER isn't an exact science, it's generated from a sampling of a couple dozen chunks and is distributed with the pack. Most likely the ore generates at least from 10 to 21, but clearly regardless of the exact numbers the spawn rate is very low, so i'll take a look.

**Comment by al132** [comment]
Increased oregen in next update
