### ISSUE TITLE
[1.10.02 v8] RFtools crafter ignores metadata

### ISSUE THREAD

**Issue by CvoidWyvern** [whatthedrunk/allthemods#34]
The RFtools crafter ignores the metadata of materials being used, allowing some items to be used in place of any other similar item.  This allows the conversion of any type of metal to any other using substratum ingots to craft blocks or nuggets, crafting octuple compressed cobble using 9 single compressed, and the duplication of all types of abyssalcraft crystalls.  This also can cause unexpected problems in crafting systems, such as crafting nine double compressed cobble into one double compressed cobble.

**Comment by Carrots4U** [comment]
Thanks for making us aware of the fix. It will be updated today with the others!
