### ISSUE TITLE
[Expert] 1.0.10 Update: Safe-Overlay out of function

### ISSUE THREAD

**Issue by BuggaNoia** [whatthedrunk/allthemods#341]
Since the Update from 1.0.09 to 1.0.10 the Safe-/Lightlevel-Overlay (Key F7) doesn't work any longer. (Just no reaction on key press.) On same world/save before update it worked. 

Pack: All the Mods Expert
Add-On Mods: Optifine, ZyinHUD, ChatLog

Curse Launcher offer only 1.0.10 not 1.0.10b

**Comment by Arcanatias** [comment]
It seems that it doesnt work on the regular atm pack as well, neither does the chunk boundary hotkey (f9).

**Comment by al132** [comment]
In 1.0.11 (several days ago) I added "More Overlays", so now this should no longer be an issue.
