### ISSUE TITLE
[Expert] - Suggestion - Mod Name Tooltip

### ISSUE THREAD

**Issue by skermajo** [whatthedrunk/allthemods#344]
Mod Name Tooltip - https://minecraft.curseforge.com/projects/mod-name-tooltip

Shows the name of the mod in an item's tooltip when you hover over the item in your inventory. I couldn't find a way to enable do this using existing mods in the expert pack. With a big pack such as this, it's nice to be able to see the mod name on an item's tooltip and not have to find the item in JEI to figure out the mod. 

The mod seems small and simple and is very useful for people like myself who organize early game storage sorted by mod.

**Comment by al132** [comment]
Added to #327
