### ISSUE TITLE
[1.10.2] [A.T.S] TCon Hatches, Bone Crooks, and Major Game DeSyncs

### ISSUE THREAD

**Issue by Zenton8787** [whatthedrunk/allthemods#345]
Issue Description: When using the bone crook as a modifier for at least a TCon hatchet, when you break leaves and get a block break event, the game hardcore desyncs forcing the user to close the game to desktop in order to continue

Note: Make sure you update to the latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: game desyncs forcing user to restart game making no progress

What you expected to happen: successful breaking of leaves with increased chance of getting saplings for tree type as well as chance for silk worms

Steps to reproduce:

1. make any TCon hatchet (at least, didnt check with mattock)
2. make a bone crook and use it as a modifier for the TCon tool made above
3. break leaves on any tree
...

Version of All the Mods: All The Sky v1.0.1

Added mods (Optifine, Fastcraft, etc.):

1. none
2.
3.
...

**Comment by OrdinatorStouff** [comment]
testing shows this is no longer a problem in 1.0.7 (if it hasn't already been fixed in previous updates)
