### ISSUE TITLE
[1.10.2] [A.T.S] Quarks Tree Specific Chests and various crafting recipes [minor]

### ISSUE THREAD

**Issue by Zenton8787** [whatthedrunk/allthemods#347]
Issue Description: I noticed that when using any of the tree specific chests (spruce was what I use) from Quark. that a good portion of the crafting recipes dont work for these chests. the Extra Utilities2 Trashcans for instance. there are other recipes but I feel by making these chests ore dictionaried with the vanilla chest, that it will mass fix this inconvenience.

Note: Make sure you update to the latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: Making the Extra Utilities2 Trashcan requires the basic oak chest and no others

What you expected to happen: to be able to use any chest to make said trashcan

Steps to reproduce:

1. make a non-basic oak chest
2. attempt to use it in making the trashcan and other recipes that use chests
...

Version of All the Mods: All The Sky v1.0.1

Added mods (Optifine, Fastcraft, etc.):

1. none
2.
3.
...

**Comment by OrdinatorStouff** [comment]
This should be very easy to add with a fer crafttweaker lines adding them to oredict

**Comment by Zenton8787** [comment]
I need to make a slight correction about what mod the tree specific chests are from, though I dont think the mod really matters, but I dont like stating wrong info. Quark adds chests for the different base trees. I dont know if Random Things does as well. I will change the title of this to reflect this oversite.

**Comment by OrdinatorStouff** [comment]
To-Be-Active in pack version 1.0.2 
Forced many chests to add to oredict with normal "chest"
