### ISSUE TITLE
[Expert] Melter gives infinite ingots

### ISSUE THREAD

**Issue by eriico39hi** [whatthedrunk/allthemods#349]
Issue Description:

When you place an iron ore (like magnetite) into the melter and then use the stamper to pack it into ingots, it returns infinite ingots. 

What happens: You get infinite ingots (iron, lead, copper)

What you expected to happen: you only get twice as many ingots as you input ores

Steps to reproduce:

1. place ore into melter/stamper setup
2. observe infinite resources

Version of All the Mods: 1.0.10

**Comment by al132** [comment]
Version 1.0.14 of ATM:E has now been released. This issue should be fixed now, but if it still exists in version 1.0.14 or later you can reopen this issue.
