### ISSUE TITLE
[1.10.2] Client Crash Placing Boat

### ISSUE THREAD

**Issue by radiocrack** [whatthedrunk/allthemods#35]
http://pastebin.com/iustdWCu

on a server world

version 0.7

crash repeated when user relogged

**Comment by Carrots4U** [comment]
Seems vanilla... not sure what the problem is here.

**Comment by whatthedrunk** [comment]
We are still trying to figure out whats going on but we found a temp fix. Once that area is loaded type /kill @e[type=Boat]

Whoever loaded it will probably crash but on reset if should be good. You may want to TP to the area listed in your crash log to make sure its gone. 

For you it's located here
Entity's Exact location: -593.72, 62.52, 907.27

**Comment by radiocrack** [comment]
Re-tested with version 1.0 

Placing boats no longer crashed. tried various types of boats in same area as original crash.


hard to keep up with you guys.  great work.  Lots of little bugs I was about to report were fixed in the latest.

**Comment by whatthedrunk** [comment]
Good to know thanks! I will mark this as closed but please let me know if it comes back.
