### ISSUE TITLE
Embers liquid pipe Duplicates Liquids that can go into ATM: Rockhounding Machines 

### ISSUE THREAD

**Issue by BLOODAXED** [whatthedrunk/allthemods#350]
Issue Description:  Pumping liquid into or out of all Rockhounding machines using Embers's mechanical pump causes the liquid to duplicate and fill up the machine and the target location.  It seems as if it tries to place the same unit of liquid into both targets at once.  This does not happen with Mekanism's Liquid pipe nor Ender IO's Liquid Conduit.

What happens:
When using Embers's mechanical pump and/or the liquid pipe to pump liquid into or out of any of the Rockhounding machines the source and the target both fill up completely.

What you expected to happen:
When using Embers's mechanical pump and/or liquid pipe it will take the liquid from one source and move to a target location, such as a tank.

Steps to reproduce:

1. Attach an Embers Mechanical pump to a Rockhounding machine that has a small amount of liquid stored in it
2. Attach the pump to any tank
3. Turn the pump on and see both liquid stores fill completely

...

Version of All the Mods: Expert v1.0.10

**Comment by eriico39hi** [comment]
I have a feeling that this is related to the issue i posted: Issue 349
[https://github.com/whatthedrunk/allthemods/issues/349](url)

**Comment by BLOODAXED** [comment]
It does only seem to work with certain liquid stores too.  For example I have tried it with just moving it between two tanks as well as with a tank and a smeltery drain; both did not cause any duping

**Comment by al132** [comment]
Version 1.0.14 of ATM:E has now been released. This issue should be fixed now, but if it still exists in version 1.0.14 or later you can reopen this issue.
