### ISSUE TITLE
Three Mod Suggestions

### ISSUE THREAD

**Issue by Fortanono** [whatthedrunk/allthemods#351]
Here we go. Each iteration of ATM could benefit from these, minus maybe Expert cause that already has a tech tree sorted out.

Refraction: A light manipulation mod with mirrors and cool stuff. https://minecraft.curseforge.com/projects/refraction
Totemic: A mod that involves totems, instruments and ceremonies. https://minecraft.curseforge.com/projects/totemic
Better with Mods: A version of Better than Wolves for Forge. Turn off all challenge modifiers and you have a cool mechanical power mod. (But PLEASE turn off all challenge modifiers, I don't want my iron to smelt into nuggets 😛) https://minecraft.curseforge.com/projects/better-with-mods

**Comment by al132** [comment]
Refraction is already in regular ATM, all of these have already been added to the suggestion list for ATM:E however, I don't plan on adding any of them for now.
