### ISSUE TITLE
My friends client crashes

### ISSUE THREAD

**Issue by deividaslord** [whatthedrunk/allthemods#353]
Issue Description:

Note: Make sure you update to the latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: Client crashes

What you expected to happen: launch the client without a crash

Steps to reproduce:

1. launched client
2. crashed

Version of All the Mods:

Added mods (Optifine, Fastcraft, etc.):

1. At the beginning he tried to install Optifine and Fastcraft but it crashed, so he tried it with out those mods. And crashed still. http://pastebin.com/aAsLLLgD

**Comment by Meller127** [comment]
You are still using OptiFine and an outdated version

 FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_C2 177 mods loaded, 176 mods active
