### ISSUE TITLE
StackOverflowException because of SonarCore and IC2 interaction

### ISSUE THREAD

**Issue by P3pp3rF1y** [whatthedrunk/allthemods#354]
Issue Description: 
After updating to version 1.53 I get StackOverFlowException after world start. Looks to be some kind of infinite loop between sonarcore and ic2 that causes this - http://pastebin.com/8ffrCTDY 
There are flux networks controllers, plugs and points in the world that I guess trigger the sonar core calls, I am not aware of any IC2 setup on the server.

The only additional mod is Thump v 1.10.2-4.1.0.138.

**Comment by jezzen** [comment]
Same crash-log 
[crash-2016-12-29_23.55.29-server.txt](https://github.com/whatthedrunk/allthemods/files/677195/crash-2016-12-29_23.55.29-server.txt), world tries loading for a while and doesn't respond, then crashing after a while. It's single-player, and I have no IC2 started yet, and the only thing from Calculator or Flux Networks done immediately beforehand would be using the hunger module (been used fine before).

Remembering that sonarcore had an update, I tried updating it and it seems to have worked.

**Comment by whatthedrunk** [comment]
I finally got around to just removing SonarCore in 2.0 going forward.
