### ISSUE TITLE
Rockhounding Mineral Sizer, never stops

### ISSUE THREAD

**Issue by Meller127** [whatthedrunk/allthemods#355]
Rockhounding Mineral Sizer, never stops even when output stack is 64

What you expected to happen:
Machine will stop using up my crushing gears

![2016-12-27_23 38 24](https://cloud.githubusercontent.com/assets/13392710/21509910/378454ac-cc8e-11e6-98a2-90d7c6acb652.png)

Version of All the Mods: 
Expert 1.0.11

Added mods (Optifine, Fastcraft, etc.):

1. Optifine
2.
3.
...

**Comment by al132** [comment]
I already told you, but fixed most recent ATM Rockhounding update a day or two ago, will be in next pack update.
