### ISSUE TITLE
Mod Suggestions.

### ISSUE THREAD

**Issue by kaperios** [whatthedrunk/allthemods#358]
Hello! If it is possible, can you add these mods to the ATM:E? :)

- Immersive Craft - https://minecraft.curseforge.com/projects/immersive-craft
- Aqua Munda - https://minecraft.curseforge.com/projects/aqua-munda

It would be cool if u add only these two small mods. P.S All these mods are from McJty

**Comment by al132** [comment]
Not likely that I will add them in even though I do think they're really cool. Added to #327
