### ISSUE TITLE
[1.10.2] FastLeafDecay Automatically Decaying Trees

### ISSUE THREAD

**Issue by SynnGit** [whatthedrunk/allthemods#359]
**What happens:**
When the _FastLeafDecay_ mod is present, leaves begin automatically decaying treetops into symmetrical dome shapes in some biomes (ie: Roofed Forest): [http://i.imgur.com/ynrTCIu.jpg](http://i.imgur.com/ynrTCIu.jpg).  This causes massive lag as it spreads throughout the entire biome.

**What you expected to happen:**
I don't believe leaves should be automatically decaying; they should persist until a tree is cut down. If the _FastLeafDecay_ mod is removed and the same world is re-created (same seed), there is no auto-decay:  [http://i.imgur.com/UnugqbP.jpg](http://i.imgur.com/UnugqbP.jpg)

**Steps to reproduce:**
1. Create a new world on a fresh install of All The Mods.
2. Enable Creative mode.
3. Fly around and find a Roofed Forest biome (or use this seed: `-3151082389169612036`, and go just south of spawn to the Roofed Forest).
4. Observe that the leaves are automatically decaying.

**Version of All the Mods:**  1.54

**Added mods (Optifine, Fastcraft, etc.):**
1. BetterFps (1.3.2) [1.10.2]
2. FullscreenWindowed (1.3.0b) [1.10.2]
3. Optifine (HD U D4) [1.10.2]

**Comment by OrdinatorStouff** [comment]
I believe this is technically present in vanilla as well, if the auto-generated (i.e. not user-placed) leaves recieve a block-update and are far away from logs, they'll begin decaying. The only difference is that with FastLeafDecay it's happening.... fast. Also, it *shouldn't* be happening automatically but only after a nearby block update like flowing water or whatever else.

Custom Biomes like those from BoP or custom trees are more prone to this happening more often, as well.
