### ISSUE TITLE
[1.10.2] OpenComputers blocks do not accept power

### ISSUE THREAD

**Issue by jmcaffee** [whatthedrunk/allthemods#36]
Know issue for OpenComputers on 1.10: [OpenComputers/issues/1937](https://github.com/MightyPirates/OpenComputers/issues/1937)

Work around is to disable power usage in `minecraft/config/opencomputers/settings.conf` and restart minecraft:

```
    # Whether to ignore any power requirements. Whenever something requires
    # power to function, it will try to get the amount of energy it needs from
    # the buffer of its connector node, and in case it fails it won't perform
    # the action / trigger a shutdown / whatever. Setting this to `true` will
    # simply make the check 'is there enough energy' succeed unconditionally.
    # Note that buffers are still filled and emptied following the usual
    # rules, there just is no failure case anymore. The converter will however
    # not accept power from other mods.
    ignorePower=true

```

**Comment by Carrots4U** [comment]
Will be fixed next version, thank you!

**Comment by Redlotus99** [comment]
Any word on when this next version will be released?

**Comment by Carrots4U** [comment]
The version that fixed this was released weeks ago, is it back again?

**Comment by Redlotus99** [comment]
This issue has was put in 18 days ago so I am unsure if it was fixed. My current version of Open Computers is OpenComputers-MC1.10-1.6.0.2-beta.4.jar and all the computers are unable to accept power unless set to ignore power.

Is there an updated version I am unaware of that fixed the machines so they accept power?

**Comment by Carrots4U** [comment]
What version of All the Mods are you on currently? 1.7?

**Comment by Redlotus99** [comment]
This issue is in regards to the 1.10.2 version and all the mods I am currently using are 1.10.2 with a few that are 1.9.4. SO my modpack has updated versions of nearly all the mods from Ender IO to IC2 and it seems neither IC2 Cables or Ender IO conduits connect to Open Computers blocks presently.

**Comment by Carrots4U** [comment]
nonono, are you on v1.7 of all the mods? Not 1.7 minecraft,

**Comment by Redlotus99** [comment]
My apologies I just realized I'm posting on the wrong github.  I followed a link to here from the Open Computers github.
