### ISSUE TITLE
[Expert] AE2 - too easy to make

### ISSUE THREAD

**Issue by kaperios** [whatthedrunk/allthemods#360]
I think that ae2 is too easy to make! Applied Energistics system needs to make only 5 types of quartz that aren't that hard to get (Only elven and sunny is hard to get for me), some steel and metal aloyer and rest is very easy to get. For example Refined Storage system (which is slightly worse) you need get to the end, build a Elven portal, start Blood Magic mod and make bees or a peat bog farm from Forestry. So in conclusion AE2 which have more features is cheaper than Refined Storage which have less features. I think that only thing in Refined Storage that can be expensive is Fluid Storage. I hope that this will be changed :)

**Comment by al132** [comment]
This is all intentional. We are happy with how it is currently. Thanks for the suggestion though.
