### ISSUE TITLE
[Expert] Embers Duplication Bug

### ISSUE THREAD

**Issue by kaperios** [whatthedrunk/allthemods#361]
Issue Description: If I drop more than 1 item to the melter from up side when i'm clicking on it i'm getting twice as much as i put into it.

What happens: Melter duplicates items

What you expected to happen: Get as much items as i put into melter

Steps to reproduce:

1.Throw items to up side of Melter with Q
2.Click on top half of Melter
3.There you have a duplicated items

Version of All the Mods: ATM:E v1.0.13

Added mods (Optifine, Fastcraft, etc.):

1.Optifine
2.Sampler

**Comment by al132** [comment]
This is a known issue that has finally been fixed in the beta release of Embers which came out a day or two ago. This will be fixed in the next pack update.

**Comment by al132** [comment]
Version 1.0.14 of ATM:E has now been released. This issue should be fixed now, but if it still exists in version 1.0.14 or later you can reopen this issue.
