### ISSUE TITLE
[ATM Expert] Compressed block(Dirt, etc.) can be multiplied by breaking it with pickaxe 

### ISSUE THREAD

**Issue by Cavesnakes** [whatthedrunk/allthemods#362]
Verision: ATM Expert 1.0.11

**Comment by al132** [comment]
I could not replicate this in the new version 1.0.14. Closing this issue for now assuming it is fixed. You can reopen if it is still a problem in v1.0.14 or later.

**Comment by Cavesnakes** [comment]
It's not fixed, still going on

**Comment by al132** [comment]
Could you be more specific? Which tool and which compressed item could I replicate this with?

**Comment by Cavesnakes** [comment]
Currently I use flint pickaxe, Infiminer, etc.(Harvestable tools) 
I think all of the pickaxe can cause this problem

**Comment by al132** [comment]
Can you duplicate this behavior in single player without sponge?

**Comment by al132** [comment]
I have decided i'm not going to try to support spongeforge. Closed, reopen if this can be duplicated without sponge.
