### ISSUE TITLE
strange WTFOres resourcepack file generation

### ISSUE THREAD

**Issue by Cavesnakes** [whatthedrunk/allthemods#363]
OS: GNU/Linux CentOS 7

I think these issue caused by WTFOres file generation method (Windows based file generation, and thus Not compatible with Linux)

**Comment by WesCook** [comment]
Fixed on WTF's side.

https://github.com/WhiskyTangoFawks/Expedition/issues/64

**Comment by whatthedrunk** [comment]
WTF has been nothing but a pain lately so we are now staying on an older version until it's fixed and it has been removed from expert fully.
