### ISSUE TITLE
[Expert] Changing ATM Expert Guide Book

### ISSUE THREAD

**Issue by kaperios** [whatthedrunk/allthemods#365]
First page of 2nd chapter is kinda outdated. Actually u don't need to use 3 gears in grindstone setup. You must face up your master axis and then u need only 2 gears to have grindstone from Crossroads working.

**Comment by al132** [comment]
It's possible that two gears have always worked, but I don't recall. Either way, just for the sake of simplicity I added a tidbit saying that what you mentioned is possible as well.
