### ISSUE TITLE
[A.T.S] [1.10.2] List of Chest and Trapdoor recipes that need added to Ore Dictionary

### ISSUE THREAD

**Issue by Zenton8787** [whatthedrunk/allthemods#367]
Issue Description: Here is a pastebin to the list that I made of all the recipes I have found (going through the vanilla chest and trapdoor recipes) that dont support Ore Dictionary for the vanilla chest or trapdoor. there was one recipe for the trapdoor I intentionally left out and that is Ender IO's Painter, painting the trapdoor to look like other things (why paint the Dark Oak trapdoor when it looks so nice ((my opinion)))

pastebin here http://pastebin.com/QH4wpd0W

Note: Make sure you update to the latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: All of the recipes listed in the pastebin dont support Quark or Dark Utilities chests or trapdoors

What you expected to happen: My favored spruce tree wood to continue to remain supreme

Steps to reproduce:

1a. Attempt to use Quarks tree specific chests or Dark Utilities material specific chests to make any of the listed items
1b. Attempt to use Quarks tree specific trapdoors to make indicated items as well
...

Version of All the Mods: v1.0.2

Added mods (Optifine, Fastcraft, etc.):

1.none
2.
3.
...

**Comment by OrdinatorStouff** [comment]
This will be fixed in 1.0.7
instead of changing all mod recipes to accept oredict, now added "conversion" recipes where any oredict chest, door, trapdoor, etc can be crafted into the basic minecraft "oak" version.
