### ISSUE TITLE
Reinforced Sword + Pickaxe = Wrench?

### ISSUE THREAD

**Issue by Meller127** [whatthedrunk/allthemods#368]
To make a wrench from Calculator you combine a sword and pickaxe, but the durability is a missmatch.

Recipie needs 250 but the items have 400 so the wrench is uncraftable.

This wrench is the only i have found to change the input/output on Calculators Machines.

Version of All the Mods: 1.0.14 Expert

Added mods (Optifine, Fastcraft, etc.):

1. Optifine
2.
3.
...

**Comment by al132** [comment]
This will be fixed in the next version, I have added an alternate shaped crafting recipe just using reinforced stone.
