### ISSUE TITLE
Crossroads Dirt Cables have random effect when placed.  ATM Expert Pack

### ISSUE THREAD

**Issue by Zetharion** [whatthedrunk/allthemods#369]
Issue Description:  I used to put dirt cable on top of the Fluid Cooling Chamber to get copper ingots.  Since the update to 1.0.16, the first update we've done since .13, placing them on top of the fluid cooling chamber causes random effects to happen.  The first time I got a lightning strike on it. The second time I got a squid.  The third time it was an explosion that destroyed the setup.  Its acting like a Chance Cube or Lucky Block.

Note: Make sure you update to the latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:

See above

What you expected to happen:

I expect the cable to simply catch fire and the cooling chamber to produce an ingot.

Steps to reproduce:

1. Do the copper ingot setup as instructed in the guide.
2. Place dirt cable.
3. A random effect is what I am getting.
...

Version of All the Mods:

1.0.016

Added mods (Optifine, Fastcraft, etc.):
none

1.
2.
3.
...

**Comment by Zetharion** [comment]
OK I have a standalone instance of Crossroads and the DIrt Cable we have in the pack doesnt exist in the instance I ran.  Is it something added by the pack dev and not the mod?

**Comment by Zetharion** [comment]
After some testing I see that any cable made with dirt as part of the recipe has several random effects other than fire that can happen.  One of those is an explosion that destroys the cooling chamber and its contents, in my book that's not ok.  Other effects of dirt cables are a villager spawns, a named Squid, a Pufferfish and a dirt block being placed on top of the cooling unit.  Cables that use slime spawn a slime instead of catching fire.  I didnt bother testing higher tier cables.

I can deal with the other effects, but destroying the setup and its contents is a bit much I think.

**Comment by al132** [comment]
I first ran into all these different effects when I started developing the pack. I specifically asked the dev of crossroads to add a config option to turn off these effects, which he did. I just looked at the config file that would have also been distributed with 1.0.16 and it says the following:
`"heat cables" {
    B:"Heat Cable Effects"=false
}`

so it _should_ be disabled. Can you please confirm that this is also disabled for you in crossroads.cfg?

**Comment by al132** [comment]
Now that I look, there are two identical config options, but apparently it ignores the old one. I'll release a new build of the pack today to fix this.

**Comment by Zetharion** [comment]
Sweet, thanks for the quick look.
