### ISSUE TITLE
[1.10.2] v08hotfix Mouseover some metal blocks crashes game

### ISSUE THREAD

**Issue by Waltibaba** [whatthedrunk/allthemods#37]
A mouseover of a block of copper or tin (in a crafting bench when trying to craft them, in the ore converter) causes the client to crash (not the server though) due to the missing tooltip information. I'm assuming this is due to the recipe defaulting to the removed IC2 copper/tin blocks.
Same happens when ore converting ingots and putting the mouse over the 3rd item, probably the IC2 ingot. Without debug info for the string being searched for the block's tooltip though, its hard to tell for certain.

To reproduce:
Put any 3x3 copper ingots in any crafting bench, and try pulling out the resulting block.

[crash-2016-07-12_08.14.42-client.txt](https://github.com/whatthedrunk/allthemods/files/358660/crash-2016-07-12_08.14.42-client.txt)

**Comment by Carrots4U** [comment]
I can make metal blocks just fine, are you sure you are running the hotfix and ic2 is removed?

**Comment by Waltibaba** [comment]
Yes to both, must have been remaining config settings. The curse launcher version upgrade to v08hotfix causes the issue. A clean download of v08hotfix from curse into a new profile fixes it but of course resets all minecraft settings, journeymap waypoints, etc.
