### ISSUE TITLE
[Expert] [Suggestion] [Recipe] Add Expert Recipe for Crystal Cluster Block

### ISSUE THREAD

**Issue by AaronOziel** [whatthedrunk/allthemods#371]
Tier 6 blood magic offers a large chunk of room for more runes but currently has no recipe for the capstone block Crystal Cluster. Please consider testing tier 6 and adding a suitably expert recipe for the Crystal Cluster Block.

**Comment by al132** [comment]
Do you have any suggestions? I don't know late game blood magic that well, goose did most of that stuff.

**Comment by Azg99** [comment]
The Blood Magic t6 orb used to be gotten from killing demons in a super-late game demon invasion. I don't know what WayOfTime has planned for Blood magic, but as of my current knowledge, the ritual for starting the invasion has not been re-implemented into the 1.10 versions and seeing as he keeps changing the way things work ever so "slightly" I'm wondering if the invasion will be added again. I would suggest (I haven't really played expert all that much yet, so this is partly uninformed) anything that would be of similar worth to draconic evolution's awakened draconium blocks from normal mode should work fine.

**Comment by Nedrith** [comment]
Considering that a lot of blood magic runes are multiplicative and T6 adds a lot of runes it should be really expensive and to that I agree with Azg99 on awakened draconium.

A simple recipe would be reuse the basic idea of WayOfTime's old crystal cluster recipe and do 5 gaia spirit ingots in a X pattern with the remaining spots being awakened cores.  Expensive and requires the kill of the strongest magic boss multiple times to get 4 crystal clusters for the altar and another for the orb.

Of course the issue with that is it uses non blood magic items.  A simple solution for that would be to add a custom item like a corrupted gaia ingot.  Throw a gaia spirit ingot into a T5 altar with a lot of LP to get one.  Something like 500k LP or so.

**Comment by al132** [comment]
Goose has had a recipe ready for me for a while, I just forgot to put it in the last update or two, it will be in the next update.

**Comment by al132** [comment]
V1.0.23 released with a new recipe
