### ISSUE TITLE
[Expert] [Suggestion] [Recipe] Nerf RFTools quarry card, not the builder's block. 

### ISSUE THREAD

**Issue by AaronOziel** [whatthedrunk/allthemods#372]
The RFTools builders block is AWESOME and provides much more than jus quarrying. With all it's additional features I usually use 3-5 different builders with different configurations for different purposes and this has been made prohibitively expensive since the builder's block itself is so expensive. I suggest the recipe be restored to something closer to vanilla RFTools and transfer all of the crafting complexity to the REAL culprit, the quarry card. 

The builder can be a god-send for mid game base building and its void quarry card is nice for clearing out space. So many cool functions rendered almost unusable since you can realistically only afford one builders block until **hyper late game**.

**Comment by al132** [comment]
This seems reasonable, i'll look into it.

**Comment by al132** [comment]
Has been changed in upcoming release for 1.0.19
