### ISSUE TITLE
[ATS] [1.10.2] Crafting issues for Salt past ATS v1.0.2

### ISSUE THREAD

**Issue by Zenton8787** [whatthedrunk/allthemods#373]
Issue Description: This was partially my own fault from a different issue I had and this is more or less damage control from it... After the implementation of consolidating the different ores in the pack to use Ex Nihilo Omnia's versions, salt got put into this as well. Pams HarvestCrafts salt was consolidated with Mekanisms Salt which has made a few issues with its crafting processes. Cooking For Blockheads Sink for instance no longer recognizes salt as a valid item to craft when connected to the Cooking Table. Because of No More Recipe Conflict, when using Pams HarvestCrafts Pot and a stack of Fresh Water to craft Salt, the crafting recipe keeps switching back to bubbly water between individual crafts even if you click to craft a stack. This means you cant easily mass craft a stack of salt

Note: Make sure you update to the latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: You can no longer use the Cooking for Blockheads Cooking Table attached to a sink to craft salt as I dont think it sees Mekanisms salt as a valid item to craft. Nor can you easily mass craft salt using Pams HarvestCraft's Pot and Fresh Water to craft a stack of salt at a time because of No More Recipe Conflict

What you expected to happen: Cooking for Blockheads Cooking Table to make salt when attached to a sink and a pot, or the more manual way of making salt using the player crafting grid or better to use a Pams pot and fresh water to make salt

Steps to reproduce:

1. place Cooking Table next to sink with a pot in your inventory to craft salt
2. attempt to use a Pams Pot and Fresh Water to make a stack of salt at a time in the player crafting grid
...

Version of All the Mods: v1.0.3

Added mods (Optifine, Fastcraft, etc.):

1. na
2.
3.
...

**Comment by OrdinatorStouff** [comment]
Will be fixed in 1.0.7 to use saucepan instead of pot and also be able to use mystical ag. water essence as an alternative
