### ISSUE TITLE
Decrease on mobs spawning 

### ISSUE THREAD

**Issue by DaFuJosh** [whatthedrunk/allthemods#374]
Issue Description:

Note: Make sure you update to the latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:

**What you expected to happen:**
**how come mobs aren't spawning that often and never spawn in the mob farm "correctly built" only get 1 or 2 mobs on normal same in nether please someone help me is it a mod decreasing the spawn rate or a config?**

Steps to reproduce:

1.is it a mod causing issue
2.or config
3.somethings reducing the mob spawn rate
...

Version of All the Mods: 1.10.2 V1.57

Added mods (Optifine, Fastcraft, etc.):

1.optifine
2.
3.
...

**Comment by whatthedrunk** [comment]
There is no mod decreasing mob spawns and they seem to be spawning as intended. Let me know if you are still having issues after the next update.

**Comment by DaFuJosh** [comment]
same issue please find fix i beginning to lose patiences
