### ISSUE TITLE
[Expert] Slime Boot variants are still cheap, only green pair has been modified

### ISSUE THREAD

**Issue by WesCook** [whatthedrunk/allthemods#375]
Issue Description: Not all slime boots have had their recipes modified.

What happens: It's easier to craft colored pairs than the green pair.

What you expected to happen: They should have similar recipes.

Steps to reproduce:

1. Craft a colored pair of slime boots
2. You're done!
...

Version of All the Mods: ATM Expert v1.0.19

Added mods (Optifine, Fastcraft, etc.):

1. N/A
...

**Comment by al132** [comment]
Will be fixed in next update

**Comment by al132** [comment]
V1.0.20 released with this change
