### ISSUE TITLE
[1.10.2 - v0.8] Biomes O'Plenty overrides superflat world settings

### ISSUE THREAD

**Issue by Ruuubi** [whatthedrunk/allthemods#38]
You're currently unable to customize Superflat worlds, because BoP is set to be the default world type.
If you select "Superflat" as world generation type and click on customize the world type will switch back to BoP. That means you can only play the default superflat world and not a customized one.

Changing the config entry to false (**config/biomesoplenty/misc.cfg**) fixes that problem:

> "gui settings" {
    # Use the Biomes O' Plenty World Type by default when selecting a world. [default: false]
    B:"Default to BoP World Type"=false
}

**Comment by whatthedrunk** [comment]
Decided to remove the config for now so this should be fixed in the next update tonight.
