### ISSUE TITLE
Does redstone exist in current worlds after the removal of WTF Expeditions? ATM Expert

### ISSUE THREAD

**Issue by Zetharion** [whatthedrunk/allthemods#382]
In our world after WTF Expeditions was removed redstone is no where to be found.  Did removing it have the side effect of us having to go to new chunks to find vanilla redstone generation?  I have search massive cave systems for a couple of hours and dug tunnels with my hammer and there is no sign of it anywhere.

**Comment by al132** [comment]
I wouldn't expect this to be the case, but I have heard some people mentioning that it has messed up generation of vanilla ores. I can't do much about it unfortunately, but I would expect this to be fixed in new chunks.
