### ISSUE TITLE
Redstone ore dissappeared

### ISSUE THREAD

**Issue by jestingstud** [whatthedrunk/allthemods#383]
Issue Description:

What happens: Explored underground with a Flint Pickaxe. Found some redstone ore and when i came back with a Reinforced Stone Pick the ore was gone. Playing solo so i have no idea whats going on

**Comment by al132** [comment]
There have been several reports of this problem. It's most likely related to the removal of WTF Expeditions several versions ago. Unfortunately, you will most likely need to discover new chunks to find redstone ore.
