### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by Tsyklop** [whatthedrunk/allthemods#384]
Issue Description:

Note: Make sure you update to the latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:

Download the latest version of the assembly. Launched. I allocate 5 GB of RAM. On entering into the world, the client crash.

log: http://pastebin.com/jja1JZ0y

What you expected to happen:

Steps to reproduce:

1.
2.
3.
...

Version of All the Mods:

Added mods (Optifine, Fastcraft, etc.):

1.
2.
3.
...

**Comment by whatthedrunk** [comment]
Try updating your graphics card if that doesn't work try removing default options and deleting options.txt. If that doesn't work let me know and we will re open this.
