### ISSUE TITLE
[ATM][1.10.2 v1.58] Inscriber recipes from AE2 are missing from JEI.

### ISSUE THREAD

**Issue by Ncrpts** [whatthedrunk/allthemods#386]
Issue Description:

Inscribers recipe for all the component seems to be missing from JEI, so missing are all the recipes that are made in an inscriber wich are, Calculation Processor, Printed Calculation Circuit, Engineering Processor, Printed Engineering Circuit, Logic Processor, Printed Logic Circuit, Printed Silicon

What happens:

Nothing happens when clicked on the mentioned items instead of showing the correct recipes.

What you expected to happen:

See inscriber recipe for the mentioned items, recipe were showing correctly in 1.57

Steps to reproduce:

1. Open Inventory
2. type "Printed Silicon" in JEI search bar
3. click "Printed Silicon" from AE2

Version of All the Mods: 1.58

Added mods (Optifine, Fastcraft, etc.):

1. Optifine

**Comment by Ncrpts** [comment]
it seems that Applied Energistics "Quartz Grindstone" grinding recipes are also missing from JEI

**Comment by whatthedrunk** [comment]
Fixed in the update coming out later today. Thanks.
