### ISSUE TITLE
ATM:E Update to 1.0.22 Removes Packet Filter items

### ISSUE THREAD

**Issue by BuggaNoia** [whatthedrunk/allthemods#387]
Issue Description:

Update from v1.0.21 to v.1.0.22 removes Routing Packet Filter items out of chest, as announce on world startup

What happens:

Packet Filter Items items are gone. But they are still displayed in JEI. (And can be cheating back in.)

Steps to reproduce:

Start World after update with items from Packet Filter Mod in world / any inventory

Version of All the Mods:

1.0.21 to 1.0.22

Added mods (Optifine, Fastcraft, etc.):

1. OptiFine
2. ZyinsHUD
3. ChatLog
4. OpenBlock Elevator

**Comment by al132** [comment]
Huh, strange. I remapped the registry IDs so that they would also be compatible in 1.11 as well, but even when I tested in 1.10 again my blocks didn't dissapear.

**Comment by BuggaNoia** [comment]
I think it doesn't have to do with the items/blocks itself, because of the remove notification on world startup (which always includes even ids, that are not part of the current world).
Maybe a ID conflict with the mod "OpenBlock Elevator" added by myself.
