### ISSUE TITLE
[1.10.2] EnderIO Capacitor Banks Randomly Stop Recieving RF

### ISSUE THREAD

**Issue by BossRedRanger** [whatthedrunk/allthemods#39]
Randomly, Capacitor banks stop recieving power. Generators will charge their internal storage yet not send to the capacitor banks. I've removed the banks and replaced with spawned in versions only to have the issue re-appear later.

**Comment by Carrots4U** [comment]
It is because capacitors randomly have their input/output set to 0. All we can do currently is wait for the devs to fix the issue. Until then you can just reset the input/output numbers back to the highest instead of spawning in new sets.

**Comment by BossRedRanger** [comment]
Thanks, I'll give that a shot.

**Comment by Carrots4U** [comment]
Does not seem to be happening anymore. Reopen if still occurring.
