### ISSUE TITLE
All the mods and anny other mod pack is crashing when pushing the play button

### ISSUE THREAD

**Issue by MatteusR898** [whatthedrunk/allthemods#390]
Issue Description: All the mods is crashing when pushing the play buttone (this happens to anny other mod pack)

Note: Make sure you update to the latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: it just crashes and sas something about minecraft versions and the weird thing is that all the mod packs 

What you expected to happen: well i didnt expect this i expected the mod pack to work

Steps to reproduce: i don't konw if anny other people i
[All the mods game output.txt](https://github.com/whatthedrunk/allthemods/files/730299/All.the.mods.game.output.txt)
s or have had this problem but i have included the game output
Version of All the Mods: 1.10.2

**Comment by SpectraXHub** [comment]
I have the same problem and the log which comes with the problem is like this:

[fml-client-latest.txt](https://github.com/whatthedrunk/allthemods/files/732531/fml-client-latest.txt)

**Comment by Link71421** [comment]
Uninstall your nVidia 3D Vision Driver. Not the graphics driver. Just the 3D vision one. That seems to be fixing this issue for several people.

**Comment by SpectraXHub** [comment]
Thanks it worked for me

**Comment by al132** [comment]
This isn't really the place for problem solving general minecraft/curse problems, but try the solution that @Link71421 posted if you're still having trouble. Closed.
