### ISSUE TITLE
making copper ingots easier mid game

### ISSUE THREAD

**Issue by bird191** [whatthedrunk/allthemods#391]
i want a change for the pack right now you process copper and when you get to dust you have to arc furnace it or melt it in a smeltery or the other early game device i have gotten to the point of 4x ore processing which is way past the point of still using those machines. As well every other dust can be furnaced except for that one. My idea is to ore dictionary it with a different copper dust that has no recipe so the only way to get is to use mekanism's ore dictionary machine so the only way to get it is by mid game and that dust can be furnaced like the others making it easier for automation and mid game players but still locked behind midgame stuff so you have to do earlier game stuff to get to it

**Comment by al132** [comment]
I just released version 1.0.23, I added recipes so dirty copper dust can be grinded into "crushed copper ore" with a macerator or AA grinder which already could be smelted. It's not ideal, but it's the most practical solution with no minetweaker support for mekanism.
