### ISSUE TITLE
JEI Client Crashes due to mods missing textures.

### ISSUE THREAD

**Issue by SpeedSlider** [whatthedrunk/allthemods#393]
Issue Description:
JEI crashes are related to Optifine and the mods in ATM2 version 0.40 that are missing textures and show blue text in the JEI search screen (e.g. advance generators, tech reborn, and simply conveyors).

What happens:
When using JEI to look items up or page through the menu my client crashes.

What you expected to happen:
I expect to see the JEI items.

Steps to reproduce:

1. Have Optifine installed
2. Due a JEI search with mods missing textures and showing blue text instead. I paged through JEI till I reached Advance Generators and did a search for @simp when I experience the crash.
3.
...

Version of All the Mods: ATM2 0.40
[crash-2017-01-30_12.00.54-client.txt](https://github.com/whatthedrunk/allthemods/files/739735/crash-2017-01-30_12.00.54-client.txt)

Added mods (Optifine, Fastcraft, etc.):

1. Optifine
2.
3.
...

**Comment by whatthedrunk** [comment]
Let me know if this happens without optifine and I will reopen. I can't reproduce it.
