### ISSUE TITLE
[Suggestion] Sound System Reloader Mod

### ISSUE THREAD

**Issue by TheRandomLabs** [whatthedrunk/allthemods#396]
When changing the default audio device, Minecraft fails to update to the new device. This is especially annoying when I'm using my Bluetooth headset, as it occasionally disconnects from my laptop. Would it be possible to include a mod that can reload the sound system? As of now, there are two mods that I know of for 1.10.2 that do that - [RandomTweaks](https://minecraft.curseforge.com/projects/randomtweaks) (which is actually my mod) and [Sound Reloader](https://minecraft.curseforge.com/projects/sound-reloader).

Also, completely unrelated, but the "Performance Issues?" link in the All the Mods Expert CurseForge page is broken.

**Comment by al132** [comment]
Fixed the performance issues link, thanks for letting me know.

**Comment by whatthedrunk** [comment]
Added it to here to review next update https://github.com/whatthedrunk/allthemods/issues/173
