### ISSUE TITLE
[ATM:E] [Suggestion] deleted items on update changelog 

### ISSUE THREAD

**Issue by BuggaNoia** [whatthedrunk/allthemods#398]
Update and worldstart on v1.0.23 gives me the info that some items of Nullifier and 2 buckets of AbyssalCraft get deleted. 
Guess this is totally OK.

Suggestion: Can you add to each changelog an info what items get reported on next startup after update? No big detailed list. Only a vage note. 
That way one can be sure that everything is fine in that case.

**Comment by al132** [comment]
I'll try my best to do this
