### ISSUE TITLE
ATM Expert: support for tier 2 and tier 3 of AA oil in IC2 semifluid Gen.

### ISSUE THREAD

**Issue by demethan** [whatthedrunk/allthemods#399]
Hi, 

Would it be possible to add the support for AA oils in the IC2 semifluid generator. 

There should be an IC2 config to add support. 

Thanks.

**Comment by al132** [comment]
Unfortunately it doesn't look like there actually is a config option

**Comment by demethan** [comment]
that is too bad.

I remember doing it in the older versions.
