### ISSUE TITLE
Jei crashes when I try to log on to the server

### ISSUE THREAD

**Issue by Harith163** [whatthedrunk/allthemods#4]
Crash report

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Bloodmoon-MC1.9.4-1.4.1.jar)
  HarmonyPreloader (craftingharmonics-1.9.4-1.4.3.26.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.jar)
  CoreXU2 (extrautils2-1.9.4-alpha-1.0.0a.jar)
  Reborn Core ASM (RebornCore-1.9.4-2.5.1.35-universal.jar)
  LoadingPlugin (RandomThings-MC1.9.4-3.7.3.jar)
  CorePlugin (FluxedRedstone-2.2.1.44.jar)
  FMLPlugin (InventoryTweaks-1.61-dev-53.jar)
  CoreMod (Aroma1997Core-1.9.4-1.0.6.0.b65.jar)
  EnderCorePlugin (EnderCore-1.9.4-0.4.0.23-alpha.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 6/4/16 10:51 AM
Description: JEI failed to start:

java.lang.NullPointerException: Item.itemRegistry.getNameForObject returned null for: class refinedstorage.item.ItemBlockBase
	at mezz.jei.util.StackHelper.getUniqueIdentifierForStack(StackHelper.java:352)
	at mezz.jei.util.StackHelper.getUniqueIdentifierForStack(StackHelper.java:333)
	at mezz.jei.util.RecipeMap.addRecipeCategory(RecipeMap.java:54)
	at mezz.jei.RecipeRegistry.<init>(RecipeRegistry.java:82)
	at mezz.jei.util.ModRegistry.createRecipeRegistry(ModRegistry.java:123)
	at mezz.jei.ProxyCommonClient.startJEI(ProxyCommonClient.java:169)
	at mezz.jei.ProxyCommonClient.onEntityJoinedWorld(ProxyCommonClient.java:137)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_491_ProxyCommonClient_onEntityJoinedWorld_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.world.World.func_72838_d(World.java:1122)
	at net.minecraft.client.multiplayer.WorldClient.func_72838_d(WorldClient.java:241)
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2441)
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2349)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:273)
	at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:76)
	at net.minecraft.network.play.server.SPacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at net.minecraft.util.Util.func_181617_a(SourceFile:45)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1044)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:369)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.9.4
	Operating System: Mac OS X (x86_64) version 10.11.3
	Java Version: 1.8.0_73, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1429569984 bytes (1363 MB) / 3089104896 bytes (2946 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 105
	FML: MCP 9.28 Powered by Forge 12.17.0.1941 Optifine OptiFine_1.9.4_HD_U_B4 96 mods loaded, 95 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9.4-12.17.0.1941.jar) 
	UCHIJA	Forge{12.17.0.1941} [Minecraft Forge] (forge-1.9.4-12.17.0.1941.jar) 
	UCHIJA	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.0.6.0.b65.jar) 
	UCHIJA	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
	UCHIJA	Botania{r1.8-308} [Botania] (Botania-unofficial.r1.8-308.jar) 
	UCHIJA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.9.4-alpha-1.0.0a.jar) 
	UCHIJA	JEI{3.4.3.207} [Just Enough Items] (jei_1.9.4-3.4.3.207.jar) 
	UCHIJA	reborncore{2.5.1.35} [RebornCore] (RebornCore-1.9.4-2.5.1.35-universal.jar) 
	UCHIJA	techreborn{1.3.0.81} [TechReborn] (TechReborn-1.9.4-1.3.0.81-universal.jar) 
	UCHIJA	hammerz{1.8.9-0.1.4.17} [Hammerz] (1.9.4-Hammerz-1.9.4-0.0.1.1.jar) 
	UCHIJA	armorplus{2.4.2} [ArmorPlus] (ArmorPlus2.4.2(1.9.4).jar) 
	UCHIJA	Aroma1997CoreHelper{1.0.6.0.b65} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.0.6.0.b65.jar) 
	UCHIJA	AromaBackup{1.0.1.0.b33} [AromaBackup] (AromaBackup-1.9.4-1.0.1.0.b33.jar) 
	UCHIJA	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.9.4-1.0.1.0.b33.jar) 
	UCHIJA	autopackager{1.6.2} [AutoPackager] (autopackager-1.6.2.jar) 
	UCHIJA	bagginses{2.4.2a} [Bagginses] (Bagginses-1.9.4-2.4.2a.jar) 
	UCHIJA	BaublesHud{3.0.0} [Baubles-Hud] (BaublesHud-1.9.4-3.0.0.jar) 
	UCHIJA	baublesstuff{2.0.10} [Baubles Stuff] (baublesstuff-2.0.10.jar) 
	UCHIJA	BBG{5.0.0} [BetterBedrockGen] (BBG-1.9.4-5.0.0.jar) 
	UCHIJA	BiomesOPlenty{4.1.0.2023} [Biomes O' Plenty] (BiomesOPlenty-1.9.4-4.1.0.2023-universal.jar) 
	UCHIJA	blockdrops{1.0.0} [Block Drops] (Block Drops-1.9.4-1.0.0.jar) 
	UCHIJA	BloodMagic{1.9.4-2.0.1-42} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.0.1-42.jar) 
	UCHIJA	Bloodmoon{1.2} [Bloodmoon] (Bloodmoon-MC1.9.4-1.4.1.jar) 
	UCHIJA	bookshelf{1.2.2.254} [Bookshelf] (Bookshelf-1.9.4-1.2.2.260.jar) 
	UCHIJA	Chameleon{1.9-2.1.4} [Chameleon] (Chameleon-1.9-2.1.4.jar) 
	UCHIJA	chisel{@VERSION@} [Chisel] (Chisel_DEV-MC1.9.4-0.0.4.18.jar) 
	UCHIJA	chiselsandbits{10.2} [Chisels & Bits] (chiselsandbits-10.2.jar) 
	UCHIJA	cookingforblockheads{3.0.7} [Cooking for Blockheads] (CookingForBlockheads-mc1.9.4-3.0.7.jar) 
	UCHIJA	correlatedpotentialistics{1.1.2} [Correlated Potentialistics] (CorrelatedPotentialistics-1.1.2.jar) 
	UCHIJA	NashornLib{1.9.4-1.8.77-1.3.0} [Nashorn Library] (NashornLib-1.9.4-1.8.77-1.3.0.7.jar) 
	UCHIJA	craftingharmonics{1.9.4-1.4.3} [Crafting Harmonics] (craftingharmonics-1.9.4-1.4.3.26.jar) 
	UCHIJA	CustomMainMenu{2.0} [Custom Main Menu] (CustomMainMenu-MC1.9.4-2.0.jar) 
	UCHIJA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJA	DarkUtils{1.1.1.42} [Dark Utilities] (DarkUtilities-1.9.4-1.1.1.47.jar) 
	UCHIJA	ElecCore{1.5.285} [ElecCore] (ElecCore-1.9.4-1.5.285.jar) 
	UCHIJA	deepresonance{1.1.4beta32} [DeepResonance] (deepresonance-1.9.4-1.1.4beta32.jar) 
	UCHIJA	easyBreeding{5.0.0} [Easy Breeding] (easybreeding-1.9.4-4.0.1.jar) 
	UCHIJA	EnderBags{2.0.1} [EnderBags] (EnderBags-1.9.4-2.0.0.jar) 
	UCHIJA	endercore{1.9.4-0.4.0.23-alpha} [EnderCore] (EnderCore-1.9.4-0.4.0.23-alpha.jar) 
	UCHIJA	endercrop{1.9-1.2-1836} [Ender Crop] (endercrop-1.9.4-1.3.1.jar) 
	UCHIJA	EnderIO{1.9.4-3.0.0.36_alpha} [Ender IO] (EnderIO-1.9.4-3.0.0.36_alpha.jar) 
	UCHIJA	EnderZoo{1.9.4-1.2.2.40} [Ender Zoo] (EnderZoo-1.9.4-1.2.2.40.jar) 
	UCHIJA	FastLeaveDecay{1.1} [Fast Leave Decay] (FastLeaveDecay-MC1.9.4-1.2.1.jar) 
	UCHIJA	flatcoloredblocks{mc1.9.4-v3.0} [Flat Colored Blocks] (flatcoloredblocks-mc1.9.4-v3.0.jar) 
	UCHIJA	reborncore-mcmultipart{2.5.1.35} [reborncore-MCMultiPart] (RebornCore-1.9.4-2.5.1.35-universal.jar) 
	UCHIJA	Tesla{1.1.0.24} [TESLA] (Tesla-1.9.4-1.1.0.24.jar) 
	UCHIJA	fluxedredstone{2.2.1.44} [FluxedRedstone] (FluxedRedstone-2.2.1.44.jar) 
	UCHIJA	fe{1.2.1} [Food Expansion] (FoodExpansion1.2.2-1.9.4.jar) 
	UCHIJA	forestry{5.0.4.124} [Forestry] (forestry_1.9.4-5.0.4.124.jar) 
	UCHIJA	grapplemod{1.9.4-v6} [Grappling hook mod] (grapplemod-1.9.4-v6.jar) 
	UCHIJA	Harvest{1.9.4-1.0.1-5} [Harvest] (Harvest-1.9.4-1.0.1-5.jar) 
	UCHIJA	HardcoreQuesting{1.9.4-5.0.0beta3} [Hardcore Questing Mode] (HQM-New Heights-1.9.4-5.0.0beta3.jar) 
	UCHIJA	InfernalMobs{1.7.0} [Infernal Mobs] (InfernalMobs-1.9.4.jar) 
	UCHIJA	inventorytweaks{1.61-dev-53-0736dc3} [Inventory Tweaks] (InventoryTweaks-1.61-dev-53.jar) 
	UCHIJA	IronChest{6.0.141.782} [Iron Chest] (ironchest-1.9.4-6.0.141.782.jar) 
	UCHIJA	itemscroller{0.5.0} [Item Scroller] (itemscroller-1.9.4-0.5.0.jar) 
	UCHIJA	journeymap{1.9.4-5.2.0} [JourneyMap] (journeymap-1.9.4-5.2.0-unlimited.jar) 
	UCHIJA	jeresources{0.4.5.31} [Just Enough Resources] (JustEnoughResources-1.9.4-0.4.5.31.jar) 
	UCHIJA	mantle{1.9.4-0.10.1.jenkins142} [Mantle] (Mantle-1.9.4-0.10.1.jenkins142.jar) 
	UCHIJA	testdummy{1.10} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.11.jar) 
	UCHIJA	moreoverlays{1.3} [MoreOverlays] (moreoverlays-1.3-mc1.9.4.jar) 
	UCHIJA	Morphtool{GRADLE:VERSION-GRADLE:BUILD} [Morph-o-Tool] (Morph-o-Tool-1.0-2.jar) 
	UCHIJA	Morpheus{1.9.4-3.1.3} [Morpheus] (Morpheus-1.9.4-3.1.3.jar) 
	UCHIJA	nethermetals{1.1.0} [Nether Metals] (NetherMetals_1.9-1.1.0.jar) 
	UCHIJA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9.4-4.0.1.jar) 
	UCHIJA	nmsot{1.1.4-mc1.9.4} [No Mob Spawning on Trees] (NoMobSpawningOnTrees-1.1.4-mc1.9.4.jar) 
	UCHIJA	notenoughwands{1.3.4} [Not Enough Wands] (notenoughwands-1.9.4-1.3.4.jar) 
	UCHIJA	fodc{1.8.2} [Ore Dictionary Converter] (OreDictionaryConverter-1.8.2.jar) 
	UCHIJA	packingtape{0.5.1} [Packing Tape] (PackingTape-1.9.4-0.5.1.jar) 
	UCHIJA	progressiveautomation{1.6.46} [Progressive Automation] (ProgressiveAutomation-1.9.4-1.6.46.jar) 
	UCHIJA	Psi{beta-33} [Psi] (Psi-beta-33.jar) 
	UCHIJA	quantumflux{2.0.7} [QuantumFlux] (quantumflux-1.9.4-2.0.7.jar) 
	UCHIJA	Quark{beta-21} [Quark] (Quark-beta-21.jar) 
	UCHIJA	randomthings{3.7.3} [Random Things] (RandomThings-MC1.9.4-3.7.3.jar) 
	UCHIJA	refinedstorage{0.7.3} [Refined Storage] (refinedstorage-0.7.3.jar) 
	UCHIJA	ResourceLoader{1.5} [Resource Loader] (ResourceLoader-MC1.9.4-1.5.jar) 
	UCHIJA	rftools{4.51} [RFTools] (rftools-1.9.4-4.51.jar) 
	UCHIJA	rftoolsdim{4.23beta40} [RFTools Dimensions] (rftoolsdim-1.9.4-4.23beta40.jar) 
	UCHIJA	ScreenshotUploader{1.9.4-2.4.0} [Screenshot Uploader] (ScreenshotUploader-1.9.4-2.4.0.jar) 
	UCHIJA	shadowmc{3.3.6} [ShadowMC] (ShadowMC-1.9.4-3.3.6.jar) 
	UCHIJA	ShieldHider{1.0.1} [Shield Hider] (ShieldHider-1.0.1_1.9.4.jar) 
	UCHIJA	simpleretrogen{3.0.1+6} [Simple Retrogen] (simpleretrogen-1.9.4-3.0.1+6.jar) 
	UCHIJA	SleepingBag{1.2.0} [Sleeping Bag] (SleepingBag-1.9.4-1.2.0.jar) 
	UCHIJA	solarvillage{1.0.0.4} [Solar Village] (SolarVillage-1.9.4-1.0.0.4.jar) 
	UCHIJA	soulshardstow{1.9.4-2.4.0-28} [Soul Shards - The Old Ways] (SoulShards-TOW-1.9.4-2.4.0-28.jar) 
	UCHIJA	StorageDrawers{1.9-3.1.7} [Storage Drawers] (StorageDrawers-1.9-3.1.7.jar) 
	UCHIJA	substratum{1.3.2.0} [Substratum] (Substratum-1.9.4-1.3.2.0.jar) 
	UCHIJA	tconstruct{1.9.4-2.3.1.jenkins229} [Tinkers' Construct] (TConstruct-1.9.4-2.3.1.jenkins229.jar) 
	UCHIJA	theoneprobe{1.0.4} [The One Probe] (theoneprobe-1.9.4-1.0.4.jar) 
	UCHIJA	tombmanygraves{1.9.4-2.1.0} [Tomb Many Graves] (TombManyGraves-1.9.4-2.1.0.jar) 
	UCHIJA	wailafeatures{0.3.1.10} [WAILA Features] (WAILA-features-1.9.4-0.3.1.10.jar) 
	UCHIJA	WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.9-1.1.7.jar) 
	UCHIJA	weaponsplus{1.8.0} [WeaponsPlus] (WeaponsPlus1.8.0.jar) 
	UCHIJA	xprings{1.1.0} [Experience Rings] (xprings-1.1.0.jar) 
	UD	craftingharmonicsPreloader{1.9.4-1.4.3} [Crafting Harmonics Preloader] (minecraft.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Bloodmoon-MC1.9.4-1.4.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
HarmonyPreloader (craftingharmonics-1.9.4-1.4.3.26.jar)
  org.winterblade.minecraft.harmony.asm.PotionRemovedHookTransformer
LoadingPlugin (ResourceLoader-MC1.9.4-1.5.jar)
  lumien.resourceloader.asm.ClassTransformer
CoreXU2 (extrautils2-1.9.4-alpha-1.0.0a.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
Reborn Core ASM (RebornCore-1.9.4-2.5.1.35-universal.jar)
  reborncore.asm.RebornClassTransformer
LoadingPlugin (RandomThings-MC1.9.4-3.7.3.jar)
  lumien.randomthings.asm.ClassTransformer
CorePlugin (FluxedRedstone-2.2.1.44.jar)
  
FMLPlugin (InventoryTweaks-1.61-dev-53.jar)
  invtweaks.forge.asm.ContainerTransformer
CoreMod (Aroma1997Core-1.9.4-1.0.6.0.b65.jar)
  
EnderCorePlugin (EnderCore-1.9.4-0.4.0.23-alpha.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1 NVIDIA-10.8.14 310.42.15f01' Renderer: 'NVIDIA GeForce GT 650M OpenGL Engine'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	OptiFine Version: OptiFine_1.9.4_HD_U_B4
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 NVIDIA-10.8.14 310.42.15f01
	OpenGlRenderer: NVIDIA GeForce GT 650M OpenGL Engine
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by whatthedrunk** [comment]
Refined storage is not part of the pack...
