### ISSUE TITLE
Shift-clicking to craft Iron Block creates Iron Plate instead

### ISSUE THREAD

**Issue by Apocryphai** [whatthedrunk/allthemods#40]
As title, fill crafting grid (vanilla crafting table) with iron ingots, shift-click to craft Iron Blocks, receive two Substratum Iron Plates instead.

Edit: Actually cannot craft Iron Blocks at all, however I try it I get Iron Plates.

**Comment by Carrots4U** [comment]
UniDict has contacted us and has said it will be fixed in the next update. Thanks for reporting!
