### ISSUE TITLE
ATM Expert, several energized stones from roots are uncraftable

### ISSUE THREAD

**Issue by Saereth** [whatthedrunk/allthemods#400]
Reported the issue to roots directly, cross posting here 
https://github.com/RootsTeam/Roots/issues/180

Issue Description:
Several recipes for energized stones all produce acceleration stones

What happens:
When attempting to craft grower stones or several other stuns, accerlator stone is created

What you expected to happen:
a grower stone to be created

Steps to reproduce:

1. attempt to craft a grower stone
2. collect your accelerator stone when the ritual completes

Version of All the Mods:
1.0.23

Added mods (Optifine, Fastcraft, etc.):

1. Optifine
2. Re-auth

I suspect the added oredict from ATM may be the issue in roots_expert.zs, this issue is not present in skyfactory 3, same version of roots.

**Comment by al132** [comment]
Thanks for doing a little research, the oredict thing most likely is the issue. It's a bit inconvenient, but it's not a big deal to work around it. I'll take a look at this when i'm working on the next update.

**Comment by al132** [comment]
Should be fixed now in 1.0.24, comment if it's still a problem.
