### ISSUE TITLE
[ATM2 v0.43] Crash when clicking the creative search tab

### ISSUE THREAD

**Issue by CorwinJV** [whatthedrunk/allthemods#401]
Issue Description:
When you click on the creative search tab the game crashes with the following log:
http://pastebin.com/VWSaBsHq

Note: Make sure you update to the latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:
Clicking on the creative search tab results in a crash

What you expected to happen:
The client doesn't crash

Steps to reproduce:

1. Create a new single player world with creative mode enabled
2. hit 'e'
3. click on the search tab (compass icon)
4. observe crash
...

Version of All the Mods: allthemods 2 v0.43

Added mods (Optifine, Fastcraft, etc.): None
...

**Comment by whatthedrunk** [comment]
Moved to https://github.com/AllTheMods/ATM-2/issues/1
