### ISSUE TITLE
ATM:E 1.0.23 Missing Serverfiles

### ISSUE THREAD

**Issue by jfschubert** [whatthedrunk/allthemods#402]
Just wanted to update my Server but noticed that the Serverfiles fro ATM:E 1.0.23 are missing on Curseforge (+1 More is missing)

**Comment by OrdinatorStouff** [comment]
We found out that the way we were distributing server files before was a direct violation of the Mojang Minecraft EULA. We are working on a new solution and hope to have server files available soon for future updates.  
  
In the meantime, if you have an existing server and the forge version has not changed between pack update you can delete the folders: mods, config, scripts from your server directory and then copy those same folders over from an updated client.
