### ISSUE TITLE
JEI disappears after updating to latest version of ATM

### ISSUE THREAD

**Issue by bignate1011** [whatthedrunk/allthemods#405]
Issue Description: After updating to the latest version of ATM via the curse launcher (v1.60) I went into my sp world and the JEI overlay is gone. Pressing ctl-o does not bring up the overlay. JEI is showing as active in game under the mod tab and i can access all the config files. Rebinding the overlay key also does not fix this. This is the case in all of my worlds as well including my creative test world. Rolling back to v1.59 does bring JEI back

Note: Make sure you update to the latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:JEI will not show when accessing inventories or pressing E

What you expected to happen: 

Steps to reproduce:

1.
2.
3.
...

Version of All the Mods:

Added mods (Optifine, Fastcraft, etc.):

1.Fullscreen Windowed Borderless for Minecraft
2.
3.
...

**Comment by whatthedrunk** [comment]
Eh sorry fixed in 60b (should be approved with curse any minute now). You just need to downgrade JEI.

**Comment by bignate1011** [comment]
Thx!
