### ISSUE TITLE
Server crash (caused by calculator/enderio) after update to 1.60 (on problem chunk loaded)

### ISSUE THREAD

**Issue by JaSpr** [whatthedrunk/allthemods#406]
Server crashes after update to 1.60.

[Crash Report.](https://gist.github.com/JaSpr/300540a78f16da2873fa45c937bec967)

Appears to be caused by an Algorithm Separator (Calculator) connected to EnderIO Conduits.

**Comment by JaSpr** [comment]
both forge options to remove erroring blocks were enabled, and this did not resolve the issue.

/setblock did not work, because it wouldn't allow setting a block in an unloaded chunk.

**Comment by meatball0417** [comment]
I have this issue, too.

Also crashed by some calculator and ender io conduicts things.
But downgraded to 1.5.9 is ok.

Also have you noticed the draconic fusion recipe disappeared?

**Comment by mercsniper** [comment]
Also affects 1.60b. Seems to be tied to multiple blocks: advanced furnace, stone separator are two that I have found.

**Comment by whatthedrunk** [comment]
I finally got around to just removing Calculator in 2.0 going forward.

**Comment by OrdinatorStouff** [comment]
Due to repeated issues with calculator versions causing crashes and world corruption, it has been completely removed from ATM1 v2.0 an onwards
