### ISSUE TITLE
[Expert] Creative Drum Not usable by non-OP

### ISSUE THREAD

**Issue by OrdinatorStouff** [whatthedrunk/allthemods#407]
**Issue Description:** Creative drum can be crafted (custom recipe) but fluid can not be set by non-op players. Non-op players can "clear" the type in a crafting grid but then can't set it after clearing again.

**What happens:** Endgame creative recipe item is useless 

**What you expected to happen:** Players can use the drum

**Steps to reproduce:**
1. Place a creative drum
2. Non-op player can't set type
3. Op player can set type and non-op can "use" but can't change type

**Version of All the Mods:** 1.0.23

**Added mods:**
1. Foamfix .0.5.3 anarchy
2. sampler
3. Tickprofiler
4. MoreCommands 4

_One possible suggestion is to add custom recipes to set type i.e. Creative Drum + Bucket of Lava = Lava Creative Drum_

**Comment by al132** [comment]
Fixed in v1.0.24, replaced with pressure pipes equivalent. The drum can be "traded in" by crafting it alone.
