### ISSUE TITLE
[Expert] A very strange crash

### ISSUE THREAD

**Issue by raphydaphy** [whatthedrunk/allthemods#410]
Issue Description: random screen jittering and shaking then crash

Note: Make sure you update to the latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:
Screen shook violently for a few minutes, so I relogged and crashed instantly.
heres stack trace: http://pastebin.com/BpzjfnvD

What you expected to happen:
No violent shaking and no crashing

Steps to reproduce:

1. Not sure
2. It just suddenly
3. Happened

The Version of All the Mods:
Expert 1.0.24

Added mods (Optifine, Fastcraft, etc.):

1. Vitality Expert Tweaks
2. Optifine
3. Vitality

**Comment by al132** [comment]
Was there any apparent trigger? I've experienced something of this sort before on death when I was working on a different pack.

**Comment by raphydaphy** [comment]
there were some invisible blue slimes nearby that were hitting me, and they made me shoot up in the air and that happened ;( not sure what else tho i wasn't rly paying attention D:

**Comment by OrdinatorStouff** [comment]
Sounds like possibly a potion effect? Mobs can sometimes cause effects on players like nausea (screen shaking?) and maybe there was a crash ticking the player or the mob or something (i.e. net.minecraft.entity.player.EntityPlayer from the log)

Are you able to reproduce the crash in any way?

**Comment by raphydaphy** [comment]
I can't reproduce it, I tried ;( but it was nothing like nauesa, and I had no active potion effects when I checked.

**Comment by Dijkstra1** [comment]
From the crash report, I can tell the death and the crash are unrelated when you relog your just unlucky enough to get IC2 crash that sometimes happens when you rejoin the server, the IC2 are aware but there is not much about it, as it down to another mod adding a null recpie most likely reciper tweatker, and even then the fault is with vanilla code

**Comment by al132** [comment]
Closing for now, reopen if anyone can reproduce
