### ISSUE TITLE
Pack crashes upon loading

### ISSUE THREAD

**Issue by Volaunis** [whatthedrunk/allthemods#411]
Issue Description: Pack crashes upon loading. Crashlog : http://pastebin.com/hT62GqKb

Note: Make sure you update to the latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: Pack crashes upon loading.

What you expected to happen: The pack not to crash upon loading.

Steps to reproduce:

1. Load pack
2. Crash
3.
...

The Version of All the Mods: 1.60b

Added mods (Optifine, Fastcraft, etc.): None

1.
2.
3.
...

**Comment by Dijkstra1** [comment]
Do you still get this on the latest version

**Comment by OrdinatorStouff** [comment]
Also seems to be a pretty old version of java (1.8.0_25) -- updating that to latest version wouldn't hurt. Are you using curse to launch the pack or some other launcher?

**Comment by Volaunis** [comment]
I just did something that I should've done in the first place, which was to do a clean profile. That launched fine. I guess I must've added something to the pack myself at one time and forgot about it.
Sorry for the inconvenience.
Also thanks for the java hint, don't know why it didn't inform me on it's own, but that's updated now as well.
