### ISSUE TITLE
[ATM:E] Recipe changes needed for jetpacks

### ISSUE THREAD

**Issue by FallenEagle1** [whatthedrunk/allthemods#415]
This deals with Simply Jetpacks 2 that is within the pack. Apparently there were some jetpacks that were added to the mod: iron, gold, and diamond jetpack. The older jetpacks seem reasonable for this pack, but those three are default and can allow for a top tier jetpack in early game.

Figured reasoning wasn't really needed, but I also didn't know if you guys knew about this change to the mod.

**Comment by al132** [comment]
I have fixed this now, i'll close this issue when I release the new version

**Comment by al132** [comment]
I have decided
