### ISSUE TITLE
[ATMexpert] Server doesn't start (Ubuntu)

### ISSUE THREAD

**Issue by Kriandir** [whatthedrunk/allthemods#416]
Issue Description: I'm  having a bit of a trouble trying to make the ServerStart.sh file to run the server.

Note: Make sure you update to the latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:
When I tried to run the ServerStart.sh at first i got the following syntax error in the picture below:
![errorinbashcode](https://cloud.githubusercontent.com/assets/14076653/23019924/db1175ae-f444-11e6-80d4-ff85b972eff8.png)

So I decided to escape the characters that were conflicting which made the server permanently looping through the starting sequence never really starting as can be seen in the picture below:

![restarting server](https://cloud.githubusercontent.com/assets/14076653/23019933/e5c206a8-f444-11e6-96e2-bdf80ce60ba2.png)

What you expected to happen:
The server to start
Steps to reproduce:

1. download the server files
2. sh ServerStart.sh
3. edit bash file escaping ( and ) by use of ''
4. sh ServerStart.sh again

The Version of All the Mods:
ATMexpert1.0.24

...

**Comment by Dijkstra1** [comment]
This script needs to be run as bash not sh or make the executable and just call it ./Serverstart.sh

**Comment by Kriandir** [comment]
Running it using bash ServerStart.sh seems to have fixed problem 1.
However, the server keeps restarting. It doesn't matter whether i force it to reinstall or not.

![serverrestarting](https://cloud.githubusercontent.com/assets/14076653/23042737/137b4744-f49a-11e6-97ff-1925db3cd789.png)

**Comment by OrdinatorStouff** [comment]
Have you already set eula=true in the eula.txt file?

If so, can you pastebin the crash-log (if any) or fml-server-latest.log if no crash report?

**Comment by Kriandir** [comment]
owh man i feel like an idiot.. totally forgot to set the eula = true...
Thanks for all the help
