### ISSUE TITLE
Server crash no reason given ATM1

### ISSUE THREAD

**Issue by mercsniper** [whatthedrunk/allthemods#418]
Issue Description:
Latest ATM1 2.1 Server

Note: Make sure you update to the latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: Server stops after about 15seconds of running post initialization

What you expected to happen:
Server Running

Steps to reproduce:

1. Start Server
2. Wait for Initialization
3. Server says "Stopping"
...

The Version of All the Mods:

Added mods (Optifine, Fastcraft, etc.):

1. No Mods
2.
3.
[fml-server-latest.txt](https://github.com/whatthedrunk/allthemods/files/783521/fml-server-latest.txt)

**Comment by OrdinatorStouff** [comment]
Is this a new server setup (or an old/existing one that no longer works)?

**Comment by mercsniper** [comment]
Server from 1.3v updated at every release.

**Comment by OrdinatorStouff** [comment]
We've been troubleshooting on discord, so far AM2 and refraction/liblib are not culprits. Problem is happening even on new world

**Comment by OrdinatorStouff** [comment]
turns out it was liblib and forgelin -- they had known issues and already fixed in newer versions. Once pack updates this will be resolved.
