### ISSUE TITLE
[Expert]  Chaos Shard unattainable

### ISSUE THREAD

**Issue by Dijkstra1** [whatthedrunk/allthemods#419]
Issue Description:

The fight with the chaos guardian is currently bugged, which means he will go away mid fight and if it is not killed then u can not get the chaos shards, which means no ATM stars with mean no nice stuff. The mod author knows it is bugged and chat message pops saying so as you get near chaos island, so until this gets fixed can not lock things behind it as it makes them unattainable.

What happens:
Dargon disappears, can not kill, no shards, no ATM star 

What you expected to happen:
Kill dragon gets shards, make atm star, profit

Steps to reproduce:

1. Go to the end
2. find chaos island
3. fight dragon 
4. loss the dragon
5. cry

The Version of All the Mods:
like always latest as of 18/02/17

Added mods (Optifine, Fastcraft, etc.):

1.
2.
3.
...

**Comment by al132** [comment]
I have replaced chaos shards/cores with opinium cores in 1.0.25, closing
