### ISSUE TITLE
1.10.2v1.0 Simple Harvest may be redundant

### ISSUE THREAD

**Issue by DeathOfTime** [whatthedrunk/allthemods#42]
Simple harvest's functionality is covered by both Quark, and EnderCore. Not together, they both have the full functionality, even taken separately. It does look fairly easy to configure. Yet is using default configs.

Its config file is "Harvest.json" It looks very similar to endercores. Probably just need to copy past a block of code and change the values to math the different crops. Right now it is only covering the vanilla crops. Pretty sure their are mods covering some of the other crops. A few could use being added though. Like the "bean" from "random things".

Just wondering if it is really needed in the pack at this time?

**Comment by whatthedrunk** [comment]
Thanks for letting me know, I will take a look at that and remove it for this weeks beta.

**Comment by Carrots4U** [comment]
Removed in the next update.
