### ISSUE TITLE
[ATM 1.10.2] Mod Request - Sanguimancy

### ISSUE THREAD

**Issue by Poshtester63** [whatthedrunk/allthemods#421]
Hello There

Would really appreciate it if you would add the [Sanguimancy](https://minecraft.curseforge.com/projects/sanguimancy) add-on for Blood Magic.

It adds, among other things:

The Drill of the Dead ritual, which can be combined with an existing mob farms.
Support for OpenComputers interactions.
Soul network dimension (not sure with this one... haven't tried it last play through).

**Comment by whatthedrunk** [comment]
Added to the correct place. https://github.com/whatthedrunk/allthemods/issues/173
