### ISSUE TITLE
ATM2 .049 StartServer.sh is not Unix friendly

### ISSUE THREAD

**Issue by saytheb** [whatthedrunk/allthemods#424]
The current StartServer.sh script in the .49 ATM2 server files is currently not *NIX friendly, requiring running it through dos2unix to remove the windows style line returns.

Minor but annoying issue :)

**Comment by ozhound** [comment]
We are aware of this, it has to do with how the files are being edited in notepad prior to being included in the server files download. We are working on a script that gets its variables from an external config file. Both the bat and sh file should never need to be edited by Linux noobs and broken
