### ISSUE TITLE
[Lite] TheOneProbe spamming console when looking at certain blocks

### ISSUE THREAD

**Issue by Babbie** [whatthedrunk/allthemods#427]
Issue Description:
Whenever anyone on the server looks at a block in, but not limited to, the following list, a message is put in the console at a rate of about 10 per second: Oak fence gate (Minecraft), Marble (Quark), Chunk Loader (ChickenChunks), Survival Generator (Extra Utils 2) and lots more.
The following message is printed:
```
[Server thread/INFO] [theoneprobe]: HarvestLevel out of bounds (less than 0). Found -1
```

Steps to reproduce:

1. Look at a vanilla oak fence gate.
2. Watch the server go nuts.

The Version of All the Mods:
All the Mods Lite v2.3

**Comment by PotDucky** [comment]
Fixed in later versions.
