### ISSUE TITLE
Recipe Conflicts in ATM2

### ISSUE THREAD

**Issue by SpeedSlider** [whatthedrunk/allthemods#428]
Issue Description: 
There is a conflict between Literal Ascensions carving tool and recipes in Roots 2 and Pam's Harvest Craft.

Note: Make sure you update to the latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:
The crafting recipe for Literal Ascensions carving tool gives you either a Roots knife or a Pam's Skillet

What you expected to happen:
I want to use the Literal Ascension carving tool to make ladder rungs on the wall.

Steps to reproduce:

1. Place crafting items for carving tool in a crafting bench.
2.
3.
...

The Version of All the Mods:
0.50

Added mods (Optifine, Fastcraft, etc.):

1. Optifine
2. Faithful Texture Packs :P
3.
...

**Comment by whatthedrunk** [comment]
Moved to https://github.com/AllTheMods/ATM-2/issues/2 I should have this fixed next update.
