### ISSUE TITLE
[1.10.2 v1.0] Stuck in bed after sleeping

### ISSUE THREAD

**Issue by alphademic** [whatthedrunk/allthemods#43]
Occasionally, after sleeping in a bed players will get stuck laying on the ground like day never came.  

Clicking the "leave bed" button does nothing.  The only way to get out of bed is to have someone break the bed for you or issue a /kill or /kick command.  Rarely, breaking the bed doesn't work and players must still be /kicked or /killed.

Modpack version: allthemods 1.10.2 v0.8  (release)
Has happened since at least allthemods 1.9.4 v1.0 as thats when I started a server.

**Comment by whatthedrunk** [comment]
Yeah it's been happening to me too but not sure I have noticed it in version 1.0. I will keep this open until we can confirm it is actually fixed.

**Comment by Carrots4U** [comment]
It's been reported in Quark, but there is no real sign of what is causing it.

**Comment by whatthedrunk** [comment]
Seems to have been fixed in 1.0. Please reopen if its still happening.

**Comment by Carrots4U** [comment]
alphademic says it is still happening.

**Comment by mrsmn** [comment]
Still happening in 1.1 as well.

**Comment by alphademic** [comment]
Just wanted to update that it's happening in 1.4.  Anything we can do to help out?

**Comment by Carrots4U** [comment]
Can anyone confirm this is still occurring in the latest version?

**Comment by DietmarKrause** [comment]
not only a bug with this modpack. Also in FTB Unstable 1.10 and - probably - in Vanilla. I made a post already in ftb forum: http://forum.feed-the-beast.com/threads/alpha-unstable-pack-bug-reports.42413/page-13#post-1695550

**Comment by DietmarKrause** [comment]
I see this bug far more often right after teleporting or leaving the nether. Leave the nether, find out it is night try to sleep and almost for sure you will get this problem.

**Comment by DietmarKrause** [comment]
related issue (i think): [URL="http://forum.feed-the-beast.com/threads/alpha-unstable-pack-bug-reports.42413/page-14#post-1709470"]{Alpha} Unstable Pack: Bug Reports[/URL] if you are in the "stuck in bed" state after teleporting you are almost for sure unvisible to others (but cannot recognize ist if in SP).  Also see here: https://github.com/Vazkii/Quark/issues/115. Hope i can help

**Comment by Carrots4U** [comment]
This is has been diagnosed as a vanilla bug, so there is nothing we can do unless Mojang themselves upload a fix. Sorry!

**Comment by PapiDimmi** [comment]
Still happening.
