### ISSUE TITLE
Creeperhost not playing well with version 2.2

### ISSUE THREAD

**Issue by jcthiel13** [whatthedrunk/allthemods#432]
Issue Description: Creeperhost not playing well with version 2.2

Note: Make sure you update to the latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: Crashes very shortly after startup with log "Can't revert to frozen GameData state without freezing first" on debug along with crash report saying that there is a duplicate forge multiblock mod on the server also in description it says "Exception in server tick loop" which I have seen in other error codes on this site.

What you expected to happen: ..... I expected the server to start normally after update

Steps to reproduce: 

1. I have tried creating new instance and get same errors on fresh server
2. Reverting to 1.59 does not create the same problem
3.
...

The Version of All the Mods: 2.2

Added mods (Optifine, Fastcraft, etc.): NONE

1.
2.
3.
...

Attached is the log from the original server with save-game for integrity purposes.

[New Text Document (3).txt](https://github.com/whatthedrunk/allthemods/files/798573/New.Text.Document.3.txt)

**Comment by ThomasAunvik** [comment]
Duplicate Mods:
	mcmultipart : /home/minecraft/mc-instances/mc-586be139620e2/mods/1.10.2/MCMultiPart-experimental-2.0.0_88-universal.jar
	mcmultipart : /home/minecraft/mc-instances/mc-586be139620e2/mods/1.10.2/MCMultiPart-1.4.0-universal.jar

Try deleting one of those.

**Comment by jcthiel13** [comment]
Deleting experimental seemed to do the trick. For reference of anyone else, just connect via the wrapper given by CreeperHost then delete the file in the path commented above.
