### ISSUE TITLE
[Expert] Disabled items in Bonus Chest.

### ISSUE THREAD

**Issue by ThomasAunvik** [whatthedrunk/allthemods#434]
Issue Description:

Note: Make sure you update to the latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:

When starting a new singleplayer world with Bonus Chest enabled, you have a chance of spawning some items, but somehow disabled items can get in the chest.

Also, when you use the tool the red disabled dissapears.

What you expected to happen:

Not to spawn disabled items.

Steps to reproduce:

1. Create a new world with Bonus Chest enabled.
2. Open Chest
3. Use Tool/Item

Added mods (Optifine, Fastcraft, etc.):
None

**Comment by goosezilla** [comment]
Just dont use the bonus chest.
