### ISSUE TITLE
Broken Sandstone Textures (Modpack V2.3, Optifine D6)

### ISSUE THREAD

**Issue by Alaric323** [whatthedrunk/allthemods#435]
Greetings,
When using connected textures (I'm using Optifine to do it), sandstone blocks break when it's not the top of a stack of them.  This started happening between version 2.1 and 2.3 (I skipped 2.2 due to speed of released updates).

Any ideas?
![image](https://cloud.githubusercontent.com/assets/4038592/23319637/735eacd0-faa5-11e6-92e4-817b86162be3.png)

**Comment by PotDucky** [comment]
No official support for Optifine, Unable to reproduce myself.
