### ISSUE TITLE
[ATM] [1.10.2] [v2.3] Not able to craft IC2 Neutron Reflector using Crafting Table

### ISSUE THREAD

**Issue by mouseodoom** [whatthedrunk/allthemods#437]
Issue Description:
Not possible to craft an IC2 Neutron Reflector using a Crafting Table, or Refined Storage Crafting Grid.

What happens:
Put the materials for an IC2 Neutron Reflector into a Crafting Grid in the correct shape. Instead of an IC2 Neutron Reflector, you can only craft a Tech Reborn Neutron Reflector. 

What you expected to happen:
I should be able to click the little arrow on the right side of the Crafting Table GUI to switch the recipe, this does not work. 

Regression: 
This works as expected on a Forestry Worktable. 

Steps to reproduce:

1. Put materials for Neutron Reflector into Crafting Table
2. Click arrow to attempt to change recipe
3. Nothing happens

*This issue is problematic because the Tech Reborn and IC2 Neutron Reflectors are not the same and cannot be used in the same recipes. I am going to create a different issue for that. 

The Version of All the Mods:
ATM 1.10.2 v2.3

Added mods (Optifine, Fastcraft, etc.):
None

**Comment by mouseodoom** [comment]
I was looking here: https://minecraft.curseforge.com/projects/mystical-agriculture and it occurs to me that the mod author of Mystical Agriculture might be the correct recipient of this issue.

**Comment by PotDucky** [comment]
Will be fixed in next ATM1 Version (2.53)

https://github.com/AllTheMods/ATM-1/commit/78ff7867860004cc4047b5496bec58c8bf488f97
