### ISSUE TITLE
[ATM] [1.10.2] [v2.3] IC2 & TechReborn Neutron Reflectors are not interchangeable. 

### ISSUE THREAD

**Issue by mouseodoom** [whatthedrunk/allthemods#438]
Issue Description:
IC2 & TechReborn Neutron Reflectors are not interchangeable. 

What happens:
-You cannot use the IC2 Neutron Reflector to make a TechReborn Thick Neutron Reflector and vice versa. This is recursive; Thick Neutron Reflectors are also not interchangeable, neither are Iridium, etc.
-The Ore Converter does not let you turn an IC2 Neutron Reflector into a TechReborn Neutron Reflector

What you expected to happen:
You should be able to use the TechReborn Neutron Reflector to make IC2 Thick Neutron reflectors and vice-versa. 

Steps to reproduce:

1. Make four TechReborn Neutron Reflectors 
2. Make four IC2 Neutron Reflectors (You have to use a Forestry Worktable due to https://github.com/whatthedrunk/allthemods/issues/437
3. Try to use the IC2 Neutron Reflectors to make a TechReborn Thick Neutron Reflector
4. Try to use the TechReborn Neutron Reflectors to make a IC2 Thick Neutron Reflector

*This is a problem because this obstructs the path to the Molecular Transformer.

The Version of All the Mods:
ATM 1.10.2 v2.3
Added mods (Optifine, Fastcraft, etc.):
None

**Comment by Mercenary4Hire** [comment]
I ran into this problem on the Hermitpack pack, i fixed 1 recipe on my server with this minetweaker script
its for the Thick Neutron reflector which is required for advanced solars, something probably can be done in this pack for similar problems

recipes.addShaped(<ic2:thick_neutron_reflector>, [[<ore:plateCopper>, <techreborn:part:26>, <ore:plateCopper>], [<techreborn:part:26>, <ore:plateCopper>, <techreborn:part:26>], [<ore:plateCopper>, <techreborn:part:26>, <ore:plateCopper>]]);

**Comment by PotDucky** [comment]
Will be fixed in next ATM1 Version (2.53)

https://github.com/AllTheMods/ATM-1/commit/78ff7867860004cc4047b5496bec58c8bf488f97
