### ISSUE TITLE
[1.10.2 v1.0] Typo in nether_ores.zs - prevents nether ore recipes from loading

### ISSUE THREAD

**Issue by jmcaffee** [whatthedrunk/allthemods#44]
```
val oreTin = <substratum:OreBlock:1>;
```

should be:

```
val oreTin = <substratum:ore:1>;
```

**Comment by whatthedrunk** [comment]
Of course the only one I do has a typo.. I will be working on a new beta this weekend and will make sure to get this fixed, thank you.

**Comment by Carrots4U** [comment]
Fixed in the next update, also added End Ore recipes.
