### ISSUE TITLE
[ATM:E] Enderio Farming station doesn't recognize the flint hoe

### ISSUE THREAD

**Issue by ScottRadish** [whatthedrunk/allthemods#441]
Issue Description: The farming station doesn't recognize the flint hoe

What happens: The farming station won't accept the flint hoe, although it takes the flint axe. Since the stone hoe is disabled and the wood hoe requires wildwood, there are not any good options for a disposable axe other than the flint hoe. It should work.

**Comment by goosezilla** [comment]
pretty sure you can use an unbreakable mattock

**Comment by al132** [comment]
Should be fixed now in 1.0.28
