### ISSUE TITLE
Install batch file does not work 2.4b

### ISSUE THREAD

**Issue by Marker248** [whatthedrunk/allthemods#445]
Issue Description:

Note: Make sure you update to the latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: 
The installation Batch file fails while trying to download forge files.

What you expected to happen:
Latest version of forge should be downloaded and the server should start
Steps to reproduce:

1.Tried running on my client machine but failed.
2.Looked at Batch file in text editor and there were no line breaks, not sure if that's actually an issue but so far it does not work
3.
...

The Version of All the Mods:
2.4b

...
Could Not Find D:\allthemods2.4b\Server Files\Full\forge-index.html
Could Not Find D:\allthemods2.4b\Server Files\Full\forge.jar
Could Not Find D:\allthemods2.4b\Server Files\Full\forge-installer-temp.jar
The system cannot find the file specified.

**Comment by OrdinatorStouff** [comment]
Is this still not working in the latest pack version? PotDucky, did you UNIXify the bat file as well? It shouldn't matter but there could be a few lines that might not play well with UNIX style endings only maybe?

**Comment by Marker248** [comment]
I haven't tested the latest beta. Been waiting for a full release.

-------- Original message --------

**Comment by OrdinatorStouff** [comment]
Ok, fair enough. We'll check it out after @PotDucky gets through some more serious stuff like people's old saves not being able to be loaded and whatnot.

**Comment by PotDucky** [comment]
Fixed in 2.52 release version.
