### ISSUE TITLE
[ATM:E] official server Rockhounding issues

### ISSUE THREAD

**Issue by Withlos** [whatthedrunk/allthemods#446]
Issue Description:Crash, dupe, and server crash in steps.

Note: Make sure you update to the latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:
Crashes to desktop and dupes generator.

What you expected to happen:
Either an invalid message( but rockhounding doesn't display warnings or errors) or no crashing

Steps to reproduce:

1.Any ATM Rockhounding machine
2.Place Forestry Electric generator next to machine.( might work with other single block generators need to test)
3.Crash to desktop
4.Rejoin. One Electric gen placed and One still in hand.(dupe glich)
5.Place induction coil upgrade into machine then remove. Server crash. (Sorry to the people on the server last night about 2am CST)

The Version of All the Mods: 
allthemods Expert v1.0.28
Added mods (Optifine, Fastcraft, etc.):

1.n/a

**Comment by al132** [comment]
Do you know if the server is using sponge forge? Also, could you please give me the crash log?

**Comment by Withlos** [comment]
[crash-2017-03-09_02.27.29-client.txt](https://github.com/whatthedrunk/allthemods/files/831936/crash-2017-03-09_02.27.29-client.txt)

About the server. Its the official ATM:expert so im not sure if it does. They managed to remove the Forestry engine but the chunk is still corrupt there going to try to remove the Rockhounding  Mineral Analyzer next. 

Also i tested in single player (Same version). Its only Forestry generators that cause the client to crash and dupe the generator. I could only get this to occur when placing a forestry generator next to any rockhounding machine that does NOT have an induction coil in its fuel slot. If an induction coil is present the fuel slot i didnt get a client crash. BUT if you accidentally pull the induction coil out while a forestry generator is next to the rockhounding machine that the coil was removed from the server crashes.

**Comment by Dijkstra1** [comment]
I dont use sponge forge

**Comment by al132** [comment]
Fixed in version 1.0.29
