### ISSUE TITLE
[ATM1] 2.5 Old worlds (pre 2.5) dont show up in single player screen after starting, but are perfect in 2.4

### ISSUE THREAD

**Issue by DietmarKrause** [whatthedrunk/allthemods#447]
Issue Description:
After update from ATM1 2.4 to 2,5 even after fresh install in a new instance none of my older worlds are shown in the selecting screen (after copying Save folder, Journeymap folder, the files options.txt and server.dat as i always do from old instance to new after having it started without them a first time).
They are fine in 2.4 (2x checked by downgrading in the same instance to 2,4 = fine worlds and re-installing 2,5). A new world can be created in 2,5 and is fine in loading. Only this new world is shown to select but in the save folder there are the unloadable worlds, too. Every world was standard made which in the past always means Bioms o plenty as far as know. 
To sum up: no old world of ATM1 constructed with bioms o plenty show up after updating to 2.5 but are definitly perfect in 2,4. 
Note: Make sure you update to the latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:
No old worlds to select from after 1.25, all worlds there and playable after Downgrading to 1.24

What you expected to happen:
Play old worlds in 2.5 build with bioms o plenty
Steps to reproduce:
try to play  an old  bioms o plenty world (as old as possible....) and try to find it after update to 2.5
1.
2.
3.
...

The Version of All the Mods:
ATM 1 1.25
Added mods (Optifine, Fastcraft, etc.):

1. no mods added but updated NVIDEA driver to latest version before as far as i remember 378.70 fro 1st March 2017. I think it has nothing to do with this issue, (works fine in vanilla and 1.25 and new world is loading fine, so no problem of driver i think)
2.
3.
...

**Comment by DietmarKrause** [comment]
problem is still thee with update 2.51b

**Comment by Rhyshh1012** [comment]
I'm also getting this exact issue with 2.51b.

**Comment by unascribed** [comment]
I'm sorry my mod caused so much grief. >.<

This has been fixed on Forge's end, but for now as a workaround you can delete the DIM-31 directory. It's not yet used by the mod.

**Comment by PotDucky** [comment]
Fixed in This should be fixed in v2.52 , Added correlated back as no easy way for me to automatically fix issue. (was only really removed as it seemed underused)

**Comment by DietmarKrause** [comment]
is fixed with latest update. Worlds works again. Thank you
