### ISSUE TITLE
ATM1-1.10.2-v2.4 Actually Additions Traveler's Sack allows duplication of items.

### ISSUE THREAD

**Issue by JaSpr** [whatthedrunk/allthemods#449]
Issue Description: Using the Traveler's sack set to auto-input on, if you drop an item, and then pick it up with an empty hand, it will add it back to your inventory AND add it to the traveler's sack inventory.  Ellpeck (who maintains AA) claims it is a mod conflict: [Issue on AA github](https://github.com/Ellpeck/ActuallyAdditions/issues/674).

The Version of All the Mods: ATM1-1.10.2-v2.4

**Comment by OrdinatorStouff** [comment]
Thanks for the report -- Closing this per PotDucky .. assuming it's been fixed or will be in next update

**Comment by PotDucky** [comment]
To clarify, Confirmed as issue with SpongeForge which is unsupported. https://github.com/SpongePowered/SpongeForge/issues/1351
