### ISSUE TITLE
ATS: Quest Issue

### ISSUE THREAD

**Issue by newyevon2** [whatthedrunk/allthemods#450]
Issue Description: Quest Not Working

What happens:Compressed dirt quest not detecting compressed dirt.

What you expected to happen:Compressed dirt to be detected so i can receive the reward.

Steps to reproduce:

1.Get to compressed dirt quest
2.make compressed dirt
3.see detect/submit button not work

The Version of All the Sky:1.0.6

Added mods (Optifine, Fastcraft, etc.):Nothing

**Comment by OrdinatorStouff** [comment]
Thanks for the report. ExtraUtils name-change again it looks like. I didn't realize it affected quests as well. I'll add this to the list for fixes next update

**Comment by OrdinatorStouff** [comment]
will be fixed in 1.0.7
