### ISSUE TITLE
[ATM:E] Vector Plates all orienting South

### ISSUE THREAD

**Issue by snaiperskaya** [whatthedrunk/allthemods#452]
All Dark Utilities vector plates reorient themselves to point South when placed. This included already placed plates, breaking existing mob farms. This occurred when updating ATM:E from 1.0.28 to 1.0.30, but a quick search has not turned up this issue elsewhere (i.e. nothing reported in Dark Utilities bug tracker yet).

The Version of All the Mods: ATM:E 1.0.30

Added mods (Optifine, Fastcraft, etc.):

1. Optifine

**Comment by thecybermind** [comment]
It's been [fixed in build 118 of Dark Utilities](https://github.com/Darkhax-Minecraft/Dark-Utilities/issues/51) already. If you're playing single player, you can just update the mod. Servers will either have to force their users to update the mod or wait for the pack to update.

**Comment by OrdinatorStouff** [comment]
Should be fixed as of 1.0.33b
