### ISSUE TITLE
Server Crash updating 2.4 - 2.51b

### ISSUE THREAD

**Issue by acanady** [whatthedrunk/allthemods#454]
Issue Description:

Crash when updating to 2.51b

Note: Make sure you update to the latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:
Server loads fine, but when trying to login to a pre-existing world the game crashes.
It works fine if you create a new world.
What you expected to happen:
To login without issue into pre-2.5 worlds
Steps to reproduce:

1. create a server world in v 1.51
2. update to 2.4
3. load the 2.4 world
4. update to 2.51b
5. load the 2.51b world
...

The Version of All the Mods:
version 2.51b
Added mods (Optifine, Fastcraft, etc.):

1. Optifine
2. Project E pe1.2.0.jar
3. 
...

[crash-2017-03-11_16.20.47-server.txt](https://github.com/whatthedrunk/allthemods/files/836168/crash-2017-03-11_16.20.47-server.txt)

**Comment by meatball0417** [comment]
It seems to be the server not recognizing the world as a missing-id world, so it wouldn't fix the id-missing by itself which causes client side to render something strange(for me is my floor become leaves ) and crash the client side.
It may be related to another issue that 2.5 versions can't find worlds before 2.5.

**Comment by saytheb** [comment]
Having the same issue when I try to upgrade from 2.4 to 2.51. Client and server will load, but server is constantly throwing exceptions for ticking null entities. Once the client logs in, all blocks have changed to something random, and while looking around the client will crash.

**Comment by DietmarKrause** [comment]
may be related to https://github.com/whatthedrunk/allthemods/issues/447 or same issue

**Comment by PotDucky** [comment]
This should be fixed in v2.52
