### ISSUE TITLE
Pam's Harvest Craft Salt not craftable

### ISSUE THREAD

**Issue by acanady** [whatthedrunk/allthemods#456]
Issue Description: Cannot craft pam's harvest craft salt, only mekanism salt and it's a pain  to do as you need water buckets instead of fresh water, also the mod cooking for blockheads doesn't recognize the crafting recipe for mekanism salt

Note: Make sure you update to the latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:
Can't craft Pam's Harvest craft salt 
What you expected to happen:
Ability to craft salt
Steps to reproduce:

1. Try to craft salt from Pam's Harvest Craft
2.
3.
...

The Version of All the Mods: 2.4

Added mods (Optifine, Fastcraft, etc.):

1. 
2.
3.
...

**Comment by DietmarKrause** [comment]
As far as i remeber there is some sort of ore converter block and item in the pack, with it you can convert the salt to Pams type as far as i can remember.

**Comment by acanady** [comment]
Yeah you can, but the issue is that you can't craft the salt to begin with. The recipe is being overriden by another recipe called bubbly water, also from Pams Harvest craft, I wonder if it's a bug with that version? Or maybe it's a config issue?

**Comment by Dijkstra1** [comment]
when crafting in your 2x2 crafting or the Minecraft crafting is there an arrow that you can click to go between conflicting recipes

**Comment by BloodWorkXGaming** [comment]
Fixed it in the new version of the config on this github:
https://github.com/AllTheMods/ATM-1

just replace your configs with those on there

**Comment by PotDucky** [comment]
Will be fixed in next version.

https://github.com/AllTheMods/ATM-1/commit/45abddf09f83a6ba18a41f37f32f164315f776fd
