### ISSUE TITLE
[ATM] [1.10.2] [v2.52] ATM Lathe produces useless iron rods

### ISSUE THREAD

**Issue by Kayinnasaki** [whatthedrunk/allthemods#458]
Advanced Rocketery's lathe produces substratum rods which aren't oredicted in a way that makes them have any use, so the mod's own tool for making  rods is a complete waste.  Not sure if there is a reason substratum iron ore doesn't count as an iron stick or if the lathe should produce another type of iron stick but clearly this an oversight.

**Comment by PotDucky** [comment]
Thanks for the report! Fixed in 2.52b , As well as tidying up other Rods/Plates/Gears.
