### ISSUE TITLE
Can´t get shaders to work.

### ISSUE THREAD

**Issue by Toasti60009** [whatthedrunk/allthemods#46]
I´ve been trying to install a shader but it instantly crashes when i select a shader in the shaders menu of Optifine.
I can install a shader on Vanilla minecraft without any problems.

This is the crash log:

[crash-2016-07-15_20.08.18-client.txt](https://github.com/whatthedrunk/allthemods/files/366705/crash-2016-07-15_20.08.18-client.txt)

I allredy read through lot´s of reddit posts etc. but nothing helped.
I would really appreciate your help.

Sry if this text is a  hard to read.
English is not my mother tongue.

**Comment by Carrots4U** [comment]
Chisels & Bits is not compatible with shaders so we aren't able to help you there, sorry. I recommend bringing this issue up with them, but chances are they already know about it.

**Comment by Toasti60009** [comment]
Oh ok thanks for the quick reply.
