### ISSUE TITLE
[ATM1] EnvironmentalTech JSON is malformed which breaks the Ore Miner

### ISSUE THREAD

**Issue by ReillyBrogan** [whatthedrunk/allthemods#461]
Issue Description:
In All The Mods 2.52b in both the server and client configurations the JSON file located at config/environmentaltech/void_ore_miner/minable is malformed which causes the ores to be generated by the Void Ore Miner or show in JEI. I'm not sure why this is happening as the config is correct here in this repository.

The Version of All the Mods:
2.5.2b

Added mods (Optifine, Fastcraft, etc.):
Flux Points
Ore Excavation

...
Line 236 is currently:
`    {
      "oreName": "oreOsmium",
      "focusColor": "purple",
      "weight": 28
    }
        {
`
and it should be
`    {
      "oreName": "oreOsmium",
      "focusColor": "purple",
      "weight": 28
    },
        {
`

while line 296 is 
`	  {
      "oreName": "oreBauxite",
      "focusColor": "brown",
      "weight": 18
    },
  ]
}
`
when it should be:
`	  {
      "oreName": "oreBauxite",
      "focusColor": "brown",
      "weight": 18
    }
  ]
}
`

**Comment by PotDucky** [comment]
Will be fixed in next version (out today or tomorrow)

https://github.com/AllTheMods/ATM-1/commit/385b548d53375d4c99ab76ec76d634bb64ac2309
