### ISSUE TITLE
[ATM2] Vanilla Slime spawning mechanics bugged or inhibited

### ISSUE THREAD

**Issue by MageOmega** [whatthedrunk/allthemods#468]
Issue Description: As per Ordinator's request, posting here to help find the cause to this. Vanilla slime spawning mechanic seems to be inhibited or disabled by some mod or config. Slimes to not spawn in slime chunks, and even certain player made spawners have issues spawning them.

Note: Make sure you update to the latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens: The server I am on is running an ATM2 instance set up with minimal changes to config(only change was disabling spice of life) Regular world gen(BoP or ATG was not used) I tried setting up a slime farm to farm for slime pearls. I spawned in a slime in a bucket to find a nearby slime chunk and once located, dug out all the stone under y level 40. I set up multiple 3 high platforms for slimes to spawn on, but nothing spawned. Tried for 2 hours to get slimes to spawn in slime chunk(confirmed that it was a slime chunk by using botania's slime in a bottle and quarks slime in a bucket, along with the slime chunk finding online tool based on seed.) Tried different options, from removing lighting(which multiple hostile mobs spawned then, so it wasn't a mob cap issue) to claiming/unclaiming the chunk. No slimes spawned at all.

Finally decided to try a Extra utilities 2 Resturbed spawner to farm slimes. Went to a swampland biome and DID find a slime. Used a spawner changer and drop of evil to make resturbed and placed 20 speed upgrades into the spawner. No slimes spawned with this spawner.

Moved the resturbed spawner to the Swamp biome, no slimes spawned. Moved the spawner to the previously found slime chunk, slimes DID spawn, but it was only the tiny slime once every 40-60 seconds(VERY slow for a max speed resturbed spawner)

What you expected to happen: Vanilla mechanics should have allowed slimes to spawn freely in the slime chunk, but either a mod conflict or config issue is preventing that from happening altogether. 

Steps to reproduce:

1. Find a slime chunk
2. Dig everything under y level 40 and make platforms for slimes to spawn on
3. Wait for slimes
...

The Version of All the Mods: All the Mods 2 v0.65

Added mods (Optifine, Fastcraft, etc.):

1.
2.
3.
...

**Comment by OrdinatorStouff** [comment]
We've been noticing this on the official ATM2 server as well so there is something wrong in some settings or whatnot that we need to sort out.

**Comment by OrdinatorStouff** [comment]
Closing this issue so it can be tracked on the new tracker instead
