### ISSUE TITLE
crafting duplication bug

### ISSUE THREAD

**Issue by Mumberthrax** [whatthedrunk/allthemods#5]
allthemods 1.9.4 v0.2.1

Crafting oak wood into planks in the player inventory crafting. cannot shift-click product. clicking the product works as expected, except input glitches out and does not decrease. by crafting a single log and repeatedly clicking and placing the product into the player inventory, an infinite amount of oak planks can be created.

This appears to work when crafting a crafting table as well.

**Comment by Mumberthrax** [comment]
bug mentioned by another user here: http://minecraft.curseforge.com/projects/all-the-mods?comment=40

**Comment by whatthedrunk** [comment]
Can you give 0.2.3 a shot? Pretty sure I fixed this now. It was hard to find because we test on a server and it only happened for me once I went local.

**Comment by Mumberthrax** [comment]
yep, 0.2.3 no longer has the issue for me. I was playing in singleplayer - sorry for not mentioning that previously.

**Comment by whatthedrunk** [comment]
No problem, glad its fixed because thats a game breaking bug.. Bug has been reported to HQM hopefully we can add the quests back soon.
