### ISSUE TITLE
BiomesO'Plenty Saplings aren't compatible with some sapling recipes

### ISSUE THREAD

**Issue by Traville** [whatthedrunk/allthemods#50]
Confirmed non-compatible:
-Lexica Botanica recipe
-Any Pam's Harvestcraft recipe

**Comment by Carrots4U** [comment]
They are set to use certain saplings so nothing I can do to help sorry. Botania's lexica is meant for some reason to use only vanilla saplings and Pam's Harvestcraft fruit trees are meant to only be able to used with a certain type of sapling.
