### ISSUE TITLE
[1.10.2-v.1.2] Reading CookingForBlockheads #NoFilter Edition causes fatal error d/c

### ISSUE THREAD

**Issue by CorwinJV** [whatthedrunk/allthemods#51]
Repro steps:
Craft a book
Cook the book
Craft CookingForBlockheads #NoFilter edition by putting the book you just crafted into your crafting window and pulling it out

Right click on CookingForBlockheads #NoFilter edition

Observe error "Fatal error. This connection has been terminated"

**Comment by whatthedrunk** [comment]
Verified. Have you submitted this to the mod author?

**Comment by DnTheMn** [comment]
#NoFilter Edition has already been disabled in the latest version because of this issue, it will be re-enabled once it's fixed. #154

**Comment by DnTheMn** [comment]
@whatthedrunk update needed :arrow_up:
