### ISSUE TITLE
Crashing when hit by negative Potion effect

### ISSUE THREAD

**Issue by athelred** [whatthedrunk/allthemods#52]
I keep crashing while fighting mobs that apply potion effects.  This is the crash log:

http://pastebin.com/Qm3AjBHT

I think it may be some interaction between PSI armor and potion effects generated by mobs (withering and poison seem to be the two main offenders).  I have this spell in my psi armor :

http://pastebin.com/rEEcsAix

I might be very wrong about the root cause though.  It is defiantly related to the negative potion effects.  It does not occur all of the time, but often enough to be less than pleasant.  Once the crash is encountered it will continue to be encountered upon reload.  You can usually break out of the loop by forcing peaceful mode, and removing the PSI armor before the next tick of whatever negative effect is causing it.

**Comment by Carrots4U** [comment]
Cannot reproduce, can you confirm if it still happening?

**Comment by Carrots4U** [comment]
I'm going to assume it's either fixed or non-exist. Re-open if still happening.
