### ISSUE TITLE
Inventory Tweaks sorting does not sort in Actually Additions Storage Crates

### ISSUE THREAD

**Issue by Traville** [whatthedrunk/allthemods#54]
Error Message in chat for Small Storage Crate:
InvTweaks: [ERROR] [3] Failed to sort container: null(l101 in HandlerSorting..java)

**Comment by Janitor53** [comment]
Temporary workaround: close crate's GUI and open again.

**Comment by Carrots4U** [comment]
Seems fixed in the latest version, reopen if I'm wrong or it comes back.
