### ISSUE TITLE
[1.10 - 1.4] Refined Storage Issues

### ISSUE THREAD

**Issue by ozhound** [whatthedrunk/allthemods#55]
Unable to changed items (delete or change qty) in the interface export row. it appears to modify these items but when you reopen the GUI changes are reverted.

The only what to modify is to break the interface and replace it in the world

**Comment by Carrots4U** [comment]
Can you confirm if it is fixed in the latest update?

**Comment by ozhound** [comment]
nope, still cannot change the items in the interface as per the OP

**Comment by raoulvdberge** [comment]
I'm working on a fix, but it would be helpful if you'd have reported this on my repository instead.

**Comment by raoulvdberge** [comment]
This issue has been fixed in https://github.com/raoulvdberge/refinedstorage/commit/1c2d2815738a9ba94bb0c4ac53aae5aa96f00aa2

But I have yet to release this fix in a version.

**Comment by Carrots4U** [comment]
Thank you for the fix @raoulvdberge We report any issues to the devs if we can't figure it out ourself. This one slipped through, thanks for the quick fix again!
