### ISSUE TITLE
No crafting recipe for steel dust

### ISSUE THREAD

**Issue by TheBraveToast** [whatthedrunk/allthemods#56]
Theres no crafting recipe for steel dust -> steel ingots. Its turned off in the configs

**Comment by whatthedrunk** [comment]
I thought I only removed the easy recipe. I will look into this tonight, thanks.

**Comment by whatthedrunk** [comment]
This will be fixed in tomorrows update.

**Comment by Apocryphai** [comment]
Workaround: Steel dust will melt in the TiCon smeltery.

**Comment by whatthedrunk** [comment]
This should have been fixed in 1.4 but let me know if there are any other issues with it.
