### ISSUE TITLE
[1.10.2] Activate Crafting Tweaks for Tinkers' Construct crafting tables

### ISSUE THREAD

**Issue by jmcaffee** [whatthedrunk/allthemods#60]
To get the Crafting Tweaks buttons to show up for TiCon crafting tables, add the following:

In the `minecraft/config/craftingtweaks.cfg` file, add the `tconstruct` line:

```
addons {
    # enabled, buttons_only, hotkeys_only or disabled [default: enabled]
    S:minecraft=enabled

    # enabled, buttons_only, hotkeys_only or disabled [default: enabled]
    S:tconstruct=enabled
}
```

In the `minecraft/config/TinkerModules.cfg` file, set crafting tweaks to true:

```
B:craftingtweaksIntegration=true
```

*Note: the craftingtweaksIntegration line only shows up after starting the pack the first time.*

**Comment by whatthedrunk** [comment]
Thanks for figure this out! I will make sure to get it into the pack hopefully tomorrow.

**Comment by whatthedrunk** [comment]
and it works now :D thanks again, hit me up on curse some time if you want to chat.
