### ISSUE TITLE
[1.10.2 1.4] Zombie pigmen always hostile

### ISSUE THREAD

**Issue by Chaogomu** [whatthedrunk/allthemods#62]
As the title says, pigmen don't start out neutral. they spawn hostile. Default Rough Mobs config says that pigmen should only turn hostile if you attack one, get too close to one, or break a block near one.

**Comment by whatthedrunk** [comment]
Seems to be a bug with the rough mobs config. I will take a look at it tonight but you can disable the mod for now if its too hard.

**Comment by whatthedrunk** [comment]
Should be fixed tonight in 1.6 let me know after you try this version if you are better.
