### ISSUE TITLE
Mods to add/Look into

### ISSUE THREAD

**Issue by Noname500** [whatthedrunk/allthemods#65]
zoology
http://minecraft.curseforge.com/projects/zoology

psionic upgrades
http://minecraft.curseforge.com/projects/psionic-upgrades?gameCategorySlug=mc-mods&projectID=247038

natural pledge
http://minecraft.curseforge.com/projects/natural-pledge?gameCategorySlug=mc-mods&projectID=247704#c2
 
tails
http://minecraft.curseforge.com/projects/tails?gameCategorySlug=mc-mods&projectID=223584

woot
http://minecraft.curseforge.com/projects/woot?gameCategorySlug=mc-mods&projectID=244049

**Comment by CaptainPepperjack** [comment]
+1 for Natural Pledge. I want more botania toys!

**Comment by whatthedrunk** [comment]
I added a few of these for testing in the new build going out in a few.
