### ISSUE TITLE
Breaking Pure Daisy with Diamond Scythe crashes client - repeatable

### ISSUE THREAD

**Issue by midmopub** [whatthedrunk/allthemods#68]
n/a

**Comment by Carrots4U** [comment]
Just for reference, official issue can be found here; https://github.com/williewillus/Botania/issues/411

**Comment by whatthedrunk** [comment]
Closing the Issue just like Botania is. Once BOP fixes it I will add it to the pack. Thanks for the report!
https://github.com/Glitchfiend/BiomesOPlenty/issues/816
