### ISSUE TITLE
platform mod problem

### ISSUE THREAD

**Issue by grazazel** [whatthedrunk/allthemods#7]
ried the platform mod on server made the platformer block fine and placed it, i put oak planks in pulled out the items but when I tried to place them they vanished and the materials were back in the platformer.  mod works fine in ssp. I checked my internet and thats fine and can interact with other blocks no problem

**Comment by Carrots4U** [comment]
It is now solved in the latest mod update, which we will get onto the modpack hopefully tonight or tomorrow morning.
