### ISSUE TITLE
[BUG][1.6-Hotfix] Acceleration Wand from Roots doesnt work

### ISSUE THREAD

**Issue by ozhound** [whatthedrunk/allthemods#70]
Doesn't work on any machine. Tested on Vanilla Furnace, EnderIO Sag and Alloy smelter.

**Comment by Noname500** [comment]
The EIO machines yes dont work no idea why but the wand works on meknism machines just fine for me

**Comment by Carrots4U** [comment]
I've seen Direwolf in Forgecraft using it fine, on both vanilla and EnderIO, so I'm going to assume the fix is coming soon?

**Comment by ozhound** [comment]
Yeah I saw him use it fine as well, but that was a week or so ago, and the recent update was included by Drunk. so maybe the update actually broke it?

**Comment by RyanP1991** [comment]
Maybe try recreating the wand maybe the update broke the old wands.

**Comment by ozhound** [comment]
nope its never worked, recreated a new one today and its still useless.

**Comment by CvoidWyvern** [comment]
Dire did say on his latest episode that the wand seemed to not work well on EnderIO machines sometimes.

**Comment by ozhound** [comment]
Doesn't work on enderio or deep res

**Comment by DnTheMn** [comment]
"I might wait to release it until Roots v0.200, where we'll have a lot more content. Depends on how much longer that takes."

**Comment by whatthedrunk** [comment]
Guessing this old issue is fixed? Feel free to reopen if its still an issue and I will follow up on it.
