### ISSUE TITLE
[1.10.2 1.6-Hotfix] Sentient Bow not working

### ISSUE THREAD

**Issue by Hazmatik** [whatthedrunk/allthemods#73]
The Sentient Bow from Blood Magic was working fine, I used the tartaric gem to grow will crystals. Put it back in my inventory and now the Sentient Bow isn't working and isn't collecting demonic will. The Sentient Sword will still collect will but the bow stopped working.

**Comment by Carrots4U** [comment]
Fixed I believe in the newer updates!
