### ISSUE TITLE
[Bug][1.6-HotFix] right clicking on a RFTools Liquid Monitor with a RFTool Smart Wrench causes client crash

### ISSUE THREAD

**Issue by ozhound** [whatthedrunk/allthemods#74]
http://pastebin.com/by1xhQHN

**Comment by Apocryphai** [comment]
Happens with most RFTools blocks, it's fixed in rftools-1.10-5.07 / 
mcjtylib-1.10-1.9.9.

**Comment by Carrots4U** [comment]
Thanks for the report, it's fixed in the next update.
