### ISSUE TITLE
Dictionary issues?

### ISSUE THREAD

**Issue by Leasara** [whatthedrunk/allthemods#75]
I can only craft a piston with Oak Planks, any other vanilla wood won't work.  Some recipies that require chests as components will only work with Vanilla chests, and running some Raw Beef through an Alloy Smelter returned Firm Tofu instead of the Steak I wanted.

**Comment by Carrots4U** [comment]
There is something weird going on with your save. Try reinstalling the pack because both of those problems are fine with me.
