### ISSUE TITLE
[1.10.2 1.6-Hotfix] Blood Magic and Mekanism

### ISSUE THREAD

**Issue by TheReidMan1** [whatthedrunk/allthemods#76]
Blood Magic Dagger of Sacrifice does not work with Mekanism Baby Skeletons. It causes one heart of damage instead of killing them outright like with other mobs.

**Comment by RyanP1991** [comment]
If I remember baby zombies were affected by this sometime a go as well not sure if that was fixed.

**Comment by Carrots4U** [comment]
The devs has said Baby mobs are exempt from the Dagger of Sacrifice. It's a "feature".
