### ISSUE TITLE
[1.10.2 1.7] Precision Sawmill shows as Rotary Condensator in the world

### ISSUE THREAD

**Issue by LordGaav** [whatthedrunk/allthemods#77]
After updating to version 1.7, a Precision Sawmill I placed during 1.6-Hotfix now shows as a Rotary Condensator in the world. Accessing the block reveals it is still a Precision Sawmill.

I'm running a remote server using the server pack, and using MultiMC locally.

![mekanism_wrong_block](https://cloud.githubusercontent.com/assets/546693/17226561/63a17d72-550a-11e6-95d0-6cde53b9d18a.png)
![mekanism_wrong_block_2](https://cloud.githubusercontent.com/assets/546693/17226562/63c3fb7c-550a-11e6-9888-3a0d5fdba50e.png)

**Comment by LordGaav** [comment]
It looks like the model in the world actually corresponds a Precision Sawmill, when compared to JEI. The Metallurgic Infuser also shows up as an Enrichtment Chamber. The models in the world are correct however.

Looks like something's up with WAILA.

**Comment by Carrots4U** [comment]
Link for reference, https://bitbucket.org/ProfMobius/waila/issues/273/194-showing-incorrect-block-type-mekanism

**Comment by DnTheMn** [comment]
"This is most likely down to the Maekanism machines, being the same ID and all that makes them different, is the NBT tags this is what JEI does to fix the issue and mod authors, seem to use when they know about it let aidancbrady know about and in about day he got back to me say he had implemented, if WAILA is still an extension, of JEI like it was to NEI, this was be easy for look up, and maybe use fix things like."
