### ISSUE TITLE
Crash/Item ID conflict: Chisels & Bits, Osmium Block and Structural Glass?

### ISSUE THREAD

**Issue by Apocryphai** [whatthedrunk/allthemods#80]
I'm getting a regular client crash that looks like this - http://pastebin.com/fmzzkbfy (full log is at https://www.dropbox.com/s/cgug3suaxfm6izg/ATMcrash_073016_fml-client-3.log?dl=0). The server just gives a disconnection error: http://pastebin.com/tt40avg6

It looks to me like it's something to do with Chisels & Bits and the Mekanism Structural Glass (BlockBasic). When I enable ItemID tooltips (F3+H) the Structural Glass, which is part of a 5x5x5 Mekanism Dynamic Tank, WAILA tooltip thinks it's Osmium Block (#7101/0). If I place a block of Osmium in the world the WAILA tooltip says the same.

Let me know if you need me to do anything to try and help track this down, or if it's just a problem on my end.

**Comment by Carrots4U** [comment]
Do you have any chisels & bits using Structural blocks somewhere on your server? Would you mind possibly removing them all and seeing if you still crash?

**Comment by Apocryphai** [comment]
I have lots of C&B blocks, but none using Structural blocks.

**Comment by Apocryphai** [comment]
Nope, not using shaders. 

OK, I've disabled Optifine and it's not happened for 20 mins now. I'll leave it AFK while I go and cook and see if that's definitely it, but for now it looks most likely that it's an Optifine issue. I should have checked that first, sorry :)

**Comment by Carrots4U** [comment]
Hm well, this is just a shot in the dark, but try removing WAILA, WAILA Harvestability, and WAWLA from both server and client.

**Comment by Apocryphai** [comment]
Done. Same crash, almost immediately this time.

I'm going to see if I can remove my Mekanism Dynamic Tank (without flooding the base with Nutrient Distillation :p ) and see if that stops it.

**Comment by Carrots4U** [comment]
Sorry didn't see your response! Next time reply instead of editing ;) and sure go ahead, just reference the issue here by posting a link when you post it!

**Comment by Apocryphai** [comment]
Remade the dynamic tank again and now the issue has gone away. Can't replicate it. Closing this, will reopen as a Mekanism issue and reference here if I manage to make it happen again.

**Comment by Apocryphai** [comment]
Reported as Mekanism issue : https://github.com/aidancbrady/Mekanism/issues/3534
