### ISSUE TITLE
[1.10.2 1.7] Botania Alchemy Catalyst recipes broken

### ISSUE THREAD

**Issue by Hazmatik** [whatthedrunk/allthemods#81]
JEI says Diorite in mana pool with alchemy catalyst makes Granite, it made Andesite instead, it also says Andesite will make Diorite instead Andesite just uses mana and stays as Andesite.

**Comment by Carrots4U** [comment]
For reference. https://github.com/williewillus/Botania/issues/413

**Comment by Carrots4U** [comment]
Will be fixed next update! Thanks for the report allowing us to get this bug fixed!
