### ISSUE TITLE
Recipe Conflicts

### ISSUE THREAD

**Issue by CaptainPepperjack** [whatthedrunk/allthemods#83]
A few recipe conflicts I've found in the newest update:

-The Architect's Chisel from ArchitectureCraft is overwritten by the Saucepan from Pam's HarvestCraft

-All of the Trapdoors from Quark (Dark Oak, Birch, Acacia, Spruce and Jungle) are being overwritten by the Trapdoors from Malisis Doors

**Comment by Carrots4U** [comment]
I'll take a look :)

**Comment by Carrots4U** [comment]
Fixed in the next update.
