### ISSUE TITLE
NoMoreRecipeConflict mod suggestion

### ISSUE THREAD

**Issue by jaz3001** [whatthedrunk/allthemods#84]
there is a mod called No More Recipe Conflict which, if two items have the same recipe, you can choose which item with that recipe you want to craft. https://minecraft.curseforge.com/projects/stimmedcow-nomorerecipeconflict?gameCategorySlug=mc-mods&projectID=238123

**Comment by Carrots4U** [comment]
It's for 1.9.4, so curse won't let us add it. But if you find conflicting recipes just report those and they get fixed ASAP.
