### ISSUE TITLE
mod suggestions

### ISSUE THREAD

**Issue by FiveEYZ** [whatthedrunk/allthemods#85]
Alot of new mods poping up for 1.10.2, here are some:

https://minecraft.curseforge.com/projects/Flux-Networks
https://minecraft.curseforge.com/projects/better-with-mods
https://minecraft.curseforge.com/projects/cyberware

and again:
https://minecraft.curseforge.com/projects/thuts-elevators (they even work with OC!)

**Comment by boonman4224** [comment]
can you add these thx
https://mods.curse.com/mc-mods/minecraft/229694-matter-overdrive
https://mods.curse.com/mc-mods/minecraft/223628-thaumcraft

**Comment by Carrots4U** [comment]
@boonman4224 Both of those aren't updated to 1.10, Matter Overdrive is for 1.7, and Thaumcraft is 1.8.

**Comment by Carrots4U** [comment]
Thanks for the suggestions, we will look into them and some of them will definitely be added.
