### ISSUE TITLE
Digital Miners disappearing

### ISSUE THREAD

**Issue by RulerOfCakes** [whatthedrunk/allthemods#90]
Looks like Digital Miners from Mekanism can occasionally disappear when placed on the world. I cannot tell how this exactly happens, but so far it has happened multiple times to me and other people playing on servers, it simply disappears randomly. I assume the reason may be players not nearby or chunk not loaded

**Comment by Hazmatik** [comment]
This might be happening on the server I've been playing on as well. Have heard a few players say that theirs was "taken" even though it was set to private which supposedly when they are set to private other players can't break them.

**Comment by Carrots4U** [comment]
I can't see to reproduce this, I've been flying in/out of range of a Digital Miner for a bit now and can't seem to get it to disappear. If someone else can confirm and/or give me a set of steps to reproduce that'd be amazing.

**Comment by whatthedrunk** [comment]
Can't seem to reproduce but it may have been fixed, reopen if you need too.
