### ISSUE TITLE
[1.10.2] Modpack extremly laggy while exploring the overworld

### ISSUE THREAD

**Issue by DietmarKrause** [whatthedrunk/allthemods#92]
Issue Description:

If simply exploring the overworld by flying in one direction or walking, the system is getting more and more laggy until unplayable. (singleplayer, no server play)

What happens:
lags lasting one or more seconds every 3 seconds after moving fast in one direction (for instance to find extreme hills to find emeralds :)

What you expected to happen:
better performance, not that much lags

Steps to reproduce:

1. start world 
2. switch to creative to fly or simply walk in one direction
3. after a short time (200-400 blocks) the lags  will get worse until system completly hangs
...

Version of All the Mods:
1.8 hotfix

Added mods (Optifine, Fastcraft, etc.):

1. none
2.
3.
...

**Comment by whatthedrunk** [comment]
Pregenerating your world with this pack is really needed. Even more so in the last few updates because of all the new underground biomes. Its a little annoying but worth it. 

Here is one way you can do this https://www.youtube.com/watch?v=7WSMgOVsnCU
