### ISSUE TITLE
ExtraUtils2 Golden Lasso uncraftable.

### ISSUE THREAD

**Issue by Zaecus** [whatthedrunk/allthemods#93]
Most recent update caused lasso to be uncraftable. Recipe is still in JEI (or whatever it is), and shift-clicking the + moves everything into the crafting bench, but nothing shows up in the output window with either this method or placing the materials individually. 

Just tried to craft a lasso using four string and four nuggets, double-checked recipe, used shift-click on the + to place the materials. Nothing ever showed up in the output window.

No added or removed mods. No alterations made to any configs or scripts. Pack is exactly as downloaded,

Reporting as bug because: Either being uncraftable is a bug or the recipe showing up in JEI is.

**Comment by Arcanatias** [comment]
Make sure you have exp. The recipe requires 4 levels I think to craft.

**Comment by Zaecus** [comment]
8 apparently. I'll try to pay more attention.
