### ISSUE TITLE
Mekanism weapon and tool rendering

### ISSUE THREAD

**Issue by Arcanatias** [whatthedrunk/allthemods#94]
It seems the tools and weapons from Mekanism (except the flamethrower and atomic 

disassembler) do not render correctly while wielding in 3rd person on the user, other players and mobs. 

They render correctly on the user while in 1st person. I tested in a creative world with all the tools and 

weapons. I am using the 1.9 version of All The Mods with no other mods installed. I also submitted this issue to the Mekanism Github page.

![2016-08-03_02 07 39](https://cloud.githubusercontent.com/assets/20810007/17356855/4ec5f018-591f-11e6-855e-0ef3e5651f73.png)

![2016-08-03_02 07 47](https://cloud.githubusercontent.com/assets/20810007/17356858/560ae018-591f-11e6-89ff-e5d49bf27d16.png)

**Comment by DnTheMn** [comment]
if you have reported it to the mekanism git hub as soon as an update is available we will be updating to it so fear not
