### ISSUE TITLE
ArmorPlus Steel is not in the OreDictionary

### ISSUE THREAD

**Issue by bb010g** [whatthedrunk/allthemods#96]
You obtain it from Steel Ore (which is odd already, considering you have to smelt to get steel) and then can't do anything with it besides make Steel or Electrical ArmorPlus armor. It would be nice if I could actually use it instead of having it sitting in a chest useless or dumping it. It should be under `ingotSteel`.

**Comment by sokratis12GR** [comment]
All the Mods right now uses an old version of ArmorPlus. In the new version you have to craft the steel and the steel ore will be removed and the ore dict will be allowed by default

**Comment by sokratis12GR** [comment]
@bb010g https://ftb.gamepedia.com/Steel#Recipes

**Comment by bb010g** [comment]
Any ETA on the update?

**Comment by sokratis12GR** [comment]
No, but @whatthedrunk is waiting for most of the mods to update to forge 2045+
