### ISSUE TITLE
[1.10.2 v1.9] Chisel "Block of _" non-vanila blocks uncraftable

### ISSUE THREAD

**Issue by CvoidWyvern** [whatthedrunk/allthemods#98]
Issue Description:
Chisel platinum blocks can't be made with substratum platinum blocks, or any other way as there aren't any other platinum blocks

What happens:
Chisel can't chisel platinum blocks

What you expected to happen:
Chisel can chisel platinum blocks

Steps to reproduce:
Place substratum platinum blocks in chisel, or look through JEI for how to make chisel platinum blocks

Version of All the Mods:
1.10.2 v1.9

Added mods (Optifine, Fastcraft, etc.): 
none

Edit: This seems to be the case with any "Block of _" for chisel, no matter what mod the block comes from, other than vanilla blocks.

**Comment by Carrots4U** [comment]
Not quite sure how to fix this, will look into it.

**Comment by CvoidWyvern** [comment]
Could you add a recipe like two blocks together become two of the first chiseled version, and vice versa until there's a better fix?

**Comment by Carrots4U** [comment]
Happy to say it's fixed in the next update! It took me a while to manually add recipes for each block but it's done.
