### ISSUE TITLE
Recipe conflict for fresh milk and cheese

### ISSUE THREAD

**Issue by joshuagore** [whatthedrunk/allthemods#99]
Issue Description:

Recipe conflict with Cheese and Fresh Milk both made from a Bucket of Milk

Note: Make sure you update to latest version first before reporting any bugs! If you are suggestions a mod or config change delete all this.

What happens:

Can only make one.

What you expected to happen:

Have two different recipes.

Steps to reproduce:

1. Look at recipe for Cheese
2. Look at recipe for Fresh Milk

Version of All the Mods:

1.9

Added mods (Optifine, Fastcraft, etc.):

1. Dynmap - server side

**Comment by Carrots4U** [comment]
Will be fixed in the update that isn't a hotfix :smile:
